Repository GetStream/stream-video-swift, pull requests merged in 2023-12, with the labels that each got.

#246 [Docs]Dolby to Stream AudioRoom migration
  docusaurus/docs/iOS/03-guides/15-migration-from-dolby.mdx
Labels: documentation

#249 [Fix]Various bug fixes
  DemoApp/Sources/Components/Stats/DemoVideoCallParticipantOptionsModifier.swift
  Sources/StreamVideoSwiftUI/CallView/CallView.swift
  Sources/StreamVideoSwiftUI/CallView/CornerDraggableView.swift
  Sources/StreamVideoSwiftUI/CallView/LocalParticipantViewModifier.swift
  Sources/StreamVideoSwiftUI/CallingViews/MicrophoneCheckView.swift
  Sources/StreamVideoSwiftUI/CallingViews/PreJoiningView.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoSwiftUITests/CallingViews/MicrophoneCheckView_Tests.swift
  StreamVideoSwiftUITests/CallingViews/__Snapshots__/MicrophoneCheckView_Tests/test_microphoneCheckView_pinned_snapshot.default-light.png
Labels: bug

#251 [Fix]VideoRenderers being added in multiple superviews
  Sources/StreamVideo/WebRTC/SfuMiddleware.swift
  Sources/StreamVideo/WebRTC/WebRTCClient.swift
  Sources/StreamVideoSwiftUI/CallView/LayoutComponents/HorizontalParticipantsListView.swift
  Sources/StreamVideoSwiftUI/CallView/LayoutComponents/SpotlightSpeakerView.swift
  Sources/StreamVideoSwiftUI/CallView/ParticipantsGridView.swift
  Sources/StreamVideoSwiftUI/CallView/VideoParticipantsView.swift
  Sources/StreamVideoSwiftUI/CallView/VideoRenderer.swift
  Sources/StreamVideoSwiftUI/CallView/VisibilityThresholdModifier.swift
Labels: bug, ✅ QAed

#245 Fix Authentication tests
  .github/workflows/cron-checks.yml
  .github/workflows/smoke-checks.yml
  .gitignore
  DemoApp/Sources/Components/Authentication/AuthenticationProvider.swift
  Githubfile
  Scripts/bootstrap.sh
  StreamVideo.xcodeproj/xcshareddata/xcschemes/DemoApp.xcscheme
  SwiftUIDemoAppUITests/Tests/Authentication_Tests.swift
  SwiftUIDemoAppUITests/Tests/CallLifecycleTests.swift
  SwiftUIDemoAppUITests/Tests/CallViewsTests.swift
  SwiftUIDemoAppUITests/Tests/LobbyTests.swift
  SwiftUIDemoAppUITests/Tests/ParticipantActionsTests.swift
  TestTools/Robots/ParticipantRobot.swift
  fastlane/Fastfile
Labels: CI/CD

#253 [Deeplink]Support path callId
  DemoApp/Sources/Components/AppEnvironment.swift
  DemoApp/Sources/Components/AppState.swift
  DemoApp/Sources/Components/Authentication/AuthenticationProvider.swift
  DemoApp/Sources/Components/Deeplinks/DeeplinkAdapter.swift
  DemoApp/Sources/Components/Router.swift
  DemoApp/Sources/DemoApp.swift
  DemoApp/Sources/Views/CallView/CallingView/DetailedCallingView.swift
  DemoApp/Sources/Views/CallView/CallingView/SimpleCallingView.swift
  DemoApp/Sources/Views/CallView/DemoCallingTopView.swift
  DemoApp/Sources/Views/CallView/DemoQRCodeScannerButton.swift
  DemoApp/Sources/Views/ChangeEnvironmentViewModifier/ChangeEnvironmentViewModifier.swift
  DemoApp/Sources/Views/Login/DebugMenu.swift
  StreamVideo.xcodeproj/project.pbxproj
  SwiftUIDemoAppUITests/Tests/DeeplinkTests.swift
  fastlane/sinatra.rb
Labels: enhancement
