Repository GetStream/stream-video-swift, pull requests merged in 2023-09, with the labels that each got.

#149 [Logs]Implement log viewer
  DemoApp/Sources/Components/MemoryLogDestination/LogQueue.swift
  DemoApp/Sources/Components/MemoryLogDestination/MemoryLogDestination.swift
  DemoApp/Sources/Components/MemoryLogDestination/MemoryLogViewer.swift
  DemoApp/Sources/Extensions/DemoApp+Sentry.swift
  DemoApp/Sources/Views/Login/DebugMenu.swift
  StreamVideo.xcodeproj/project.pbxproj
Labels: enhancement

#150 QR scanner in calling view
  DemoApp/Resources/Assets/Assets.xcassets/AccentColor.colorset/Contents.json
  DemoApp/Resources/Assets/Assets.xcassets/capture.imageset/Capture Button.pdf
  DemoApp/Resources/Assets/Assets.xcassets/capture.imageset/Contents.json
  DemoApp/Resources/Assets/Assets.xcassets/textFieldBackground.colorset/Contents.json
  DemoApp/Resources/Assets/Assets.xcassets/textFieldBorder.colorset/Contents.json
  DemoApp/Resources/Assets/Assets.xcassets/viewfinder.imageset/Contents.json
  DemoApp/Resources/Assets/Assets.xcassets/viewfinder.imageset/viewfinder.pdf
  DemoApp/Resources/Entitlements/DemoApp-Debug.entitlements
  DemoApp/Resources/Entitlements/DemoApp.entitlements
  DemoApp/Sources/Components/AppEnvironment.swift
  DemoApp/Sources/Components/CodeScanner/CodeScanner.swift
  DemoApp/Sources/Components/Deeplinks/DeeplinkAdapter.swift
  DemoApp/Sources/Components/Router.swift
  DemoApp/Sources/Extensions/URL+Convenience.swift
  DemoApp/Sources/Views/CallView/CallingView/SimpleCallingView.swift
  DemoApp/Sources/Views/CallView/DemoCallingTopView.swift
  DemoApp/Sources/Views/CallView/DemoQRCodeScannerButton.swift
  DemoApp/Sources/Views/Login/DebugMenu.swift
  Sources/StreamVideoSwiftUI/Models/Toast.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideo.xcodeproj/xcshareddata/xcschemes/DemoApp-DevBeta.xcscheme
Labels: enhancement

#155 Fix/size improvements for smaller devices
  DemoApp/Sources/Components/AppEnvironment.swift
  DemoApp/Sources/Components/Chat/DemoChatAdapter.swift
  DemoApp/Sources/Components/Chat/DemoChatViewFactory.swift
  DemoApp/Sources/Components/Chat/DemoChatViewModel+Injection.swift
  DemoApp/Sources/Components/Chat/DemoChatViewModel.swift
  DemoApp/Sources/Components/DemoAppViewFactory.swift
  DemoApp/Sources/Components/Reactions/ReactionsHelper.swift
  DemoApp/Sources/Components/Router.swift
  DemoApp/Sources/Views/CallModifier/DemoCallModifier.swift
  DemoApp/Sources/Views/CallView/DemoCallContainerView.swift
  DemoApp/Sources/Views/Controls/DemoControls.swift
  DemoApp/Sources/Views/JoinCallView.swift
  DemoApp/Sources/Views/Login/AddUserView.swift
  DemoApp/Sources/Views/Login/DebugMenu.swift
  DemoApp/Sources/Views/Login/LoginView.swift
  DemoApp/Sources/Views/WaitingLocalUserView/DemoWaitingLocalUserView.swift
  Sources/StreamVideo/Controllers/CallController.swift
  Sources/StreamVideo/WebRTC/StreamVideoCaptureHandler.swift
  Sources/StreamVideoSwiftUI/CallViewModel.swift
  Sources/StreamVideoSwiftUI/CallingViews/PreJoiningView.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoSwiftUITests/CallingViews/__Snapshots__/LobbyView_Tests/test_lobbyView_snapshot.default-dark-with_0_participants.png
  StreamVideoSwiftUITests/CallingViews/__Snapshots__/LobbyView_Tests/test_lobbyView_snapshot.default-dark-with_1_participants.png
  StreamVideoSwiftUITests/CallingViews/__Snapshots__/LobbyView_Tests/test_lobbyView_snapshot.default-dark-with_2_participants.png
  StreamVideoSwiftUITests/CallingViews/__Snapshots__/LobbyView_Tests/test_lobbyView_snapshot.default-light-with_0_participants.png
  StreamVideoSwiftUITests/CallingViews/__Snapshots__/LobbyView_Tests/test_lobbyView_snapshot.default-light-with_1_participants.png
  StreamVideoSwiftUITests/CallingViews/__Snapshots__/LobbyView_Tests/test_lobbyView_snapshot.default-light-with_2_participants.png
Labels: enhancement

#159 Update SwiftUI and UIKit tutorials
  docusaurus/docs/iOS/02-tutorials/01-video-calling.mdx
  docusaurus/docs/iOS/02-tutorials/02-audio-room-uikit.mdx
Labels: documentation

#163 [Fix]Deeplink handling
  DemoApp/Resources/Entitlements/DemoApp-Debug.entitlements
  DemoApp/Resources/Entitlements/DemoApp.entitlements
  DemoApp/Sources/AppDelegate.swift
  DemoApp/Sources/Components/AppEnvironment.swift
  DemoApp/Sources/Components/MemoryLogDestination/OSLogDestination.swift
  DemoApp/Sources/Components/Router.swift
  DemoApp/Sources/Extensions/DemoApp+Sentry.swift
  DemoApp/Sources/Views/CallView/CallingView/DetailedCallingView.swift
  StreamVideo.xcodeproj/project.pbxproj
  SwiftUIDemoAppUITests/Tests/DeeplinkTests.swift
  TestTools/UITests/Safari.swift
  TestTools/UITests/XCUIApplication+KeyboardIntroduction.swift
Labels: bug

#165 Fix reactions not showing for remote participants
  DemoApp/Sources/Components/Reactions/ReactionsHelper.swift
  DemoApp/Sources/Views/VideoCallParticipantModifier/DemoVideoCallParticipantModifier.swift
Labels: bug
