Repository GetStream/stream-video-swift, pull requests merged in 2023-10, with the labels that each got.

#166 Performance/update webrtc version
  Package.swift
  StreamVideo.podspec
  StreamVideo.xcodeproj/project.pbxproj
Labels: enhancement

#167 [Fix]Thermal State not updating
  Sources/StreamVideo/Utils/ThermalStateObserver.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoTests/Utils/ThermalStateObserverTests.swift
Labels: bug

#174 Adaptive frame rate depending on thermalState
  DemoApp/Sources/Views/ThermalStateViewModifier/ThermalStateViewModifier.swift
  Sources/StreamVideo/Utils/ThermalStateObserver.swift
  Sources/StreamVideo/WebRTC/WebRTCClient.swift
  Sources/StreamVideoSwiftUI/CallView/VideoRenderer.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoSwiftUITests/CallView/VideoRenderer_Tests.swift
  StreamVideoTests/Utils/ThermalStateObserverTests.swift
Labels: enhancement

#176 [Improvements]Change available size to available frame
  CHANGELOG.md
  DemoApp/Sources/Components/DemoAppViewFactory.swift
  DemoApp/Sources/Examples/Examples.swift
  DemoApp/Sources/Views/VideoCallParticipantModifier/DemoVideoCallParticipantModifier.swift
  Sources/StreamVideoSwiftUI/CallView/CallView.swift
  Sources/StreamVideoSwiftUI/CallView/MinimizedCallView.swift
  Sources/StreamVideoSwiftUI/CallView/Participants/CallParticipantsInfoView.swift
  Sources/StreamVideoSwiftUI/CallView/ParticipantsFullScreenLayout.swift
  Sources/StreamVideoSwiftUI/CallView/ParticipantsGridLayout.swift
  Sources/StreamVideoSwiftUI/CallView/ParticipantsGridView.swift
  Sources/StreamVideoSwiftUI/CallView/ParticipantsSpotlightLayout.swift
  Sources/StreamVideoSwiftUI/CallView/ScreenSharing/ScreenSharingView.swift
  Sources/StreamVideoSwiftUI/CallView/VideoParticipantsView.swift
  Sources/StreamVideoSwiftUI/CallView/VideoRenderer.swift
  Sources/StreamVideoSwiftUI/Livestreaming/LivestreamPlayer.swift
  Sources/StreamVideoSwiftUI/ViewFactory.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoSwiftUITests/CallView/ParticipantsFullScreenLayout_Tests.swift
  StreamVideoSwiftUITests/CallView/ParticipantsGridLayout_Tests.swift
  StreamVideoSwiftUITests/CallView/ParticipantsSpotlightLayout_Tests.swift
  StreamVideoSwiftUITests/CallView/ScreenSharingView_Tests.swift
  TestTools/TestData/ViewFactory.swift
  docusaurus/docs/iOS/02-tutorials/01-video-calling.mdx
  docusaurus/docs/iOS/03-guides/10-view-slots.mdx
  docusaurus/docs/iOS/04-ui-components/02-video-renderer.mdx
  docusaurus/docs/iOS/04-ui-components/07-call/04-active-call.mdx
  docusaurus/docs/iOS/04-ui-components/07-call/07-screen-share-content.mdx
  docusaurus/docs/iOS/04-ui-components/08-participants/01-call-participant.mdx
  docusaurus/docs/iOS/04-ui-components/08-participants/02-call-participants.mdx
  docusaurus/docs/iOS/04-ui-components/08-participants/03-call-participants-info-menu.mdx
  docusaurus/docs/iOS/05-ui-cookbook/03-custom-label.mdx
  docusaurus/docs/iOS/05-ui-cookbook/04-video-layout.mdx
  docusaurus/docs/iOS/05-ui-cookbook/07-video-fallback.mdx
  docusaurus/docs/iOS/05-ui-cookbook/13-pinning-users.mdx
  docusaurus/docs/iOS/06-advanced/04-screensharing.mdx
Labels: documentation, enhancement

#179 Make it easy to record snapshots on CI
  .github/workflows/smoke-checks.yml
  StreamVideoUIKitTests/__Snapshots__/CallViewController_Tests/test_callViewController_outgoingSnapshot.default-dark.png
  StreamVideoUIKitTests/__Snapshots__/CallViewController_Tests/test_callViewController_outgoingSnapshot.default-light.png
  fastlane/Fastfile
Labels: CI/CD

#184 Fix waiting user view appearance
  DemoApp/Sources/Views/WaitingLocalUserView/DemoWaitingLocalUserView.swift
Labels: bug

#188 Fix compilation error on DemoUIKit
  StreamVideo.xcodeproj/project.pbxproj
Labels: bug

#190 Update release flow
  DemoApp/Info.plist
  DemoApp/Sources/Components/AppEnvironment.swift
  DemoApp/Sources/Views/Login/GoogleHelper.swift
  DemoApp/Sources/Views/Login/LoginView.swift
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: bug

#192 [CI] Create PR with SwiftUI snapshots when required
  .github/workflows/smoke-checks.yml
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: CI/CD

#191 Fix issue where tracks weren't enabled when becoming visible
  Sources/StreamVideoSwiftUI/CallView/ParticipantsSpotlightLayout.swift
  Sources/StreamVideoSwiftUI/CallView/VisibilityThresholdModifier.swift
  StreamVideoSwiftUITests/CallView/VisibilityThresholdModifier_Tests.swift
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantWithAudio_snapshot.default-dark-with_1_participants.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantWithAudio_snapshot.default-dark-with_2_participants.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantWithAudio_snapshot.default-dark-with_3_participants.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantWithAudio_snapshot.default-dark-with_4_participants.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantWithAudio_snapshot.default-light-with_1_participants.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantWithAudio_snapshot.default-light-with_2_participants.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantWithAudio_snapshot.default-light-with_3_participants.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantWithAudio_snapshot.default-light-with_4_participants.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantWithoutAudio_snapshot.default-dark-with_1_participants.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantWithoutAudio_snapshot.default-dark-with_2_participants.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantWithoutAudio_snapshot.default-dark-with_3_participants.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantWithoutAudio_snapshot.default-dark-with_4_participants.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantWithoutAudio_snapshot.default-light-with_1_participants.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantWithoutAudio_snapshot.default-light-with_2_participants.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantWithoutAudio_snapshot.default-light-with_3_participants.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantWithoutAudio_snapshot.default-light-with_4_participants.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantsConnectionQuality_snapshot.default-dark-excellent.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantsConnectionQuality_snapshot.default-dark-good.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantsConnectionQuality_snapshot.default-dark-poor.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantsConnectionQuality_snapshot.default-dark-unknown.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantsConnectionQuality_snapshot.default-light-excellent.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantsConnectionQuality_snapshot.default-light-good.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantsConnectionQuality_snapshot.default-light-poor.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantsConnectionQuality_snapshot.default-light-unknown.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantsSpeaking_snapshot.default-dark.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantsSpeaking_snapshot.default-light.png
Labels: bug

#186 Align participants sorting with Web
  DemoApp/Sources/Views/Login/GoogleHelper.swift
  Sources/StreamVideo/CallState.swift
  Sources/StreamVideo/Utils/Sorting.swift
  Sources/StreamVideoSwiftUI/CallViewModel.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoSwiftUITests/CallViewModel_Tests.swift
  StreamVideoTests/CallState/CallState_Tests.swift
  StreamVideoTests/Controllers/CallController_Tests.swift
  StreamVideoTests/Mock/CallParticipant_Mock.swift
  StreamVideoTests/Mock/MockResponseBuilder.swift
  StreamVideoTests/Utils/Sorting_Tests.swift
Labels: enhancement

#175 Use single instance for the microphoneChecker
  DemoApp/Sources/Components/DemoAppViewFactory.swift
  DemoApp/Sources/Views/CallView/DemoCallView.swift
  DemoApp/Sources/Views/CustomCallView.swift
  Sources/StreamVideoSwiftUI/CallView/LocalParticipantViewModifier.swift
  Sources/StreamVideoSwiftUI/CallingViews/MicrophoneChecker.swift
  Sources/StreamVideoSwiftUI/CallingViews/PreJoiningView.swift
  Sources/StreamVideoSwiftUI/CallingViews/iOS13/PreJoiningView_iOS13.swift
  StreamVideoSwiftUITests/CallingViews/MicrophoneChecker_Tests.swift
Labels: enhancement

#200 Fix flaky E2E tests
  .github/workflows/cron-checks.yml
  .github/workflows/smoke-checks.yml
  SwiftUIDemoAppUITests/Robots/UserRobot+Asserts.swift
  SwiftUIDemoAppUITests/Tests/DeeplinkTests.swift
  TestTools/Robots/Sinatra.swift
  TestTools/UITests/Safari.swift
  fastlane/sinatra.rb
Labels: CI/CD

#208 [UI/UX]Update ControlsView with CornerClipper
  DemoApp/Sources/Views/Controls/DemoControls.swift
  Sources/StreamVideoSwiftUI/CallView/CallControlsView.swift
  Sources/StreamVideoSwiftUI/CallView/CallView.swift
  Sources/StreamVideoSwiftUI/Utils/ClipCorners.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoSwiftUITests/CallView/__Snapshots__/CallControlsView_Tests/test_callControlsView_snapshot.default-dark.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/CallControlsView_Tests/test_callControlsView_snapshot.default-light.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ReconnectionView_Tests/test_reconnectionView_snapshot.default-dark.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ReconnectionView_Tests/test_reconnectionView_snapshot.default-light.png
  StreamVideoSwiftUITests/CallingViews/__Snapshots__/CallConnectingView_Tests/test_callConnectingView_snapshot.default-dark.png
  StreamVideoSwiftUITests/CallingViews/__Snapshots__/CallConnectingView_Tests/test_callConnectingView_snapshot.default-light.png
  StreamVideoSwiftUITests/CallingViews/__Snapshots__/JoiningCallView_Tests/test_joiningCallView_snapshot.default-dark.png
  StreamVideoSwiftUITests/CallingViews/__Snapshots__/JoiningCallView_Tests/test_joiningCallView_snapshot.default-light.png
  StreamVideoSwiftUITests/CallingViews/__Snapshots__/OutgoingCallView_Tests/test_outgoingCallView_snapshot.default-dark.png
  StreamVideoSwiftUITests/CallingViews/__Snapshots__/OutgoingCallView_Tests/test_outgoingCallView_snapshot.default-light.png
  StreamVideoSwiftUITests/Utils/CornerClipper_Tests.swift
  StreamVideoSwiftUITests/Utils/__Snapshots__/CornerClipper_Tests/test_cornerClipper_allCorners.default-dark.png
  StreamVideoSwiftUITests/Utils/__Snapshots__/CornerClipper_Tests/test_cornerClipper_allCorners.default-light.png
  StreamVideoSwiftUITests/Utils/__Snapshots__/CornerClipper_Tests/test_cornerClipper_cornerRadiusBottom.default-dark.png
  StreamVideoSwiftUITests/Utils/__Snapshots__/CornerClipper_Tests/test_cornerClipper_cornerRadiusBottom.default-light.png
  StreamVideoSwiftUITests/Utils/__Snapshots__/CornerClipper_Tests/test_cornerClipper_cornerRadiusBottomLeft.default-dark.png
  StreamVideoSwiftUITests/Utils/__Snapshots__/CornerClipper_Tests/test_cornerClipper_cornerRadiusBottomLeft.default-light.png
  StreamVideoSwiftUITests/Utils/__Snapshots__/CornerClipper_Tests/test_cornerClipper_cornerRadiusBottomRight.default-dark.png
  StreamVideoSwiftUITests/Utils/__Snapshots__/CornerClipper_Tests/test_cornerClipper_cornerRadiusBottomRight.default-light.png
  StreamVideoSwiftUITests/Utils/__Snapshots__/CornerClipper_Tests/test_cornerClipper_cornerRadiusLeading.default-dark.png
  StreamVideoSwiftUITests/Utils/__Snapshots__/CornerClipper_Tests/test_cornerClipper_cornerRadiusLeading.default-light.png
  StreamVideoSwiftUITests/Utils/__Snapshots__/CornerClipper_Tests/test_cornerClipper_cornerRadiusLeadingDiagonal.default-dark.png
  StreamVideoSwiftUITests/Utils/__Snapshots__/CornerClipper_Tests/test_cornerClipper_cornerRadiusLeadingDiagonal.default-light.png
  StreamVideoSwiftUITests/Utils/__Snapshots__/CornerClipper_Tests/test_cornerClipper_cornerRadiusTop.default-dark.png
  StreamVideoSwiftUITests/Utils/__Snapshots__/CornerClipper_Tests/test_cornerClipper_cornerRadiusTop.default-light.png
  StreamVideoSwiftUITests/Utils/__Snapshots__/CornerClipper_Tests/test_cornerClipper_cornerRadiusTopLeft.default-dark.png
  StreamVideoSwiftUITests/Utils/__Snapshots__/CornerClipper_Tests/test_cornerClipper_cornerRadiusTopLeft.default-light.png
  StreamVideoSwiftUITests/Utils/__Snapshots__/CornerClipper_Tests/test_cornerClipper_cornerRadiusTopRight.default-dark.png
  StreamVideoSwiftUITests/Utils/__Snapshots__/CornerClipper_Tests/test_cornerClipper_cornerRadiusTopRight.default-light.png
  StreamVideoSwiftUITests/Utils/__Snapshots__/CornerClipper_Tests/test_cornerClipper_cornerRadiusTrailing.default-dark.png
  StreamVideoSwiftUITests/Utils/__Snapshots__/CornerClipper_Tests/test_cornerClipper_cornerRadiusTrailing.default-light.png
  StreamVideoSwiftUITests/Utils/__Snapshots__/CornerClipper_Tests/test_cornerClipper_cornerRadiusTrailingDiagonal.default-dark.png
  StreamVideoSwiftUITests/Utils/__Snapshots__/CornerClipper_Tests/test_cornerClipper_cornerRadiusTrailingDiagonal.default-light.png
  StreamVideoUIKitTests/__Snapshots__/CallViewController_Tests/test_callViewController_outgoingSnapshot.default-dark.png
  StreamVideoUIKitTests/__Snapshots__/CallViewController_Tests/test_callViewController_outgoingSnapshot.default-light.png
Labels: enhancement

#220 Fix compilation errors on iOS 14
  DemoApp/Sources/Components/Stats/RawStatsView.swift
  DemoApp/Sources/Views/CallView/DemoCallsView.swift
  Sources/StreamVideoSwiftUI/CallView/Participants/InviteParticipantsView.swift
Labels: bug

#221 LongPress to focus on LocalVideo
  CHANGELOG.md
  DemoApp/Sources/Components/DemoAppViewFactory.swift
  DemoApp/Sources/Views/LongPressToFocusViewModifier/LongPressToFocusViewModifier.swift
  DemoApp/Sources/Views/VideoCallParticipantModifier/DemoVideoCallParticipantModifier.swift
  README.md
  Sources/StreamVideo/Call.swift
  Sources/StreamVideo/Controllers/CallController.swift
  Sources/StreamVideo/WebRTC/VideoCapturer.swift
  Sources/StreamVideo/WebRTC/WebRTCClient.swift
  Sources/StreamVideoSwiftUI/CallContainer.swift
  StreamVideo.xcodeproj/project.pbxproj
  docusaurus/docs/iOS/05-ui-cookbook/15-long-press-to-focus.mdx
Labels: enhancement

#210 [UI/UX]Fix discrepancies between Screensharing/Spotlight
  .github/workflows/smoke-checks.yml
  Sources/StreamVideoSwiftUI/CallView/LayoutComponents/HorizontalParticipantsListView.swift
  Sources/StreamVideoSwiftUI/CallView/LayoutComponents/SpotlightSpeakerView.swift
  Sources/StreamVideoSwiftUI/CallView/ParticipantsSpotlightLayout.swift
  Sources/StreamVideoSwiftUI/CallView/ScreenSharing/ScreenSharingView.swift
  Sources/StreamVideoSwiftUI/ViewFactory.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoSwiftUITests/CallView/LayoutComponents/HorizontalParticipantsListView_Tests.swift
  StreamVideoSwiftUITests/CallView/LayoutComponents/SpotlightSpeakerView_Tests.swift
  StreamVideoSwiftUITests/CallView/LayoutComponents/__Snapshots__/HorizontalParticipantsListView_Tests/test_layout_participantsWithAudio_withAllInfoAndSmallerSize_viewWasConfiguredCorrectly.default-dark.png
  StreamVideoSwiftUITests/CallView/LayoutComponents/__Snapshots__/HorizontalParticipantsListView_Tests/test_layout_participantsWithAudio_withAllInfoAndSmallerSize_viewWasConfiguredCorrectly.default-light.png
  StreamVideoSwiftUITests/CallView/LayoutComponents/__Snapshots__/HorizontalParticipantsListView_Tests/test_layout_participantsWithAudio_withAllInfo_viewWasConfiguredCorrectly.default-dark.png
  StreamVideoSwiftUITests/CallView/LayoutComponents/__Snapshots__/HorizontalParticipantsListView_Tests/test_layout_participantsWithAudio_withAllInfo_viewWasConfiguredCorrectly.default-light.png
  StreamVideoSwiftUITests/CallView/LayoutComponents/__Snapshots__/HorizontalParticipantsListView_Tests/test_layout_participantsWithAudio_withoutAllInfo_viewWasConfiguredCorrectly.default-dark.png
  StreamVideoSwiftUITests/CallView/LayoutComponents/__Snapshots__/HorizontalParticipantsListView_Tests/test_layout_participantsWithAudio_withoutAllInfo_viewWasConfiguredCorrectly.default-light.png
  StreamVideoSwiftUITests/CallView/LayoutComponents/__Snapshots__/HorizontalParticipantsListView_Tests/test_layout_participantsWithoutAudio_withAllInfoAndSmallerSize_viewWasConfiguredCorrectly.default-dark.png
  StreamVideoSwiftUITests/CallView/LayoutComponents/__Snapshots__/HorizontalParticipantsListView_Tests/test_layout_participantsWithoutAudio_withAllInfoAndSmallerSize_viewWasConfiguredCorrectly.default-light.png
  StreamVideoSwiftUITests/CallView/LayoutComponents/__Snapshots__/HorizontalParticipantsListView_Tests/test_layout_participantsWithoutAudio_withAllInfo_viewWasConfiguredCorrectly.default-dark.png
  StreamVideoSwiftUITests/CallView/LayoutComponents/__Snapshots__/HorizontalParticipantsListView_Tests/test_layout_participantsWithoutAudio_withAllInfo_viewWasConfiguredCorrectly.default-light.png
  StreamVideoSwiftUITests/CallView/LayoutComponents/__Snapshots__/HorizontalParticipantsListView_Tests/test_layout_participantsWithoutAudio_withoutAllInfo_viewWasConfiguredCorrectly.default-dark.png
  StreamVideoSwiftUITests/CallView/LayoutComponents/__Snapshots__/HorizontalParticipantsListView_Tests/test_layout_participantsWithoutAudio_withoutAllInfo_viewWasConfiguredCorrectly.default-light.png
  StreamVideoSwiftUITests/CallView/LayoutComponents/__Snapshots__/SpotlightSpeakerView_Tests/test_appearance.default-dark.png
  StreamVideoSwiftUITests/CallView/LayoutComponents/__Snapshots__/SpotlightSpeakerView_Tests/test_appearance.default-light.png
  StreamVideoSwiftUITests/CallView/LayoutComponents/mock-profile-image.jpg
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantWithAudio_snapshot.default-dark-with_1_participants.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantWithAudio_snapshot.default-dark-with_2_participants.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantWithAudio_snapshot.default-dark-with_3_participants.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantWithAudio_snapshot.default-dark-with_4_participants.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantWithAudio_snapshot.default-light-with_1_participants.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantWithAudio_snapshot.default-light-with_2_participants.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantWithAudio_snapshot.default-light-with_3_participants.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantWithAudio_snapshot.default-light-with_4_participants.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantWithoutAudio_snapshot.default-dark-with_1_participants.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantWithoutAudio_snapshot.default-dark-with_2_participants.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantWithoutAudio_snapshot.default-dark-with_3_participants.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantWithoutAudio_snapshot.default-dark-with_4_participants.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantWithoutAudio_snapshot.default-light-with_1_participants.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantWithoutAudio_snapshot.default-light-with_2_participants.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantWithoutAudio_snapshot.default-light-with_3_participants.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantWithoutAudio_snapshot.default-light-with_4_participants.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantsConnectionQuality_snapshot.default-dark-excellent.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantsConnectionQuality_snapshot.default-dark-good.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantsConnectionQuality_snapshot.default-dark-poor.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantsConnectionQuality_snapshot.default-dark-unknown.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantsConnectionQuality_snapshot.default-light-excellent.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantsConnectionQuality_snapshot.default-light-good.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantsConnectionQuality_snapshot.default-light-poor.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantsConnectionQuality_snapshot.default-light-unknown.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantsSpeaking_snapshot.default-dark.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ParticipantsSpotlightLayout_Tests/test_spotlight_participantsSpeaking_snapshot.default-light.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ReconnectionView_Tests/test_reconnectionView_snapshot.default-dark.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ReconnectionView_Tests/test_reconnectionView_snapshot.default-light.png
Labels: bug, enhancement, ✅ QAed
