Repository GetStream/stream-video-swift, pull requests merged in 2024-09, with the labels that each got.

#502 [Workaround]ParticipantCount event backend fix
  Sources/StreamVideo/Controllers/CallController.swift
Labels: bug

#505 [Fix]CallSettings propagation to call
  Sources/StreamVideo/Call.swift
Labels: bug

#506 [CI] Clean up disk space on CI before downloading iOS runtimes
  .github/actions/setup-ios-runtime/action.yml
Labels: CI/CD

#508 [CI] Update git fetch-depth on release
  .github/workflows/release-publish.yml
Labels: CI/CD

#512 Fix/background is removed on reconnection
  Sources/StreamVideo/WebRTC/v2/WebRTCCoordinator.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift
Labels: bug

#510 Add comments and test for SFU components
  Sources/StreamVideo/Models/CallParticipant.swift
  Sources/StreamVideo/Models/ConnectionQuality.swift
  Sources/StreamVideo/Utils/Logger/Logger.swift
  Sources/StreamVideo/Utils/ReflectiveStringConvertible/ReflectiveStringConvertible.swift
  Sources/StreamVideo/WebRTC/PeerConnectionFactory.swift
  Sources/StreamVideo/WebRTC/v2/Extensions/AudioSettings+Convenience.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/Extensions/SignalServer+Subject.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/Protocols/RTCPeerConnectionCoordinatorProviding.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/RTCPeerConnectionCoordinator.swift
  Sources/StreamVideo/WebRTC/v2/SFU/Extensions/Stream_Video_Sfu_Event_SfuEvent.OneOf_EventPayload+Payload.swift
  Sources/StreamVideo/WebRTC/v2/SFU/Protocols/SignalServerEvent.swift
  Sources/StreamVideo/WebRTC/v2/SFU/SFUAdapter.swift
  Sources/StreamVideo/WebRTC/v2/SFU/SFUEventAdapter.swift
  Sources/StreamVideo/WebRTC/v2/SFU/SFUSignalService.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift
  Sources/StreamVideo/WebSockets/Client/WebSocketClient.swift
  Sources/StreamVideo/WebSockets/Events/Event.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoSwiftUITests/Utils/PictureInPicture/StreamPictureInPictureTrackStateAdapterTests.swift
  StreamVideoTests/Mock/MockRTCPeerConnectionCoordinator.swift
  StreamVideoTests/Mock/MockRTCPeerConnectionCoordinatorFactory.swift
  StreamVideoTests/Utilities/Dummy/RTCMediaStreamTrack+dummy.swift
  StreamVideoTests/Utilities/Extensions/Stream_Video_Sfu_Models_ConnectionQuality+Convenience.swift
  StreamVideoTests/Utilities/Extensions/Stream_Video_Sfu_Models_Participant+Convenience.swift
  StreamVideoTests/Utils/StateMachine/CallStateMachine/StreamCallStateMachine_Tests.swift
  StreamVideoTests/WebRTC/SFU/Mocks/MockSFUAdapter.swift
  StreamVideoTests/WebRTC/SFU/Mocks/MockSignalServer.swift
  StreamVideoTests/WebRTC/SFU/Mocks/MockWebSocketClient.swift
  StreamVideoTests/WebRTC/SFU/SFUAdapter_Tests.swift
  StreamVideoTests/WebRTC/SFU/SFUEventAdapter_Tests.swift
  StreamVideoTests/WebRTC/SFUMiddlewareTests.swift
  SwiftUIDemoAppUITests/Pages/CallDetailsPage.swift
  SwiftUIDemoAppUITests/Tests/ReconnectionTests.swift
Labels: enhancement

#517 Disconnect rather than error stage
  Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Connected.swift
  Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Connecting.swift
  Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Disconnected.swift
  Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+FastReconnected.swift
  Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+FastReconnecting.swift
  Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Joined.swift
  Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Joining.swift
  Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Migrated.swift
  Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Migrating.swift
  Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Rejoining.swift
  Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Stage.swift
Labels: bug

#520 Retain camera position after reconnection
  Sources/StreamVideo/WebRTC/v2/PeerConnection/RTCPeerConnectionCoordinator.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCCoordinator.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift
Labels: bug

#525 [Fix]MissingPermission error thrown when connectUser shouldn't be called
  CHANGELOG.md
  DemoApp/Sources/Components/Router.swift
  Sources/StreamVideo/StreamVideo.swift
Labels: bug

#526 Update tests for RTCPeerConnectionCoordinator on handling negotiation/subscriberOffer
  Sources/StreamVideo/WebRTC/v2/PeerConnection/Protocols/StreamRTCPeerConnectionProtocol.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/RTCTemporaryPeerConnection.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/StreamRTCPeerConnection.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoTests/Mock/MockRTCPeerConnection.swift
  StreamVideoTests/WebRTC/SFU/SFUMiddleware_Tests.swift
  StreamVideoTests/WebRTC/v2/PeerConnection/RTCPeerConnectionCoordinator_Tests.swift
Labels: enhancement

#528 [Fix]Pass all available parameters to connect
  Sources/StreamVideo/Call.swift
  Sources/StreamVideo/Controllers/CallController.swift
  Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Connecting.swift
  Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Migrated.swift
  Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Rejoining.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCAuthenticator.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCCoordinator.swift
  StreamVideoTests/Call/Call_Tests.swift
  StreamVideoTests/Mock/CallController_Mock.swift
  StreamVideoTests/Mock/MockCallAuthenticator.swift
  StreamVideoTests/Mock/MockWebRTCAuthenticator.swift
  StreamVideoTests/Mock/MockWebRTCCoordinatorStack.swift
  StreamVideoTests/WebRTC/SFU/SFUEventAdapter_Tests.swift
  StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_CleanUpStageTests.swift
  StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_ConnectingStageTests.swift
  StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_DisconnectedStageTests.swift
  StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_FastReconnectingStageTests.swift
  StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_JoinedStageTests.swift
  StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_JoiningStageTests.swift
  StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_LeavingStageTests.swift
  StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_MigratedStageTests.swift
  StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_MigratingStageTests.swift
  StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_RejoiningStageTests.swift
  StreamVideoTests/WebRTC/v2/StateMachine/WebRTCCoordinator_StateMachineTests.swift
  StreamVideoTests/WebRTC/v2/WebRTCAuthenticator_Tests.swift
  StreamVideoTests/WebRTC/v2/WebRTCCoorindator_Tests.swift
  StreamVideoTests/WebRTC/v2/WebRTCJoinRequestFactory_Tests.swift
  StreamVideoTests/WebRTC/v2/WebRTCStateAdapter_Tests.swift
Labels: bug

#527 [Fix]Migration not working due to event not being received
  Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Migrated.swift
  StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_MigratedStageTests.swift
Labels: bug

#529 Reenable Callcontroller tests
  Sources/StreamVideo/Controllers/CallController.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCCoordinatorProviding.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoTests/Call/Call_Tests.swift
  StreamVideoTests/Controllers/CallController_Tests.swift
  StreamVideoTests/Mock/MockWebRTCCoordinatorFactory.swift
  StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_ConnectingStageTests.swift
  StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_JoinedStageTests.swift
  StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_LeavingStageTests.swift
  StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_MigratingStageTests.swift
  StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_RejoiningStageTests.swift
  StreamVideoTests/WebRTC/v2/WebRTCJoinRequestFactory_Tests.swift
  StreamVideoTests/WebRTC/v2/WebRTCStateAdapter_Tests.swift
Labels: enhancement

#530 [Enhancement]Allow CustomData passing to CallViewModel
  CHANGELOG.md
  Sources/StreamVideoSwiftUI/CallViewModel.swift
Labels: enhancement

#531 Add more tests for ICEAdapter
  StreamVideoTests/Mock/MockRTCPeerConnection.swift
  StreamVideoTests/WebRTC/SFU/SFUEventAdapter_Tests.swift
  StreamVideoTests/WebRTC/v2/PeerConnection/Adapters/ICEAdapter_Tests.swift
Labels: enhancement

#532 Reenable crud tests
  Sources/StreamVideo/Call.swift
  Sources/StreamVideo/Controllers/CallController.swift
  StreamVideoTests/IntegrationTests/CallCRUDTests.swift
  StreamVideoTests/IntegrationTests/IntegrationTest.swift
Labels: enhancement

#534 [Fix]Track orientation issue
  CHANGELOG.md
  Sources/StreamVideo/Utils/DeviceOrientation/StreamDeviceOrientationAdapter.swift
  Sources/StreamVideo/WebRTC/VideoCapturing/StreamVideoCaptureHandler.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoSwiftUITests/CallView/ParticipantsGridLayout_Tests.swift
  StreamVideoTests/Mock/MockRTCVideoCapturerDelegate.swift
  StreamVideoTests/Utilities/Extensions/CVPixelBuffer+Convenience.swift
  StreamVideoTests/WebRTC/VideoCapturing/StreamVideoCaptureHandler_Tests.swift
Labels: bug

#540 [CI] Resolve fastlane git status issue
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: CI/CD

#548 [Fix]Revert reconnection ui-freeze
  Sources/StreamVideo/Controllers/CallController.swift
  Sources/StreamVideo/Models/CallParticipant.swift
  Sources/StreamVideo/WebRTC/v2/Extensions/Foundation/Publisher+TaskSink.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/Adapters/ICEAdapter.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalAudioMediaAdapter.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalVideoMediaAdapter.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/Protocols/StreamRTCPeerConnectionProtocol.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/RTCPeerConnectionCoordinator.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/RTCTemporaryPeerConnection.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/StreamRTCPeerConnection.swift
  Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Joined.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift
  Sources/StreamVideoSwiftUI/CallView/VideoRenderer/VideoRendererView.swift
  StreamVideoTests/Mock/MockRTCPeerConnectionCoordinator.swift
  StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalAudioMediaAdapter_Tests.swift
  StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalVideoMediaAdapter_Tests.swift
  StreamVideoTests/WebRTC/v2/PeerConnection/RTCPeerConnectionCoordinator_Tests.swift
Labels: bug

#554 [Fix]Revert reconnection ui-freeze (#548)
  Sources/StreamVideo/Controllers/CallController.swift
  Sources/StreamVideo/Models/CallParticipant.swift
  Sources/StreamVideo/WebRTC/v2/Extensions/Foundation/Publisher+TaskSink.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/Adapters/ICEAdapter.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalAudioMediaAdapter.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalVideoMediaAdapter.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/Protocols/StreamRTCPeerConnectionProtocol.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/RTCPeerConnectionCoordinator.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/RTCTemporaryPeerConnection.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/StreamRTCPeerConnection.swift
  Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Joined.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift
  Sources/StreamVideoSwiftUI/CallView/VideoRenderer/VideoRendererView.swift
  StreamVideoTests/Mock/MockRTCPeerConnectionCoordinator.swift
  StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalAudioMediaAdapter_Tests.swift
  StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalVideoMediaAdapter_Tests.swift
  StreamVideoTests/WebRTC/v2/PeerConnection/RTCPeerConnectionCoordinator_Tests.swift
Labels: bug

#558 [CI] Improvements
  fastlane/Fastfile
Labels: CI/CD
