Repository GetStream/stream-video-swift, pull requests merged in 2024-10, with the labels that each got.

#561 [Fix]Retry location hint
  Sources/StreamVideo/Utils/LocationFetcher.swift
Labels: bug

#562 [Fix]Participants duplication
  Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift
Labels: bug

#563 [Fix]Capture quality adaptive policy criteria
  Sources/StreamVideo/Utils/ThermalStateObserver.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/MediaAdapters/VideoCapturePolicy/VideoCapturePolicy.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoSwiftUITests/CallView/VideoRenderer_Tests.swift
  StreamVideoTests/Controllers/CallController_Tests.swift
  StreamVideoTests/Mock/MockThermalStateObserver.swift
  StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/VideoCapturePolicy/AdaptiveVideoCapturePolicy_tests.swift
  StreamVideoTests/WebRTC/v2/WebRTCCoorindator_Tests.swift
  StreamVideoTests/WebRTC/v2/WebRTCStateAdapter_Tests.swift
Labels: bug

#568 [CI] Automatically publish release on merge
  .github/workflows/release-publish.yml
  fastlane/Fastfile
Labels: CI/CD

#570 [CI] Bump gem versions
  Gemfile.lock
Labels: CI/CD

#571 [Feature]Manual Quality Selection
  CHANGELOG.md
  DemoApp/Sources/ViewModifiers/MoreControls/DemoManualQualitySelectionButtonView.swift
  DemoApp/Sources/ViewModifiers/MoreControls/DemoMoreControlsViewModifier.swift
  DocumentationTests/DocumentationTests/DocumentationTests.xcodeproj/project.pbxproj
  DocumentationTests/DocumentationTests/DocumentationTests/05-ui-cookbook/21-manual-quality-selection.swift
  DocumentationTests/DocumentationTests/DocumentationTests/GloballyUsedVariables.swift
  Sources/StreamVideo/Call.swift
  Sources/StreamVideo/CallState.swift
  Sources/StreamVideo/Controllers/CallController.swift
  Sources/StreamVideo/Models/CallParticipant.swift
  Sources/StreamVideo/Models/IncomingVideoQualitySettings.swift
  Sources/StreamVideo/Utils/CollectionDelayedUpdateObserver.swift
  Sources/StreamVideo/WebRTC/v2/Extensions/CallParticipant+Convenience.swift
  Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Joined.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCCoordinator.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCJoinRequestFactory.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift
  Sources/StreamVideoSwiftUI/CallView/VideoParticipantsView.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoTests/Call/Call_Tests.swift
  StreamVideoTests/Controllers/CallController_Tests.swift
  StreamVideoTests/Models/CallParticipants_Tests.swift
  StreamVideoTests/Models/IncomingVideoQualitySettings_Tests.swift
  StreamVideoTests/Utils/CollectionDelayedUpdateObserver_Tests.swift
  StreamVideoTests/WebRTC/v2/Extensions/CallParticipant_TrackSubscriptionTests.swift
  StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_JoinedStageTests.swift
  StreamVideoTests/WebRTC/v2/WebRTCCoorindator_Tests.swift
  StreamVideoTests/WebRTC/v2/WebRTCJoinRequestFactory_Tests.swift
  StreamVideoTests/WebRTC/v2/WebRTCStateAdapter_Tests.swift
  docusaurus/docs/iOS/05-ui-cookbook/22-manual-video-quality-selection.mdx
  docusaurus/docs/iOS/assets/manual-video-quality-preview.png
Labels: enhancement

#577 [Feature]Report thermal state to SFU
  Sources/StreamVideo/Models/Extensions/Stream_Video_Sfu_Models_AppleThermalState+Convenience.swift
  Sources/StreamVideo/Utils/Logger/Logger.swift
  Sources/StreamVideo/Utils/ThermalStateObserver.swift
  Sources/StreamVideo/WebRTC/v2/SFU/SFUAdapter.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCStatsReporter.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoTests/WebRTC/SFU/SFUAdapter_Tests.swift
  StreamVideoTests/WebRTC/v2/WebRTCStatsReporter_Tests.swift
Labels: enhancement

#579 [Demo]Improve stats view
  DemoApp/Sources/Components/Router.swift
  DemoApp/Sources/Views/StatsView/DemoStatsAdapter.swift
  DemoApp/Sources/Views/StatsView/DemoStatsView.swift
  StreamVideo.xcodeproj/project.pbxproj
Labels: enhancement

#580 Lock vale version to 2.1.0
  .github/workflows/vale-doc-lint.yml
Labels: documentation, CI/CD

#572 [Fix]Failing iOS 15 tests
  Sources/StreamVideo/Utils/DeviceOrientation/StreamDeviceOrientationAdapter.swift
  Sources/StreamVideo/WebRTC/VideoCapturing/StreamVideoCaptureHandler.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift
  StreamVideoSwiftUITests/CallView/ParticipantsGridLayout_Tests.swift
  StreamVideoTests/Controllers/CallController_Tests.swift
  StreamVideoTests/WebRTC/VideoCapturing/StreamVideoCaptureHandler_Tests.swift
  StreamVideoTests/WebRTC/v2/IntegrationTests/WebRTCIntegrationTests.swift
  StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalAudioMediaAdapter_Tests.swift
  StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalScreenShareMediaAdapter_Tests.swift
  StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalVideoMediaAdapter_Tests.swift
  StreamVideoTests/WebRTC/v2/WebRTCStateAdapter_Tests.swift
Labels: bug, CI/CD

#582 Align docusaurus-related workflows across repos
  .github/workflows/docusaurus-prod.yml
  .github/workflows/docusaurus-staging.yml
  .github/workflows/docusaurus.yml
Labels: documentation, CI/CD

#583 [Feature]VideoCodec preference
  CHANGELOG.md
  DemoApp/Sources/Components/AppEnvironment.swift
  DemoApp/Sources/Views/CallView/CallingView/DemoCallingViewModifier.swift
  DemoApp/Sources/Views/CallView/CallingView/DetailedCallingView.swift
  DemoApp/Sources/Views/CallView/CallingView/SimpleCallingView.swift
  DemoApp/Sources/Views/Login/DebugMenu.swift
  DemoApp/Sources/Views/StatsView/DemoStatsView.swift
  Sources/StreamVideo/Call.swift
  Sources/StreamVideo/Controllers/CallController.swift
  Sources/StreamVideo/Models/CallStatsReport.swift
  Sources/StreamVideo/Models/VideoCodec.swift
  Sources/StreamVideo/Models/VideoLayer.swift
  Sources/StreamVideo/Models/VideoOptions.swift
  Sources/StreamVideo/WebRTC/PeerConnectionFactory.swift
  Sources/StreamVideo/WebRTC/Statistics/StreamCallStatisticsReporter.swift
  Sources/StreamVideo/WebRTC/VideoCapturing/VideoCapturer.swift
  Sources/StreamVideo/WebRTC/VideoCapturing/VideoCapturing.swift
  Sources/StreamVideo/WebRTC/VideoCapturing/VideoCapturingUtils.swift
  Sources/StreamVideo/WebRTC/v2/Extensions/Stream_Video_Sfu_Models_VideoLayer+Convenience.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/Extensions/RTCRtpEncodingParameters+Convenience.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/Extensions/RTCRtpTransceiverInit+Convenience.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalScreenShareMediaAdapter.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalVideoMediaAdapter.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/MediaAdapters/MediaAdapter.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/MediaAdapters/VideoCapturePolicy/VideoCapturePolicy.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/MediaAdapters/VideoMediaAdapter.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/RTCPeerConnectionCoordinator.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/RTCTemporaryPeerConnection.swift
  Sources/StreamVideo/WebRTC/v2/SFU/SFUEventAdapter.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCAuthenticator.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCCoordinator.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCJoinRequestFactory.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoTests/Controllers/CallController_Tests.swift
  StreamVideoTests/Mock/MockCameraVideoCapturer.swift
  StreamVideoTests/Mock/MockRTCPeerConnectionCoordinator.swift
  StreamVideoTests/Utilities/Dummy/CallStatsReport+Dummy.swift
  StreamVideoTests/Utilities/Dummy/Stream_Video_Sfu_Event_VideoLayerSetting+Dummy.swift
  StreamVideoTests/Utilities/Dummy/Stream_Video_Sfu_Models_Codec+Dummy.swift
  StreamVideoTests/WebRTC/SFU/SFUEventAdapter_Tests.swift
  StreamVideoTests/WebRTC/v2/PeerConnection/Extensions/RTCRtpEncodingParameters_Test.swift
  StreamVideoTests/WebRTC/v2/PeerConnection/Extensions/RTCRtpTransceiverInit_Tests.swift
  StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalAudioMediaAdapter_Tests.swift
  StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalScreenShareMediaAdapter_Tests.swift
  StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalVideoMediaAdapter_Tests.swift
  StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/VideoCapturePolicy/AdaptiveVideoCapturePolicy_tests.swift
  StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/VideoCapturePolicy/VideoCapturePolicy_Tests.swift
  StreamVideoTests/WebRTC/v2/WebRTCAuthenticator_Tests.swift
  StreamVideoTests/WebRTC/v2/WebRTCCoorindator_Tests.swift
  StreamVideoTests/WebRTC/v2/WebRTCJoinRequestFactory_Tests.swift
  StreamVideoTests/WebRTC/v2/WebRTCStateAdapter_Tests.swift
Labels: enhancement

#586 [Fix]SetPublisher track setUp race condition
  CHANGELOG.md
  Sources/StreamVideo/CallKit/CallKitService.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/RTCPeerConnectionCoordinator.swift
  Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Joining.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCConfiguration.swift
  StreamVideoTests/Mock/MockRTCPeerConnectionCoordinator.swift
  StreamVideoTests/WebRTC/v2/IntegrationTests/WebRTCIntegrationTests.swift
  StreamVideoTests/WebRTC/v2/PeerConnection/RTCPeerConnectionCoordinator_Tests.swift
  StreamVideoTests/WebRTC/v2/WebRTCConfiguration_Tests.swift
Labels: bug

#587 [Fix]Empty session ids during livestream
  Sources/StreamVideo/WebRTC/v2/SFU/SFUAdapter.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift
  StreamVideoTests/WebRTC/v2/WebRTCStateAdapter_Tests.swift
Labels: bug
