Repository GetStream/stream-video-swift, pull requests merged in 2024-08, with the labels that each got.

#478 [CI] Automate the merge of the release branches
  .github/workflows/release-merge.yml
  .github/workflows/release-publish.yml
  .github/workflows/release-start.yml
  fastlane/Fastfile
Labels: CI/CD

#482 [CI] Update gems
  Gemfile.lock
Labels: CI/CD

#487 [CI] Share fastlane lanes across platforms
  .github/workflows/cron-checks.yml
  .gitignore
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: CI/CD

#485 [CI] Measure the size of StreamWebRTC
  README.md
  fastlane/Fastfile
Labels: CI/CD

#492 [CI] Update publish release flow
  .github/workflows/release-publish.yml
  fastlane/Fastfile
Labels: CI/CD

#491 Enhancement/custom call settings when joining from callkit
  DocumentationTests/DocumentationTests/DocumentationTests/06-advanced/03-callkit-integration.swift
  Sources/StreamVideo/CallKit/CallKitAdapter.swift
  Sources/StreamVideo/CallKit/CallKitService.swift
  StreamVideoTests/CallKit/CallKitAdapterTests.swift
  StreamVideoTests/CallKit/CallKitServiceTests.swift
  StreamVideoTests/Controllers/CallsController_Tests.swift
  StreamVideoTests/Mock/MockCall.swift
  StreamVideoTests/StreamVideoTestCase.swift
  docusaurus/docs/iOS/06-advanced/03-callkit-integration.mdx
Labels: enhancement

#496 [Enhancement]Handle participantsCount event
  CHANGELOG.md
  Sources/StreamVideo/CallState.swift
  Sources/StreamVideo/Controllers/CallController.swift
  Sources/StreamVideo/WebRTC/SfuMiddleware.swift
  Sources/StreamVideo/WebRTC/WebRTCClient.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoTests/WebRTC/SFUMiddlewareTests.swift
Labels: enhancement

#497 [Fix]Allow callSettings propagation to CallState
  CHANGELOG.md
  Sources/StreamVideo/Call.swift
  Sources/StreamVideo/StreamVideo.swift
  Sources/StreamVideoSwiftUI/CallViewModel.swift
  StreamVideoTests/Mock/MockStreamVideo.swift
Labels: bug

#500 [CI] Do not cache iOS Simulator Runtimes nightly
  .github/actions/setup-ios-runtime/action.yml
Labels: CI/CD
