Repository GetStream/stream-video-swift, pull requests merged in 2024-06, with the labels that each got.

#426 Fix TestOps API request failure
  Gemfile.lock
  fastlane/Allurefile
  fastlane/Pluginfile
Labels: CI/CD

#423 Update release flow to be able to start the release from CI
  .github/actions/bootstrap/action.yml
  .github/actions/xcode-cache/action.yml
  .github/workflows/cron-checks.yml
  .github/workflows/smoke-checks.yml
  .github/workflows/start-new-release.yml
  Gemfile.lock
Labels: CI/CD

#430 [CI] Resolve Allure issue
  Gemfile.lock
  fastlane/Pluginfile
Labels: CI/CD

#431 [Fix]Async CallViewModel tests
  Sources/StreamVideoSwiftUI/CallViewModel.swift
  StreamVideoSwiftUITests/CallViewModel_Tests.swift
  StreamVideoTests/StreamVideoTestCase.swift
  StreamVideoTests/Utilities/Extensions/XCTestCase+PredicateFulfillment.swift
Labels: enhancement

#417 [Enhancement]Minor improvements
  Sources/StreamVideo/OpenApi/URLSessionTransport.swift
  Sources/StreamVideo/Utils/UUIDProviding/StreamUUIDFactory.swift
  Sources/StreamVideo/WebRTC/WebRTCClient.swift
  Sources/StreamVideo/WebSockets/Client/WebSocketClient.swift
  Sources/StreamVideo/WebSockets/Events/Event.swift
  Sources/StreamVideo/WebSockets/Events/EventNotificationCenter.swift
Labels: enhancement

#422 [Debug] Fix add new user and customise the environment
  DemoApp/Sources/Components/AppEnvironment.swift
  DemoApp/Sources/Components/AppState.swift
  DemoApp/Sources/Components/Authentication/AuthenticationProvider.swift
  DemoApp/Sources/Components/Router.swift
  DemoApp/Sources/Components/Storage/UnsecureRepository.swift
  DemoApp/Sources/Extensions/User+Demo.swift
  DemoApp/Sources/Extensions/View+AlertWithTextField.swift
  DemoApp/Sources/Views/Login/AddUserView.swift
  DemoApp/Sources/Views/Login/DebugMenu.swift
  DemoApp/Sources/Views/Login/LoginView.swift
  DemoApp/Sources/Views/Login/LoginViewModel.swift
  Sources/StreamVideo/Models/PushNotificationsConfig.swift
  StreamVideo.xcodeproj/project.pbxproj
Labels: enhancement

#433 [Fix]Cancel ringing timer when call is answered elsewhere
  Sources/StreamVideo/CallKit/CallKitService.swift
Labels: bug

#434 [Enhancement]Participant auto-leave policy implementation
  CHANGELOG.md
  DemoApp/Sources/Components/AppEnvironment.swift
  DemoApp/Sources/Views/CallView/DemoCallContainerView.swift
  DemoApp/Sources/Views/Login/DebugMenu.swift
  DocumentationTests/DocumentationTests/DocumentationTests/06-advanced/00-ringing.swift
  Sources/StreamVideo/Utils/ParticipantAutoLeavePolicy/DefaultParticipantAutoLeavePolicy.swift
  Sources/StreamVideo/Utils/ParticipantAutoLeavePolicy/LastParticipantAutoLeavePolicy.swift
  Sources/StreamVideo/Utils/ParticipantAutoLeavePolicy/ParticipantAutoLeavePolicy.swift
  Sources/StreamVideo/Utils/Publisher+WeakAssign.swift
  Sources/StreamVideoSwiftUI/CallViewModel.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoTests/Utilities/Extensions/XCTestCase+PredicateFulfillment.swift
  StreamVideoTests/Utils/ParticipantAutoLeavePolicy/LastParticipantAutoLeavePolicyTests.swift
  StreamVideoTests/Utils/StateMachine/CallStateMachine/Stages/StreamCallStateMachineStageAcceptedStage_Tests.swift
  StreamVideoTests/Utils/StateMachine/CallStateMachine/Stages/StreamCallStateMachineStageAcceptingStage_Tests.swift
  StreamVideoTests/Utils/StateMachine/CallStateMachine/Stages/StreamCallStateMachineStageErrorStage_Tests.swift
  StreamVideoTests/Utils/StateMachine/CallStateMachine/Stages/StreamCallStateMachineStageIdleStage_Tests.swift
  StreamVideoTests/Utils/StateMachine/CallStateMachine/Stages/StreamCallStateMachineStageJoinedStage_Tests.swift
  StreamVideoTests/Utils/StateMachine/CallStateMachine/Stages/StreamCallStateMachineStageJoiningStage_Tests.swift
  StreamVideoTests/Utils/StateMachine/CallStateMachine/Stages/StreamCallStateMachineStageRejectedStage_Tests.swift
  StreamVideoTests/Utils/StateMachine/CallStateMachine/Stages/StreamCallStateMachineStageRejectingStage_Tests.swift
  docusaurus/docs/iOS/06-advanced/00-ringing.mdx
Labels: enhancement, ✅ QAed

#435 [Fix]Demo share link format
  DemoApp/Sources/Components/AppEnvironment.swift
  DemoApp/Sources/Views/WaitingLocalUserView/DemoWaitingLocalUserView.swift
  StreamVideo.xcodeproj/project.pbxproj
Labels: bug

#440 [Fix]Flakey tests
  Sources/StreamVideo/StreamVideo.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamPictureInPictureTrackStateAdapter.swift
  StreamVideoSwiftUITests/CallViewModel_Tests.swift
  StreamVideoSwiftUITests/Utils/PictureInPicture/StreamPictureInPictureTrackStateAdapterTests.swift
  StreamVideoTests/StreamVideoTestCase.swift
  StreamVideoTests/Utilities/Extensions/XCTestCase+PredicateFulfillment.swift
Labels: bug

#443 [Fix]Disappearing tracks due to lack of capability
  Sources/StreamVideo/Call.swift
  Sources/StreamVideo/CallState.swift
  Sources/StreamVideo/Controllers/CallController.swift
  Sources/StreamVideo/WebRTC/WebRTCClient.swift
Labels: bug

#444 [CI] Make CI great again
  .github/workflows/cron-checks.yml
  .github/workflows/smoke-checks.yml
  Scripts/bootstrap.sh
  fastlane/Fastfile
Labels: 🔧 WIP, CI/CD

#445 Introducing develop branch
  .github/workflows/publish-release.yml
  fastlane/Fastfile
Labels: CI/CD

#447 [Fix]Flakey tests on LLC and SwiftUI
  Sources/StreamVideo/Call.swift
  Sources/StreamVideo/CallKit/CallKitService.swift
  Sources/StreamVideo/Controllers/CallsController.swift
  Sources/StreamVideo/StreamVideo.swift
  Sources/StreamVideo/Utils/AudioRecorder/StreamCallAudioRecorder.swift
  Sources/StreamVideo/Utils/DisposableBag/DisposableBag.swift
  Sources/StreamVideo/WebRTC/AudioFilter/Filters/NoiseCancellationFilter.swift
  Sources/StreamVideo/WebRTC/AudioSession.swift
  Sources/StreamVideo/WebRTC/PeerConnectionFactory.swift
  Sources/StreamVideo/WebRTC/WebRTCClient.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamPictureInPictureTrackStateAdapter.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideo.xcodeproj/xcshareddata/xcschemes/StreamVideoSwiftUI.xcscheme
  StreamVideoSwiftUITests/Utils/PictureInPicture/StreamPictureInPictureTrackStateAdapterTests.swift
  StreamVideoTests/IntegrationTests/CallCRUDTests.swift
  StreamVideoTests/StreamVideo_Tests.swift
  StreamVideoTests/WebRTC/WebRTCClient_Tests.swift
Labels: bug, CI/CD

#442 [Logs]Improving logs
  DemoApp/Sources/Components/MemoryLogDestination/OSLogDestination.swift
  DemoApp/Sources/Components/Snapshot/LocalParticipantSnapshotViewModel.swift
  DemoApp/Sources/Extensions/DemoApp+Sentry.swift
  Sources/StreamVideo/Utils/AudioRecorder/StreamCallAudioRecorder.swift
  Sources/StreamVideo/Utils/Logger/Destination/LogDestination.swift
  Sources/StreamVideo/Utils/Logger/Logger.swift
  Sources/StreamVideo/WebRTC/PeerConnection.swift
  Sources/StreamVideo/WebRTC/SfuMiddleware.swift
  Sources/StreamVideo/WebRTC/VideoCapturingUtils.swift
  Sources/StreamVideoSwiftUI/CallView/ViewModifiers/CallEndedViewModifier.swift
Labels: enhancement

#448 [Fix]Project warnings
  Sources/StreamVideo/WebRTC/WebRTCClient.swift
Labels: enhancement

#450 [Fix]Reactions not showing after logging out and back in
  DemoApp/Sources/Components/Reactions/ReactionsAdapter.swift
  DemoApp/Sources/Components/Router.swift
Labels: bug

#436 [Enhancement]Error handling inside SwiftConcurrency tasks
  .swiftlint.yml
  DemoApp/Sources/AppDelegate.swift
  DemoApp/Sources/Components/Reactions/ReactionsAdapter.swift
  DemoApp/Sources/Components/Router.swift
  DemoApp/Sources/Components/Snapshot/LocalParticipantSnapshotViewModel.swift
  DemoApp/Sources/DemoApp.swift
  DemoApp/Sources/Views/CallTopView/DemoCallTopView.swift
  DemoApp/Sources/Views/CallView/CallingView/DemoCallingViewModifier.swift
  DemoApp/Sources/Views/CallView/DemoCallsViewModel.swift
  DemoApp/Sources/Views/CallsView/CallsViewModel.swift
  DemoApp/Sources/Views/Login/LoginViewModel.swift
  DemoAppUIKit/SceneDelegate.swift
  Mintfile
  Sources/StreamVideo/Controllers/CallController.swift
  Sources/StreamVideo/Controllers/CallsController.swift
  Sources/StreamVideo/StreamVideo.swift
  Sources/StreamVideo/WebRTC/PeerConnection.swift
  Sources/StreamVideo/WebRTC/SfuMiddleware.swift
  Sources/StreamVideo/WebRTC/StreamVideoCaptureHandler.swift
  Sources/StreamVideo/WebRTC/WebRTCClient.swift
  Sources/StreamVideoSwiftUI/CallView/ParticipantPopoverView.swift
  Sources/StreamVideoSwiftUI/CallView/Participants/CallParticipantsInfoViewModel.swift
  Sources/StreamVideoSwiftUI/CallView/Participants/InviteParticipantsViewModel.swift
  Sources/StreamVideoSwiftUI/CallView/VideoParticipantsView.swift
  Sources/StreamVideoSwiftUI/CallViewModel.swift
  Sources/StreamVideoSwiftUI/CallingViews/PreJoiningViewModel.swift
  Sources/StreamVideoSwiftUI/Livestreaming/LivestreamPlayerViewModel.swift
  fastlane/Fastfile
Labels: enhancement

#452 Merge main to develop as part of automated release pipeline
  fastlane/Fastfile
Labels: CI/CD
