Repository GetStream/stream-video-swift, pull requests merged in 2024-01, with the labels that each got.

#262 Fix memory leaks on Utils and UserState
  DemoApp/Sources/Components/Router.swift
  DemoApp/Sources/DemoApp.swift
  Sources/StreamVideoSwiftUI/StreamVideoUI.swift
  Sources/StreamVideoSwiftUI/Utils.swift
Labels: bug

#260 Disable broadcast button on simulators
  DemoApp/Sources/Views/Controls/DemoControls.swift
Labels: enhancement

#263 [Fix]Only reuse VideoRenderers when they are actually presented
  Sources/StreamVideoSwiftUI/CallView/VideoParticipantsView.swift
Labels: bug

#258 Picture in Picture improvements
  Sources/StreamVideoSwiftUI/CallView/CallView.swift
  Sources/StreamVideoSwiftUI/CallView/VideoRenderer.swift
  Sources/StreamVideoSwiftUI/CallView/VideoRendererFactory.swift
  Sources/StreamVideoSwiftUI/CallViewModel.swift
  Sources/StreamVideoSwiftUI/Utils.swift
  Sources/StreamVideoSwiftUI/Utils/PiPHandler.swift
  Sources/StreamVideoSwiftUI/Utils/PiPTrackSelectionUtils.swift
  Sources/StreamVideoSwiftUI/Utils/PiPUtils.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamAVPictureInPictureVideoCallViewController.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamBufferTransformer.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamPictureInPIctureView.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamPictureInPictureAdapter.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamPictureInPictureController.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamPictureInPictureTrackStateAdapter.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamPictureInPictureVideoRenderer.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoSwiftUITests/Utils/PiPTrackSelectionUtils_Tests.swift
  StreamVideoSwiftUITests/Utils/PiPUtils_Tests.swift
  StreamVideoSwiftUITests/Utils/PictureInPicture/StreamBufferTransformerTests.swift
  StreamVideoSwiftUITests/Utils/PictureInPicture/StreamPictureInPictureTrackStateAdapterTests.swift
  StreamVideoSwiftUITests/Utils/PictureInPicture/__Snapshots__/StreamBufferTransformerTests/testTransformPixelBuffer.1.png
  docusaurus/docs/iOS/06-advanced/05-picture-in-picture.mdx
Labels: enhancement

#264 [Integration]Add toggle for picture in picture
  DemoApp/Sources/Components/AppEnvironment.swift
  DemoApp/Sources/Views/CallView/DemoCallContainerView.swift
  DemoApp/Sources/Views/Login/DebugMenu.swift
Labels: enhancement

#268 Delete unused job on CI
  .github/workflows/emerge.yml
  Gemfile.lock
  docusaurus/docs/iOS/06-advanced/15-sdk-size-impact.mdx
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: CI/CD

#272 Gemfile refactoring
  Gemfile
  Gemfile.lock
  TestTools/Robots/Sinatra.swift
Labels: CI/CD

#276 Add clientDetails on JoinRequest
  Sources/StreamVideo/Utils/SystemEnvironment+XStreamClient.swift
  Sources/StreamVideo/WebRTC/WebRTCClient.swift
Labels: enhancement

#277 Implement docs testing pipeline
  .github/workflows/cron-checks.yml
  .github/workflows/smoke-checks.yml
  DocumentationTests/DocumentationTests/DocumentationTests.xcodeproj/project.pbxproj
  DocumentationTests/DocumentationTests/DocumentationTests.xcodeproj/xcshareddata/xcschemes/DocumentationTests.xcscheme
  Package.swift
  fastlane/.rubocop.yml
  fastlane/Fastfile
Labels: CI/CD
