Repository GetStream/stream-video-swift, pull requests merged in 2024-03, with the labels that each got.

#312 [CI/CD]Update testflight lane
  .github/workflows/testflight.yml
  StreamVideo.xcodeproj/project.pbxproj
  fastlane/Fastfile
Labels: CI/CD

#314 Updated the WS reconnection logic
  CHANGELOG.md
  DemoApp/Sources/Components/Chat/DemoChatAdapter.swift
  Sources/StreamVideo/StreamVideo.swift
  StreamVideoSwiftUITests/StreamVideoUITestCase.swift
  StreamVideoTests/Controllers/CallsController_Tests.swift
  StreamVideoTests/StreamVideoTestCase.swift
Labels: ✅ QAed

#316 [Fix]Universal link tests
  SwiftUIDemoAppUITests/Tests/DeeplinkTests.swift
Labels: bug

#317 [Fix]Picture-in-Picture memory consumption
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamBufferTransformer.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamPictureInPictureController.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamPictureInPictureVideoRenderer.swift
  StreamVideoSwiftUITests/Utils/PictureInPicture/StreamBufferTransformerTests.swift
Labels: bug

#319 Fix compile error on Xcode 14
  Sources/StreamVideoSwiftUI/CallView/SampleBufferVideoCallView.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamPictureInPictureVideoRenderer.swift
  SwiftUIDemoAppUITests/Tests/DeeplinkTests.swift
Labels: bug, CI/CD

#320 [Fix]Local video rotate on YAxis when turning off video
  Sources/StreamVideo/WebRTC/StreamVideoCaptureHandler.swift
  Sources/StreamVideoSwiftUI/CallView/VideoRenderer.swift
Labels: bug

#323 [Docs]Update VoIP certificate creation
  docusaurus/docs/iOS/06-advanced/03-callkit-integration.mdx
  docusaurus/docs/iOS/assets/callkit_02.png
Labels: documentation

#324 Rotate local user feed on all layouts
  Sources/StreamVideoSwiftUI/CallView/VideoParticipantsView.swift
  Sources/StreamVideoSwiftUI/CallView/VideoRenderer.swift
Labels: bug

#321 [Improvement] Use accelerate for frame processing during pip
  Sources/StreamVideoSwiftUI/Utils/Extensions/CVPixelBuffer+Convenience.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamBufferTransformer.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamPictureInPictureVideoRenderer.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamRTCYUVBuffer.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamYUVToARGBConversion.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/YpCbCrPixelRange+Default.swift
  Sources/StreamVideoSwiftUI/Utils/StreamPixelBufferRepository/StreamPixelBufferPool.swift
  Sources/StreamVideoSwiftUI/Utils/StreamPixelBufferRepository/StreamPixelBufferRepository.swift
  Sources/StreamVideoSwiftUI/Utils/UnfairQueue/UnfairQueue.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoSwiftUITests/Utils/PictureInPicture/StreamBufferTransformerTests.swift
  SwiftUIDemoAppUITests/Tests/DeeplinkTests.swift
Labels: enhancement

#329 [UIKit]Fix view positioning
  Sources/StreamVideoUIKit/CallViewController.swift
Labels: bug, uikit

#331 [Fix]Xcode 15.3 warnings
  DemoApp/Sources/Components/Chat/DemoChatAdapter.swift
  DemoApp/Sources/Views/Login/DebugMenu.swift
  Sources/StreamVideo/Controllers/CallController.swift
  Sources/StreamVideo/Controllers/CallsController.swift
  Sources/StreamVideo/StreamVideo.swift
  Sources/StreamVideoSwiftUI/CallContainer.swift
  Sources/StreamVideoSwiftUI/CallView/Participants/UserListProvider.swift
  Sources/StreamVideoSwiftUI/CallView/ScreenSharing/ScreenSharingView.swift
  Sources/StreamVideoSwiftUI/StreamNuke/Nuke/Decoding/ImageDecoders+Default.swift
  Sources/StreamVideoSwiftUI/StreamNuke/Nuke/Internal/Graphics.swift
  Sources/StreamVideoSwiftUI/StreamNuke/Nuke/Processing/ImageProcessingOptions.swift
  Sources/StreamVideoSwiftUI/StreamNuke/Nuke/Processing/ImageProcessors+Resize.swift
  Sources/StreamVideoSwiftUI/StreamNuke/Nuke/Processing/ImageProcessors+RoundedCorners.swift
  Sources/StreamVideoSwiftUI/StreamNuke/Nuke/Processing/ImageProcessors.swift
  Sources/StreamVideoSwiftUI/StreamNuke/NukeUI/NukeVideoPlayerView.swift
  Sources/StreamVideoSwiftUI/ViewFactory.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideo.xcodeproj/xcshareddata/xcschemes/DemoApp.xcscheme
  StreamVideo.xcodeproj/xcshareddata/xcschemes/DemoAppUIKit.xcscheme
  StreamVideo.xcodeproj/xcshareddata/xcschemes/StreamVideo.xcscheme
  StreamVideo.xcodeproj/xcshareddata/xcschemes/StreamVideoSwiftUI.xcscheme
  StreamVideo.xcodeproj/xcshareddata/xcschemes/StreamVideoUIKit.xcscheme
Labels: bug

#333 [Fix]Stop recording when error occurs on join
  Sources/StreamVideoSwiftUI/CallViewModel.swift
Labels: bug

#336 [Fix]Handle VoIP notifications for ended calls
  CHANGELOG.md
  DemoApp/Sources/Components/Services/CallKitService.swift
  DemoApp/Sources/Components/Services/CallService.swift
Labels: bug

#337 [Fix]Long usernames on various places
  Sources/StreamVideo/StreamVideo.swift
Labels: bug
