Repository GetStream/stream-video-swift, pull requests merged in 2024-07, with the labels that each got.

#453 [CI] Update iOS runtimes' download
  .github/actions/setup-ios-runtime/action.yml
  .github/workflows/cron-checks.yml
  .github/workflows/smoke-checks.yml
  .gitignore
  Scripts/bootstrap.sh
  Scripts/install_ios_runtime.sh
  fastlane/.env
  fastlane/Fastfile
Labels: CI/CD

#449 [Enhancement]Provide call rejection reason
  CHANGELOG.md
  DemoApp/Sources/Examples/Examples.swift
  DocumentationTests/DocumentationTests/DocumentationTests/05-ui-cookbook/05-incoming-call.swift
  Sources/StreamVideo/CallKit/CallKitService.swift
  Sources/StreamVideo/Models/Extensions/RejectCallRequest+Reason.swift
  Sources/StreamVideo/StreamVideo.swift
  Sources/StreamVideo/Utils/RejectionReasonProvider/RejectionReasonProvider.swift
  Sources/StreamVideoSwiftUI/CallViewModel.swift
  Sources/StreamVideoSwiftUI/CallingViews/IncomingCallView.swift
  Sources/StreamVideoSwiftUI/CallingViews/IncomingCallViewModel.swift
  Sources/StreamVideoSwiftUI/CallingViews/iOS13/IncomingCallView_iOS13.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoTests/Mock/MockCall.swift
  StreamVideoTests/Mock/MockStreamVideo.swift
  StreamVideoTests/Utils/RejectionReasonProvider/RejectionReasonProvider_Tests.swift
  docusaurus/docs/iOS/05-ui-cookbook/05-incoming-call.mdx
Labels: enhancement

#455 Fix e2e test issues on CI
  .github/workflows/cron-checks.yml
  SwiftUIDemoAppUITests/Tests/StreamTestCase.swift
Labels: CI/CD

#454 [Fix]DefaultRetryStrategy on first try
  Sources/StreamVideo/WebSockets/Client/RetryStrategy.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoTests/WebSocketClient/RetryStrategy_Tests.swift
  StreamVideoTests/WebSockets/Client/DefaultRetryStrategyTests.swift
Labels: bug

#457 [CI] Do not fail jobs on unsuccessful removal of temp folders
  Scripts/install_ios_runtime.sh
Labels: CI/CD

#458 [CI] Lint pod on release and nighty only
  .github/workflows/smoke-checks.yml
Labels: CI/CD

#461 [Fix]Spacing between horizontal participants in gridLayout
  Sources/StreamVideoSwiftUI/CallView/ParticipantsGridLayout.swift
Labels: bug

#463 Remove StreamVideo module's shadow at xcframeworks' swiftinterfaces
  fastlane/Fastfile
Labels: CI/CD

#460 [Feature]Allow PiP window to resize based on rendering track size
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamAVPictureInPictureVideoCallViewController.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamBufferTransformer.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamPictureInPictureController.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamPictureInPictureVideoRenderer.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/WindowSizePolicy/StreamPictureInPictureAdaptiveWindowSizePolicy.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/WindowSizePolicy/StreamPictureInPictureFixedWindowSizePolicy.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/WindowSizePolicy/StreamPictureInPictureWindowSizePolicy.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoSwiftUITests/CallView/CallControls/Stateful/CallControlsView_Tests.swift
  StreamVideoSwiftUITests/CallView/CallControls/Stateless/StatelessAudioOutputIconView_Tests.swift
  StreamVideoSwiftUITests/CallView/CallControls/Stateless/StatelessHangUpIconView_Tests.swift
  StreamVideoSwiftUITests/CallView/CallControls/Stateless/StatelessMicrophoneIconView_Tests.swift
  StreamVideoSwiftUITests/CallView/CallControls/Stateless/StatelessParticipantsListButton_Tests.swift
  StreamVideoSwiftUITests/CallView/CallControls/Stateless/StatelessSpeakerIconView_Tests.swift
  StreamVideoSwiftUITests/CallView/CallControls/Stateless/StatelessToggleCameraIconView_Tests.swift
  StreamVideoSwiftUITests/CallView/CallControls/Stateless/StatelessVideoIconView_Tests.swift
  StreamVideoSwiftUITests/CallView/CallDurationView_Tests.swift
  StreamVideoSwiftUITests/CallView/ControlBadgeView_Tests.swift
  StreamVideoSwiftUITests/CallView/LayoutComponents/HorizontalParticipantsListView_Tests.swift
  StreamVideoSwiftUITests/CallView/LayoutComponents/SpotlightSpeakerView_Tests.swift
  StreamVideoSwiftUITests/CallView/ParticipantListButton_Tests.swift
  StreamVideoSwiftUITests/CallView/ParticipantsFullScreenLayout_Tests.swift
  StreamVideoSwiftUITests/CallView/ParticipantsGridLayout_Tests.swift
  StreamVideoSwiftUITests/CallView/ParticipantsSpotlightLayout_Tests.swift
  StreamVideoSwiftUITests/CallView/ReconnectionView_Tests.swift
  StreamVideoSwiftUITests/CallView/RecordingView_Tests.swift
  StreamVideoSwiftUITests/CallView/ScreenSharingView_Tests.swift
  StreamVideoSwiftUITests/CallView/VideoRenderer_Tests.swift
  StreamVideoSwiftUITests/CallView/VisibilityThresholdModifier_Tests.swift
  StreamVideoSwiftUITests/CallViewModel_Tests.swift
  StreamVideoSwiftUITests/CallingViews/CallConnectingView_Tests.swift
  StreamVideoSwiftUITests/CallingViews/CallingGroupView_Tests.swift
  StreamVideoSwiftUITests/CallingViews/CallingParticipantView_Tests.swift
  StreamVideoSwiftUITests/CallingViews/IncomingCallView_Tests.swift
  StreamVideoSwiftUITests/CallingViews/JoiningCallView_Tests.swift
  StreamVideoSwiftUITests/CallingViews/LobbyView_Tests.swift
  StreamVideoSwiftUITests/CallingViews/MicrophoneCheckView_Tests.swift
  StreamVideoSwiftUITests/CallingViews/MicrophoneChecker_Tests.swift
  StreamVideoSwiftUITests/CallingViews/OutgoingCallView_Tests.swift
  StreamVideoSwiftUITests/Livestreaming/LivestreamPlayer_Tests.swift
  StreamVideoSwiftUITests/StreamVideoUITestCase.swift
  StreamVideoSwiftUITests/Utils/AudioValuePercentageNormaliser_Tests.swift
  StreamVideoSwiftUITests/Utils/CallEventsHandler_Tests.swift
  StreamVideoSwiftUITests/Utils/CornerClipper_Tests.swift
  StreamVideoSwiftUITests/Utils/PictureInPicture/Mocks/MockStreamAVPictureInPictureViewControlling.swift
  StreamVideoSwiftUITests/Utils/PictureInPicture/StreamBufferTransformerTests.swift
  StreamVideoSwiftUITests/Utils/PictureInPicture/StreamPictureInPictureTrackStateAdapterTests.swift
  StreamVideoSwiftUITests/Utils/PictureInPicture/StreamPictureInPictureVideoRendererTests.swift
  StreamVideoSwiftUITests/Utils/PictureInPicture/WindowSizePolicy/StreamPictureInPictureAdaptiveWindowSizePolicy_Tests.swift
  StreamVideoSwiftUITests/Utils/PictureInPicture/WindowSizePolicy/StreamPictureInPictureFixedWindowSizePolicy_Tests.swift
  StreamVideoSwiftUITests/Utils/ReusePool_Tests.swift
  StreamVideoSwiftUITests/Utils/StreamMediaDurationFormatter_Tests.swift
  StreamVideoSwiftUITests/Utils/ToastView_Tests.swift
  fastlane/Fastfile
Labels: enhancement

#464 Update xcframeworks installation docs
  docusaurus/docs/iOS/01-basics/02-installation.mdx
Labels: CI/CD

#462 Fix/stretchy track
  Sources/StreamVideoSwiftUI/CallView/VideoRenderer/LocalVideoView.swift
  Sources/StreamVideoSwiftUI/CallView/VideoRenderer/VideoRenderer.swift
  Sources/StreamVideoSwiftUI/CallView/VideoRenderer/VideoRendererView.swift
  StreamVideo.xcodeproj/project.pbxproj
Labels: bug

#465 [Fix]Screensharing track disappearing when shared second time
  Sources/StreamVideo/CallState.swift
Labels: bug

#467 [CI] Update some release-related git commands
  fastlane/Fastfile
Labels: CI/CD

#468 [Fix]Debug menu call expiration not working as expected
  DemoApp/Sources/Views/Login/DebugMenu.swift
Labels: bug

#469 Resolve StreamVideo.xcframework cocoapods-related paths
  StreamVideo-XCFramework.podspec
Labels: CI/CD

#470 [CI] Update git fetch-depth on release
  .github/workflows/publish-release.yml
Labels: CI/CD

#472 [CI] Comment SDK size on every commit
  .github/workflows/sdk-size-metrics.yml
  .github/workflows/smoke-checks.yml
  .gitignore
  fastlane/Fastfile
  fastlane/sdk_size_export_options.plist
Labels: CI/CD

#473 [CI] Automatically update SDK size badges in README.md
  README.md
  fastlane/Fastfile
Labels: CI/CD

#476 [Fix]Recording state when failed
  Sources/StreamVideo/CallState.swift
Labels: bug

#477 [CI] Correctly retrieve a git branch on CI
  .github/workflows/cron-checks.yml
  .github/workflows/publish-release.yml
  .github/workflows/sdk-size-metrics.yml
  .github/workflows/smoke-checks.yml
  .github/workflows/start-new-release.yml
  .github/workflows/testflight.yml
  fastlane/Allurefile
  fastlane/Fastfile
Labels: CI/CD
