Repository GetStream/stream-video-swift, pull requests merged in 2024-11, with the labels that each got.

#590 [Enhancement]CallKit handling mute
  CHANGELOG.md
  Sources/StreamVideo/CallKit/CallKitService.swift
  Sources/StreamVideoSwiftUI/Utils/ToastView.swift
  StreamVideoTests/CallKit/CallKitServiceTests.swift
Labels: enhancement

#588 [Improvement]Locking mechanisms and Atomic property wrapper
  Sources/StreamVideo/Utils/Atomic.swift
  Sources/StreamVideo/Utils/Queues/LockQueuing.swift
  Sources/StreamVideo/Utils/Queues/RecursiveQueue.swift
  Sources/StreamVideo/Utils/Queues/UnfairQueue.swift
  Sources/StreamVideo/WebSockets/Client/RetryStrategy.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoTests/Utils/Queues/RecursiveQueueTests.swift
  StreamVideoTests/Utils/Queues/UnfairQueueTests.swift
  StreamVideoTests/WebSockets/Client/DefaultRetryStrategyTests.swift
Labels: enhancement

#594 [Fix]Compiler warning on StreamVideo
  Sources/StreamVideo/StreamVideo.swift
Labels: enhancement

#596 [Fix]Frame scaled to fill without respecting content mode
  CHANGELOG.md
  Sources/StreamVideoSwiftUI/Utils/ReusePool.swift
  Sources/StreamVideoSwiftUI/Utils/VideoRendererPool/VideoRendererPool.swift
  StreamVideoSwiftUITests/Utils/ReusePool_Tests.swift
Labels: bug

#598 Fix/failing test current route returns correct route
  StreamVideoTests/Utils/AudioSession/StreamRTCAudioSession_Tests.swift
Labels: CI/CD

#601 [Fix]Demo stats formula for publishing bitrate
  DemoApp/Sources/Views/StatsView/DemoStatsView.swift
  Sources/StreamVideo/CallState.swift
Labels: bug

#603 [CI] Add snapshot version postfix
  Gemfile.lock
  Sources/StreamVideo/Generated/SystemEnvironment+Version.swift
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: CI/CD

#604 [CI] Add reminder about last release step
  .github/workflows/release-publish.yml
Labels: CI/CD

#584 [PBE-0] support livestream
  DemoApp/Sources/Components/AppEnvironment.swift
  DemoApp/Sources/DemoApp.swift
  DemoApp/Sources/ViewModifiers/CallModifier/DemoCallModifier.swift
  DemoApp/Sources/Views/CallTopView/DemoCallTopView.swift
  DemoApp/Sources/Views/CallView/CallingView/DemoCallingViewModifier.swift
  DemoApp/Sources/Views/CallView/CallingView/SimpleCallingView.swift
  DemoApp/Sources/Views/CallView/DemoCallContainerView.swift
  DemoApp/Sources/Views/Login/DebugMenu.swift
  Sources/StreamVideo/CallState.swift
  Sources/StreamVideo/Utils/Sorting.swift
  Sources/StreamVideoSwiftUI/CallViewModel.swift
  Sources/StreamVideoSwiftUI/Livestreaming/LivestreamPlayer.swift
Labels: enhancement

#600 [Fix]StreamVideo unable to connect from CallKit
  CHANGELOG.md
  Sources/StreamVideo/WebSockets/Client/ConnectionRecoveryHandler.swift
Labels: bug

#608 [Fix]Update deviceToken to empty once unregister void notifications
  CHANGELOG.md
  DocumentationTests/DocumentationTests/DocumentationTests/06-advanced/03-callkit-integration.swift
  Sources/StreamVideo/CallKit/CallKitPushNotificationAdapter.swift
  StreamVideoTests/CallKit/CallKitPushNotificationAdapterTests.swift
Labels: bug
