Repository GetStream/stream-video-swift, pull requests merged in 2024-04, with the labels that each got.

#339 [Fix]CallKit crash and Call management
  DemoApp/Sources/AppDelegate.swift
  DemoApp/Sources/Components/Services/CallKitService.swift
  DemoApp/Sources/Components/Services/CallService.swift
  StreamVideo.xcodeproj/project.pbxproj
  docusaurus/docs/iOS/06-advanced/03-callkit-integration.mdx
Labels: bug

#341 [Fix]Stop recording when closing the Lobby
  Sources/StreamVideoSwiftUI/CallingViews/PreJoiningView.swift
Labels: bug

#342 [Fix]Stop PiP when app moves to foreground
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamPictureInPictureController.swift
Labels: bug

#344 Fix google client id on CI
  .github/workflows/testflight.yml
  fastlane/Fastfile
Labels: CI/CD

#346 [CleanUp]Remove AVAudioRecorder creation timing
  Sources/StreamVideo/Utils/AudioRecorder/StreamCallAudioRecorder.swift
Labels: enhancement

#347 Fix E2E test hierarchy issue on iOS 15
  SwiftUIDemoAppUITests/Pages/LobbyPage.swift
Labels: CI/CD

#350 [Improvement]Implement VideoRendererPool
  Sources/StreamVideoSwiftUI/CallView/VideoRenderer.swift
  Sources/StreamVideoSwiftUI/CallView/VideoRendererFactory.swift
  Sources/StreamVideoSwiftUI/Utils.swift
  Sources/StreamVideoSwiftUI/Utils/ReusePool.swift
  Sources/StreamVideoSwiftUI/Utils/VideoRendererPool/VideoRendererPool.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoSwiftUITests/Utils/ReusePool_Tests.swift
Labels: enhancement

#353 [Feature]Noise cancellation
  CHANGELOG.md
  DemoApp/Sources/Components/AppState.swift
  DemoApp/Sources/Components/AudioFilter/AudioFilter.swift
  DemoApp/Sources/Components/AudioFilter/DemoVoiceProcessor.swift
  DemoApp/Sources/Components/AudioFilter/RobotVoiceFilter.swift
  DemoApp/Sources/Components/Router.swift
  DemoApp/Sources/Extensions/RTCDefaultAudioProcessingModule+AudioProcessingModule.swift
  DemoApp/Sources/ViewModifiers/MoreControls/DemoMoreControlsViewModifier.swift
  DocumentationTests/DocumentationTests/DocumentationTests/06-advanced/06-apply-video-filters.swift
  DocumentationTests/DocumentationTests/DocumentationTests/GloballyUsedVariables.swift
  Sources/StreamVideo/Call.swift
  Sources/StreamVideo/Controllers/CallController.swift
  Sources/StreamVideo/StreamVideo.swift
  Sources/StreamVideo/VideoConfig.swift
  Sources/StreamVideo/WebRTC/AudioFilter/AudioFilter.swift
  Sources/StreamVideo/WebRTC/AudioFilter/Filters/NoiseCancellationFilter.swift
  Sources/StreamVideo/WebRTC/AudioFilter/StreamAudioFilterCapturePostProcessingModule.swift
  Sources/StreamVideo/WebRTC/AudioFilter/StreamAudioProcessingModule.swift
  Sources/StreamVideo/WebRTC/PeerConnectionFactory.swift
  Sources/StreamVideo/WebRTC/WebRTCClient.swift
  Sources/StreamVideoSwiftUI/CallViewModel.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoSwiftUITests/Utils/PictureInPicture/StreamPictureInPictureTrackStateAdapterTests.swift
  StreamVideoTests/WebRTC/WebRTCClient_Tests.swift
  docusaurus/docs/iOS/06-advanced/06-apply-video-filters.mdx
Labels: enhancement

#358 [Feature]Toggle Transcriptions
  DemoApp/Sources/ViewModifiers/MoreControls/DemoMoreControlsViewModifier.swift
  DocumentationTests/DocumentationTests/DocumentationTests.xcodeproj/project.pbxproj
  DocumentationTests/DocumentationTests/DocumentationTests/05-ui-cookbook/18-transcriptions.swift
  Sources/StreamVideo/Call.swift
  Sources/StreamVideo/CallState.swift
  Sources/StreamVideo/Utils/Models+Sendable.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoTests/Call/Call_Tests.swift
  docusaurus/docs/iOS/05-ui-cookbook/18-transcriptions.mdx
Labels: enhancement

#361 Handle `call_display_name` on VoIP notifications
  CHANGELOG.md
  Sources/StreamVideo/CallKit/CallKitPushNotificationAdapter.swift
  StreamVideoTests/CallKit/CallKitPushNotificationAdapterTests.swift
  docusaurus/docs/iOS/06-advanced/03-callkit-integration.mdx
Labels: enhancement

#363 [Docs]Small corrections/updates
  docusaurus/docs/iOS/05-ui-cookbook/18-transcriptions.mdx
  docusaurus/docs/iOS/06-advanced/03-callkit-integration.mdx
Labels: documentation

#366 [Fix]VoIP Push Notification registration docs
  DocumentationTests/DocumentationTests/DocumentationTests/06-advanced/03-callkit-integration.swift
  docusaurus/docs/iOS/06-advanced/03-callkit-integration.mdx
Labels: bug, documentation

#367 Remove auto-signing for Debug builds on CI
  fastlane/Fastfile
Labels: CI/CD

#371 [Fix]Failing tests due to AudioProcessingModule lifecycle
  StreamVideoSwiftUITests/Utils/PictureInPicture/StreamPictureInPictureTrackStateAdapterTests.swift
  StreamVideoTests/WebRTC/WebRTCClient_Tests.swift
Labels: bug

#372 [LLC]Public interface cleanup
  Sources/StreamVideo/StreamVideo.swift
  Sources/StreamVideo/Utils/Atomic.swift
  Sources/StreamVideo/Utils/AudioRecorder/StreamCallAudioRecorder.swift
  Sources/StreamVideo/Utils/Sorting.swift
  Sources/StreamVideo/Utils/StreamRuntimeCheck.swift
  Sources/StreamVideo/Utils/ThermalStateObserver.swift
  Sources/StreamVideo/WebRTC/Screensharing/BroadcastObserver.swift
  Sources/StreamVideo/WebRTC/Screensharing/BroadcastSampleHandler.swift
  Sources/StreamVideo/WebRTC/SimulatorScreenCapturer.swift
  StreamVideoSwiftUITests/CallViewModel_Tests.swift
  StreamVideoTests/IntegrationTests/IntegrationTest.swift
Labels: documentation, enhancement

#374 [NoiseCancellation]Integrate and cleanUp
  DemoApp/Sources/Components/AppState.swift
  Sources/StreamVideo/Call.swift
  Sources/StreamVideo/VideoConfig.swift
  Sources/StreamVideo/WebRTC/AudioFilter/Filters/NoiseCancellationFilter.swift
  Sources/StreamVideo/WebRTC/AudioFilter/StreamAudioFilterCapturePostProcessingModule.swift
  Sources/StreamVideo/WebRTC/AudioFilter/StreamAudioProcessingModule.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoTests/Mock/VideoConfig+Dummy.swift
Labels: enhancement

#373 [UI]Public interface cleanup
  Sources/StreamVideoSwiftUI/Appearance.swift
  Sources/StreamVideoSwiftUI/CallView/CallControlsView.swift
  Sources/StreamVideoSwiftUI/CallView/ConnectionQualityIndicator.swift
  Sources/StreamVideoSwiftUI/CallView/CornerDraggableView.swift
  Sources/StreamVideoSwiftUI/CallView/LayoutComponents/ControlBadgeView.swift
  Sources/StreamVideoSwiftUI/CallView/Participants/CallParticipantMenuAction.swift
  Sources/StreamVideoSwiftUI/CallView/Participants/InviteParticipantsViewModel.swift
  Sources/StreamVideoSwiftUI/CallView/Participants/UserListProvider.swift
  Sources/StreamVideoSwiftUI/CallView/VideoRenderer.swift
  Sources/StreamVideoSwiftUI/CallView/ViewModifiers/Snapshot/SnapshotViewModifier.swift
  Sources/StreamVideoSwiftUI/CallingViews/IncomingCallView.swift
  Sources/StreamVideoSwiftUI/StreamVideoUI.swift
  Sources/StreamVideoSwiftUI/Utils.swift
  Sources/StreamVideoSwiftUI/Utils/CallSoundsPlayer.swift
  Sources/StreamVideoSwiftUI/Utils/DeviceOrientation/StreamDeviceOrientationAdapter.swift
  Sources/StreamVideoSwiftUI/Utils/Formatters/Formatters.swift
  Sources/StreamVideoSwiftUI/Utils/HalfSheetView.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamPictureInPictureAdapter.swift
Labels: documentation, enhancement

#370 Update API and docs for NoiseCancellation
  DemoApp/Sources/ViewModifiers/MoreControls/DemoMoreControlsViewModifier.swift
  DocumentationTests/DocumentationTests/DocumentationTests.xcodeproj/project.pbxproj
  DocumentationTests/DocumentationTests/DocumentationTests/03-guides/16-noise-cancellation.swift
  DocumentationTests/DocumentationTests/DocumentationTests/05-ui-cookbook/19-noise-cancellation.swift
  DocumentationTests/DocumentationTests/DocumentationTests/06-advanced/06-apply-video-filters.swift
  DocumentationTests/DocumentationTests/DocumentationTests/GloballyUsedVariables.swift
  StreamVideo.xcodeproj/project.pbxproj
  docusaurus/docs/iOS/03-guides/04-camera-and-microphone.mdx
  docusaurus/docs/iOS/03-guides/04-noise-cancellation.mdx
  docusaurus/docs/iOS/05-ui-cookbook/19-noise-cancellation.mdx
  docusaurus/docs/iOS/06-advanced/06-apply-video-filters.mdx
Labels: enhancement
