Repository GetStream/stream-video-swift, pull requests merged in 2024-05, with the labels that each got.

#376 [Fix]AsyncImage on iOS 15 and below
  Sources/StreamVideoSwiftUI/Utils/AsyncImage/StreamAsyncImage.swift
Labels: bug

#379 [Docs]Update Readme with NoiseCancellation
  README.md
Labels: documentation

#378 [Docs]NoiseCancellation docs to mention performance needs
  docusaurus/docs/iOS/03-guides/04-noise-cancellation.mdx
  docusaurus/docs/iOS/05-ui-cookbook/19-noise-cancellation.mdx
Labels: documentation

#382 [Feature]Collect user feedback
  CHANGELOG.md
  DemoApp/Resources/Assets/Assets.xcassets/feedback-logo.imageset/Contents.json
  DemoApp/Resources/Assets/Assets.xcassets/feedback-logo.imageset/feedback-logo.pdf
  DemoApp/Sources/Components/AppEnvironment.swift
  DemoApp/Sources/Components/Feedback/DemoFeedbackView.swift
  DemoApp/Sources/ViewModifiers/ModalNavigationBar/DemoModalNavigationBarViewModifier.swift
  DemoApp/Sources/Views/CallView/DemoCallContainerView.swift
  DemoApp/Sources/Views/Login/AddUserView.swift
  DocumentationTests/DocumentationTests/DocumentationTests.xcodeproj/project.pbxproj
  DocumentationTests/DocumentationTests/DocumentationTests/05-ui-cookbook/18-call-quality-rating.swift
  DocumentationTests/DocumentationTests/DocumentationTests/05-ui-cookbook/19-transcriptions.swift
  DocumentationTests/DocumentationTests/DocumentationTests/05-ui-cookbook/20-noise-cancellation.swift
  DocumentationTests/DocumentationTests/DocumentationTests/GloballyUsedVariables.swift
  Sources/StreamVideo/Call.swift
  Sources/StreamVideo/Controllers/CallController.swift
  Sources/StreamVideo/Utils/Models+Sendable.swift
  Sources/StreamVideo/Utils/SystemEnvironment.swift
  Sources/StreamVideo/Utils/Utils.swift
  Sources/StreamVideoSwiftUI/CallView/ViewModifiers/CallEndedViewModifier.swift
  Sources/StreamVideoSwiftUI/CallViewModel.swift
  Sources/StreamVideoSwiftUI/Utils/Extensions/View+OptionalPublisher.swift
  Sources/StreamVideoSwiftUI/Utils/ViewExtensions.swift
  StreamVideo.xcodeproj/project.pbxproj
  docusaurus/docs/iOS/05-ui-cookbook/18-call-quality-rating.mdx
  docusaurus/docs/iOS/05-ui-cookbook/19-transcriptions.mdx
  docusaurus/docs/iOS/05-ui-cookbook/20-noise-cancellation.mdx
  docusaurus/docs/iOS/assets/call-quality-rating.png
  docusaurus/shared
  package-lock.json
Labels: enhancement

#388 [Fix]CallKitService ending call while busy
  Sources/StreamVideo/CallKit/CallKitService.swift
Labels: bug

#389 [Fix]Compilation issues in Xcode 14
  DemoApp/Resources/Assets/Assets.xcassets/feedbackLogo.imageset/Contents.json
  DemoApp/Resources/Assets/Assets.xcassets/feedbackLogo.imageset/feedback-logo.pdf
  DemoApp/Sources/Components/Feedback/DemoFeedbackView.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoTests/Utilities/Extensions/XCTestCase+PredicateFulfillment.swift
  TestTools/TestData/XCTestCase+SafeFulfillment.swift
Labels: bug, CI/CD

#391 [Fix]Undo name override on User
  CHANGELOG.md
  Sources/StreamVideo/Models/User.swift
  Sources/StreamVideo/StreamVideo.swift
Labels: bug

#352 [Improvement]Testing
  Sources/StreamVideo/Call.swift
  Sources/StreamVideo/CallKit/CallKitService.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoTests/CallKit/CallKitServiceTests.swift
  StreamVideoTests/Mock/CallController_Mock.swift
  StreamVideoTests/Mock/MockCXCallController.swift
  StreamVideoTests/Mock/MockCall.swift
  StreamVideoTests/Mock/MockStreamVideo.swift
  StreamVideoTests/TestUtils/Mockable.swift
  StreamVideoTests/Utilities/Dummy/Credentials+Dummy.swift
  StreamVideoTests/Utilities/Dummy/JoinCallResponse+Dummy.swift
  StreamVideoTests/Utilities/Dummy/MemberResponse+Dummy.swift
  StreamVideoTests/Utilities/Dummy/SFUResponse+Dummy.swift
Labels: enhancement

#395 [Fix]Memory issue on SimulatorScreenCapturer
  Sources/StreamVideo/WebRTC/SimulatorScreenCapturer.swift
  Sources/StreamVideo/WebRTC/VideoCapturer.swift
  Sources/StreamVideo/WebRTC/WebRTCClient.swift
Labels: bug

#394 Bump minimum supported Swift version
  .github/workflows/cron-checks.yml
  .github/workflows/smoke-checks.yml
  .swiftformat
  Brewfile.lock.json
  Package.swift
  README.md
  StreamVideo-XCFramework.podspec
  StreamVideo.podspec
  StreamVideoSwiftUI-XCFramework.podspec
  StreamVideoSwiftUI.podspec
  StreamVideoUIKit-XCFramework.podspec
  StreamVideoUIKit.podspec
  fastlane/Fastfile
Labels: CI/CD

#399 Remove macOS from Package.swift
  Package.swift
Labels: CI/CD

#403 [Fix]StreamAudioFilterProcessingModule release issues
  Sources/StreamVideo/VideoConfig.swift
  Sources/StreamVideo/WebRTC/AudioFilter/StreamAudioProcessingModule.swift
Labels: bug

#402 [Fix]Memory issues causing Call objects to leak
  DemoApp/Sources/Components/Snapshot/LocalParticipantSnapshotViewModel.swift
  DemoApp/Sources/Extensions/DemoApp+Sentry.swift
  Sources/StreamVideo/Call.swift
  Sources/StreamVideo/CallKit/CallKitService.swift
  Sources/StreamVideo/Controllers/CallController.swift
  Sources/StreamVideo/StreamVideo.swift
  Sources/StreamVideo/Utils/AudioRecorder/StreamCallAudioRecorder.swift
  Sources/StreamVideo/Utils/UnfairQueue/UnfairQueue.swift
  Sources/StreamVideo/WebRTC/WebRTCClient.swift
  Sources/StreamVideoSwiftUI/CallView/CallControls/Stateless/StatelessParticipantsListButton.swift
  Sources/StreamVideoSwiftUI/CallView/VideoRenderer.swift
  Sources/StreamVideoSwiftUI/CallView/ViewModifiers/CallEndedViewModifier.swift
  Sources/StreamVideoSwiftUI/CallViewModel.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamPictureInPictureAdapter.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideo.xcodeproj/xcshareddata/xcschemes/DemoApp.xcscheme
Labels: bug, enhancement

#404 [Enhancement]Use single instances for Call objects with the same cId
  CHANGELOG.md
  Sources/StreamVideo/Call.swift
  Sources/StreamVideo/StreamVideo.swift
  Sources/StreamVideo/Utils/CallCache/CallCache.swift
  Sources/StreamVideoSwiftUI/CallView/CallControls/Stateless/StatelessHangUpIconView.swift
  Sources/StreamVideoSwiftUI/CallView/VideoParticipantsView.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoTests/Mock/MockResponseBuilder.swift
  StreamVideoTests/StreamVideo_Tests.swift
  StreamVideoTests/Utilities/Extensions/XCTestCase+PredicateFulfillment.swift
  StreamVideoTests/Utils/CallCache_Tests.swift
Labels: enhancement

#410 [Minor]Preselect 5 star rating
  DemoApp/Sources/Components/Feedback/DemoFeedbackView.swift
Labels: enhancement

#411 Dispatch CallKit reporting to mainActor
  CHANGELOG.md
  Sources/StreamVideo/CallKit/CallKitPushNotificationAdapter.swift
  Sources/StreamVideo/CallKit/CallKitService.swift
  StreamVideoTests/CallKit/CallKitPushNotificationAdapterTests.swift
  StreamVideoTests/CallKit/CallKitServiceTests.swift
Labels: enhancement

#415 [Fix]Sync call state handling between CallKit and CallViewModel
  Sources/StreamVideo/CallKit/CallKitService.swift
  Sources/StreamVideo/Utils/StateMachine/CallStateMachine/Stages/StreamCallStateMachine+RejectingStage.swift
  Sources/StreamVideo/Utils/UUIDProviding/StreamUUIDFactory.swift
  Sources/StreamVideo/Utils/Utils.swift
  Sources/StreamVideoSwiftUI/CallView/Participants/CallParticipantsInfoViewModel.swift
  Sources/StreamVideoSwiftUI/CallViewModel.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoTests/CallKit/CallKitServiceTests.swift
  StreamVideoTests/Utilities/Extensions/XCTestCase+PredicateFulfillment.swift
  StreamVideoTests/Utilities/Mocks/MockCXProvider.swift
Labels: bug

#420 [Enhancement]Allow configuring CallKit supported call types
  CHANGELOG.md
  DocumentationTests/DocumentationTests/DocumentationTests/06-advanced/03-callkit-integration.swift
  Sources/StreamVideo/CallKit/CallKitService.swift
  StreamVideoTests/CallKit/CallKitServiceTests.swift
  docusaurus/docs/iOS/06-advanced/03-callkit-integration.mdx
Labels: enhancement
