Repository GetStream/stream-video-swift, pull requests merged in 2024-02, with the labels that each got.

#279 [Redesign]Address UI/UX feedback
  Sources/StreamVideoSwiftUI/CallView/Participants/CallParticipantsInfoView.swift
  Sources/StreamVideoSwiftUI/CallView/ParticipantsGridLayout.swift
  Sources/StreamVideoSwiftUI/Utils/HalfSheetView.swift
  Sources/StreamVideoSwiftUI/Utils/Modifiers.swift
Labels: enhancement

#281 Improve statistics collection
  DemoApp/Sources/Components/Stats/ParticipantStatsViewModel.swift
  Sources/StreamVideo/Models/CallStatsReport.swift
  Sources/StreamVideo/WebRTC/Statistics/Statistics+Convenience.swift
  Sources/StreamVideo/WebRTC/Statistics/StreamCallStatisticsFormatter.swift
  Sources/StreamVideo/WebRTC/Statistics/StreamCallStatisticsReporter.swift
  Sources/StreamVideo/WebRTC/StatsReporter.swift
  Sources/StreamVideo/WebRTC/WebRTCClient.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoTests/WebRTC/Statistics/Mocks/MockStreamStatistics.swift
  StreamVideoTests/WebRTC/Statistics/StreamCallStatisticsFormatter_Tests.swift
  StreamVideoTests/WebRTC/StatsReporter_Tests.swift
Labels: enhancement

#270 [Redesign]Demo App
  DemoApp/Sources/Components/Stats/DemoVideoCallParticipantOptionsModifier.swift
  DemoApp/Sources/Components/Stats/ParticipantStatsView.swift
  DemoApp/Sources/Components/Stats/ParticipantStatsViewModel.swift
  DemoApp/Sources/Components/Stats/RawStatsView.swift
  DemoApp/Sources/Controls/CallButtonView.swift
  DemoApp/Sources/Controls/CallButtonView/CallButtonView.swift
  DemoApp/Sources/Controls/DemoAppCallControlsView.swift
  DemoApp/Sources/Controls/DemoControls.swift
  DemoApp/Sources/Controls/DemoMoreControls/DemoMoreControlListButtonView.swift
  DemoApp/Sources/Controls/DemoMoreControls/DemoReactionButton.swift
  DemoApp/Sources/Controls/DemoParticipantOptionsButton.swift
  DemoApp/Sources/Models/Reaction.swift
  DemoApp/Sources/ViewModifiers/CallModifier/DemoCallModifier.swift
  DemoApp/Sources/ViewModifiers/ChangeEnvironmentViewModifier/ChangeEnvironmentViewModifier.swift
  DemoApp/Sources/ViewModifiers/DemoChatModifier.swift
  DemoApp/Sources/ViewModifiers/DragIndicatorViewModifier/DragIndicatorViewModifier.swift
  DemoApp/Sources/ViewModifiers/LongPressToFocusViewModifier/LongPressToFocusViewModifier.swift
  DemoApp/Sources/ViewModifiers/ModalNavigationBar/DemoModalNavigationBarViewModifier.swift
  DemoApp/Sources/ViewModifiers/MoreControls/DemoMoreControlsViewModifier.swift
  DemoApp/Sources/ViewModifiers/ThermalStateViewModifier/ThermalStateViewModifier.swift
  DemoApp/Sources/ViewModifiers/VideoCallParticipantModifier/DemoLocalViewModifier.swift
  DemoApp/Sources/ViewModifiers/VideoCallParticipantModifier/DemoVideoCallParticipantModifier.swift
  DemoApp/Sources/Views/CallTopView/DemoCallTopView.swift
  DemoApp/Sources/Views/CallView/DemoCallView.swift
  DemoApp/Sources/Views/CallView/DemoQRCodeScannerButton.swift
  DemoApp/Sources/Views/Login/LoginView.swift
  DemoApp/Sources/Views/StatsView/DemoStatsView.swift
  DemoApp/Sources/Views/WaitingLocalUserView/DemoWaitingLocalUserView.swift
  Sources/StreamVideo/WebRTC/Statistics/StreamCallStatisticsFormatter.swift
  Sources/StreamVideo/WebRTC/WebRTCClient.swift
  Sources/StreamVideoSwiftUI/CallView/Participants/CallParticipantsInfoView.swift
  Sources/StreamVideoSwiftUI/CallView/ParticipantsGridLayout.swift
  Sources/StreamVideoSwiftUI/Utils/HalfSheetView.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoTests/WebRTC/Statistics/StreamCallStatisticsFormatter_Tests.swift
  SwiftUIDemoAppUITests/Robots/UserRobot+Asserts.swift
Labels: enhancement

#284 [Enhancement]Improve device orientation changes
  CHANGELOG.md
  DemoApp/Sources/Controls/DemoMoreControls/DemoReactionButton.swift
  DocumentationTests/DocumentationTests/DocumentationTests/04-ui-components/08-participants/02-call-participants.swift
  Sources/StreamVideoSwiftUI/CallView/ParticipantsGridLayout.swift
  Sources/StreamVideoSwiftUI/CallView/ScreenSharing/ScreenSharingView.swift
  Sources/StreamVideoSwiftUI/CallView/VideoParticipantsView.swift
  Sources/StreamVideoSwiftUI/Utils/DeviceOrientation/StreamDeviceOrientationAdapter.swift
  Sources/StreamVideoSwiftUI/Utils/Modifiers.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoSwiftUITests/CallView/ParticipantsGridLayout_Tests.swift
  StreamVideoSwiftUITests/CallView/__Snapshots__/ScreenSharingView_Tests/test_screenSharingView_snapshot.default-dark.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ScreenSharingView_Tests/test_screenSharingView_snapshot.default-light.png
  docusaurus/docs/iOS/04-ui-components/08-participants/02-call-participants.mdx
Labels: enhancement

#283 [Feature]Capture CallView snapshot
  DemoApp/Sources/Components/DemoAppViewFactory.swift
  DemoApp/Sources/Components/SnapshotTrigger.swift
  DemoApp/Sources/Extensions/CallViewModel+Snapshot.swift
  DemoApp/Sources/ViewModifiers/MoreControls/DemoMoreControlsViewModifier.swift
  DemoApp/Sources/Views/CallView/DemoCallView.swift
  DemoApp/Sources/Views/CallView/DemoSnapshotViewModel.swift
  DocumentationTests/DocumentationTests/DocumentationTests.xcodeproj/project.pbxproj
  DocumentationTests/DocumentationTests/DocumentationTests/05-ui-cookbook/16-snapshot.swift
  DocumentationTests/DocumentationTests/DocumentationTests/GloballyUsedVariables.swift
  Sources/StreamVideo/WebSockets/Events/Event.swift
  Sources/StreamVideoSwiftUI/CallView/ViewModifiers/Snapshot/SnapshotViewModifier.swift
  Sources/StreamVideoSwiftUI/CallView/ViewModifiers/Snapshot/UIView+Snapshot.swift
  Sources/StreamVideoSwiftUI/Models/Toast.swift
  Sources/StreamVideoSwiftUI/Utils/ToastView.swift
  StreamVideo.xcodeproj/project.pbxproj
  docusaurus/docs/iOS/05-ui-cookbook/16-snapshot.mdx
Labels: enhancement

#289 [Fix]User handling in demo app
  DemoApp/Sources/Components/Authentication/AuthenticationProvider.swift
  DemoApp/Sources/DemoApp.swift
  DemoApp/Sources/Views/CallView/CallingView/DemoCallingViewModifier.swift
  DemoApp/Sources/Views/CallView/CallingView/DetailedCallingView.swift
  DemoApp/Sources/Views/CallView/CallingView/SimpleCallingView.swift
  DemoApp/Sources/Views/CallView/DemoCallContentView.swift
  DemoApp/Sources/Views/CallView/DemoCallingTopView.swift
  DemoApp/Sources/Views/Login/LoginView.swift
  DemoApp/Sources/Views/Login/LoginViewModel.swift
  StreamVideo.xcodeproj/project.pbxproj
  SwiftUIDemoAppUITests/Tests/DeeplinkTests.swift
  fastlane/sinatra.rb
Labels: bug, CI/CD

#291 [Fix]Finish stream continuations
  Sources/StreamVideo/Call.swift
  Sources/StreamVideo/StreamVideo.swift
  Sources/StreamVideo/Utils/Utils.swift
Labels: bug

#290 Fix small snapshot issues
  DemoApp/Sources/Components/DemoAppViewFactory.swift
  DemoApp/Sources/Extensions/CallViewModel+Snapshot.swift
  DemoApp/Sources/Views/CallTopView/DemoCallTopView.swift
  DemoApp/Sources/Views/CallView/CallingView/DemoCallingViewModifier.swift
  DemoApp/Sources/Views/CallView/CallingView/DetailedCallingView.swift
  DocumentationTests/DocumentationTests/DocumentationTests/05-ui-cookbook/16-snapshot.swift
  Sources/StreamVideoSwiftUI/CallView/ViewModifiers/Snapshot/SnapshotViewModifier.swift
  StreamVideoSwiftUITests/StreamVideoSwiftUI.xctestplan
  StreamVideoTests/TestUtils/AssertDelay.swift
  docusaurus/docs/iOS/05-ui-cookbook/16-snapshot.mdx
Labels: bug

#293 [Fix]Crop & Scale RTCCVPixelBuffer frames
  Sources/StreamVideoSwiftUI/Utils/Extensions/CVPixelBuffer+Convenience.swift
  Sources/StreamVideoSwiftUI/Utils/Extensions/RTCCVPixelBuffer+Convenience.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamBufferTransformer.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamPictureInPictureVideoRenderer.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoSwiftUITests/Utils/PictureInPicture/StreamBufferTransformerTests.swift
Labels: bug

#298 Fix warnings on older Xcode versions
  Sources/StreamVideo/CallSettings/CameraManager.swift
  Sources/StreamVideo/CallSettings/MicrophoneManager.swift
  Sources/StreamVideo/CallSettings/SpeakerManager.swift
  Sources/StreamVideo/CallState.swift
  Sources/StreamVideo/StreamVideo.swift
  Sources/StreamVideo/WebRTC/Screensharing/BroadcastObserver.swift
  Sources/StreamVideoSwiftUI/CallView/CallDurationView.swift
Labels: bug

#297 [CI] Build SDKs on Xcode 15.0
  .github/workflows/cron-checks.yml
  .github/workflows/smoke-checks.yml
  fastlane/Fastfile
Labels: CI/CD

#295 [Improvement]Move participantEvent in a viewModifier
  Sources/StreamVideoSwiftUI/CallView/CallView.swift
  Sources/StreamVideoSwiftUI/CallView/ViewModifiers/ParticipantEventViewModifier.swift
  StreamVideo.xcodeproj/project.pbxproj
Labels: bug, enhancement

#301 [Feature]Allow setting capturePhoto and video outputs for local participant
  CHANGELOG.md
  DemoApp/Sources/Components/Snapshot/LocalParticipantSnapshotViewModel.swift
  DemoApp/Sources/Components/Snapshot/SnapshotTrigger.swift
  DemoApp/Sources/ViewModifiers/MoreControls/DemoMoreControlsViewModifier.swift
  DocumentationTests/DocumentationTests/DocumentationTests.xcodeproj/project.pbxproj
  DocumentationTests/DocumentationTests/DocumentationTests/05-ui-cookbook/16-snapshot.swift
  DocumentationTests/DocumentationTests/DocumentationTests/05-ui-cookbook/17-camera-zoom.swift
  DocumentationTests/DocumentationTests/DocumentationTests/GloballyUsedVariables.swift
  Sources/StreamVideo/Call.swift
  Sources/StreamVideo/Controllers/CallController.swift
  Sources/StreamVideo/Utils/AVCaptureSession+ActiveCaptureDevice.swift
  Sources/StreamVideo/WebRTC/VideoCapturer.swift
  Sources/StreamVideo/WebRTC/WebRTCClient.swift
  Sources/StreamVideoSwiftUI/Utils/HalfSheetView.swift
  StreamVideo.xcodeproj/project.pbxproj
  docusaurus/docs/iOS/05-ui-cookbook/16-snapshot.mdx
  docusaurus/docs/iOS/05-ui-cookbook/17-camera-zoom.mdx
Labels: enhancement

#302 [Improvement]Allow removing videoOutputs from AVCaptureSession
  CHANGELOG.md
  DemoApp/Sources/Components/Snapshot/LocalParticipantSnapshotViewModel.swift
  DemoApp/Sources/ViewModifiers/MoreControls/DemoMoreControlsViewModifier.swift
  DocumentationTests/DocumentationTests/DocumentationTests/05-ui-cookbook/16-snapshot.swift
  Sources/StreamVideo/Call.swift
  Sources/StreamVideo/Controllers/CallController.swift
  Sources/StreamVideo/WebRTC/VideoCapturer.swift
  Sources/StreamVideo/WebRTC/WebRTCClient.swift
  docusaurus/docs/iOS/05-ui-cookbook/16-snapshot.mdx
  docusaurus/docs/iOS/05-ui-cookbook/17-camera-zoom.mdx
Labels: enhancement

#304 Replace wget with curl in cocoapods prepare command
  StreamVideo-XCFramework.podspec
  StreamVideo.podspec
Labels: CI/CD

#306 Update the way we test deeplinks
  SwiftUIDemoAppUITests/Tests/DeeplinkTests.swift
  SwiftUIDemoAppUITests/Tests/StreamTestCase.swift
  TestTools/Robots/Sinatra.swift
  fastlane/sinatra.rb
Labels: CI/CD

#307 [DemoApp & Docs]CallService unregister
  DemoApp/Sources/Components/Services/CallService.swift
  DemoApp/Sources/Components/Services/VoIPPushService.swift
  DocumentationTests/DocumentationTests/DocumentationTests/06-advanced/02-push-notifications.swift
  docusaurus/docs/iOS/06-advanced/03-callkit-integration.mdx
Labels: documentation

#303 [Fix]Single instance AVAudioRecorder
  DemoApp/Sources/Views/CallView/CallingView/DemoCallingViewModifier.swift
  DemoApp/Sources/Views/CallView/DemoCallView.swift
  DemoApp/Sources/Views/CustomCallView.swift
  DocumentationTests/DocumentationTests/DocumentationTests/05-ui-cookbook/11-speaking-while-muted.swift
  Sources/StreamVideo/Models/CallSettings.swift
  Sources/StreamVideo/StreamVideo.swift
  Sources/StreamVideo/Utils/AudioRecorder/AVAudioRecorderBuilder.swift
  Sources/StreamVideo/Utils/AudioRecorder/AudioSessionProtocol.swift
  Sources/StreamVideo/Utils/AudioRecorder/StreamActiveCallProvider.swift
  Sources/StreamVideo/Utils/AudioRecorder/StreamCallAudioRecorder.swift
  Sources/StreamVideoSwiftUI/CallContainer.swift
  Sources/StreamVideoSwiftUI/CallView/CallTopView.swift
  Sources/StreamVideoSwiftUI/CallView/LocalParticipantViewModifier.swift
  Sources/StreamVideoSwiftUI/CallView/VideoRendererFactory.swift
  Sources/StreamVideoSwiftUI/CallViewModel.swift
  Sources/StreamVideoSwiftUI/CallingViews/MicrophoneChecker.swift
  Sources/StreamVideoSwiftUI/CallingViews/PreJoiningView.swift
  Sources/StreamVideoSwiftUI/CallingViews/PreJoiningViewModel.swift
  Sources/StreamVideoSwiftUI/CallingViews/iOS13/PreJoiningView_iOS13.swift
  Sources/StreamVideoSwiftUI/Utils/Camera.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoSwiftUITests/CallingViews/MicrophoneChecker_Tests.swift
  StreamVideoTests/Utils/StreamCallAudioRecorderTests.swift
  SwiftUIDemoAppUITests/Robots/UserRobot+Asserts.swift
  docusaurus/docs/iOS/05-ui-cookbook/11-speaking-while-muted.mdx
Labels: enhancement

#308 Remove unnecessary usage of RTCCameraVideoCapturer
  Sources/StreamVideo/WebRTC/Screensharing/BroadcastScreenCapturer.swift
  Sources/StreamVideo/WebRTC/Screensharing/ScreenshareCapturer.swift
Labels: enhancement

#310 Update XCTest fulfillment function
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoSwiftUITests/CallingViews/MicrophoneChecker_Tests.swift
  StreamVideoTests/IntegrationTests/IntegrationTest.swift
  StreamVideoTests/Utils/StreamCallAudioRecorderTests.swift
  SwiftUIDemoAppUITests/Pages/CallPage.swift
  SwiftUIDemoAppUITests/Robots/UserRobot.swift
  SwiftUIDemoAppUITests/Tests/ReconnectionTests.swift
  TestTools/TestData/XCTestCase+SafeFulfillment.swift
Labels: CI/CD

#309 [Feature]Implement image and blur background filters
  CHANGELOG.md
  DemoApp/Resources/Assets/Assets.xcassets/Video Background Filter Images/Contents.json
  DemoApp/Resources/Assets/Assets.xcassets/Video Background Filter Images/amsterdam-1.imageset/Amsterdam 1.png
  DemoApp/Resources/Assets/Assets.xcassets/Video Background Filter Images/amsterdam-1.imageset/Contents.json
  DemoApp/Resources/Assets/Assets.xcassets/Video Background Filter Images/amsterdam-2.imageset/Amsterdam 2.png
  DemoApp/Resources/Assets/Assets.xcassets/Video Background Filter Images/amsterdam-2.imageset/Contents.json
  DemoApp/Resources/Assets/Assets.xcassets/Video Background Filter Images/boulder-1.imageset/Boulder 1.png
  DemoApp/Resources/Assets/Assets.xcassets/Video Background Filter Images/boulder-1.imageset/Contents.json
  DemoApp/Resources/Assets/Assets.xcassets/Video Background Filter Images/boulder-2.imageset/Boulder 2.png
  DemoApp/Resources/Assets/Assets.xcassets/Video Background Filter Images/boulder-2.imageset/Contents.json
  DemoApp/Resources/Assets/Assets.xcassets/Video Background Filter Images/gradient-1.imageset/Contents.json
  DemoApp/Resources/Assets/Assets.xcassets/Video Background Filter Images/gradient-1.imageset/Gradient 1.png
  DemoApp/Resources/Assets/Assets.xcassets/Video Background Filter Images/gradient-2.imageset/Contents.json
  DemoApp/Resources/Assets/Assets.xcassets/Video Background Filter Images/gradient-2.imageset/Gradient 2.png
  DemoApp/Resources/Assets/Assets.xcassets/Video Background Filter Images/gradient-3.imageset/Contents.json
  DemoApp/Resources/Assets/Assets.xcassets/Video Background Filter Images/gradient-3.imageset/Gradient 3.png
  DemoApp/Sources/Components/AppState.swift
  DemoApp/Sources/Controls/DemoMoreControls/DemoBackgroundEffectSelector.swift
  DemoApp/Sources/ViewModifiers/MoreControls/DemoMoreControlsViewModifier.swift
  DocumentationTests/DocumentationTests/DocumentationTests.xcodeproj/project.pbxproj
  DocumentationTests/DocumentationTests/DocumentationTests/06-advanced/06-apply-video-filters.swift
  DocumentationTests/DocumentationTests/DocumentationTests/GloballyUsedVariables.swift
  Sources/StreamVideo/Utils/SerialActor.swift
  Sources/StreamVideo/Utils/UIInterfaceOrientation+CGOrientation.swift
  Sources/StreamVideo/WebRTC/StreamVideoCaptureHandler.swift
  Sources/StreamVideo/WebRTC/VideoFilters.swift
  Sources/StreamVideo/WebRTC/VideoFilters/Extensions/CIImage+Resize.swift
  Sources/StreamVideo/WebRTC/VideoFilters/Extensions/CIImage+Sendable.swift
  Sources/StreamVideo/WebRTC/VideoFilters/Extensions/UIDevice+NeuralEngine.swift
  Sources/StreamVideo/WebRTC/VideoFilters/Filters/BlurBackgroundFilter/BlurBackgroundVideoFilter.swift
  Sources/StreamVideo/WebRTC/VideoFilters/Filters/ImageBackgroundFilter/ImageBackgroundVideoFilter.swift
  Sources/StreamVideo/WebRTC/VideoFilters/Utilities/BackgroundImageFilterProcessor.swift
  Sources/StreamVideo/WebRTC/VideoFilters/VideoFilters.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideo.xcodeproj/xcshareddata/xcbaselines/84F737F3287C13AD00A363F4.xcbaseline/05BF3974-39D5-4CF1-A0F9-3E40F2AA51F3.plist
  StreamVideo.xcodeproj/xcshareddata/xcbaselines/84F737F3287C13AD00A363F4.xcbaseline/Info.plist
  StreamVideoTests/Utils/SerialActor_Tests.swift
  StreamVideoTests/WebRTC/VideoFilters/Extensions/CIImage_Resize_Tests.swift
  docusaurus/docs/iOS/06-advanced/06-apply-video-filters.mdx
Labels: enhancement

#311 Remove token generation for E2E tests
  DemoApp/Sources/Components/AppEnvironment.swift
  DemoApp/Sources/Components/Authentication/AuthenticationProvider.swift
  DemoApp/Sources/Views/Login/DebugMenu.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoTests/IntegrationTests/CallCRUDTests.swift
  StreamVideoTests/IntegrationTests/IntegrationTest.swift
  SwiftUIDemoAppUITests/Tests/Authentication_Tests.swift
  TestTools/TestData/TokenGenerator.swift
Labels: enhancement, CI/CD
