Repository GetStream/stream-video-swift, pull requests merged in 2024-12, with the labels that each got.

#611 [Feature]Introduce CallKit availability policies
  CHANGELOG.md
  DocumentationTests/DocumentationTests/DocumentationTests/06-advanced/03-callkit-integration.swift
  DocumentationTests/DocumentationTests/DocumentationTests/GloballyUsedVariables.swift
  Sources/StreamVideo/CallKit/AvailabilityPolicy/CallKitAlwaysAvailabilityPolicy.swift
  Sources/StreamVideo/CallKit/AvailabilityPolicy/CallKitAvailabilityPolicy.swift
  Sources/StreamVideo/CallKit/AvailabilityPolicy/CallKitAvailabilityPolicyProtocol.swift
  Sources/StreamVideo/CallKit/AvailabilityPolicy/CallKitRegionBasedAvailabilityPolicy.swift
  Sources/StreamVideo/CallKit/CallKitAdapter.swift
  Sources/StreamVideo/Utils/LocaleProvider/StreamLocaleProvider.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoTests/CallKit/AvailabilityPolicy/CallKitRegionBasedAvailabilityPolicy.swift
Labels: enhancement

#613 [Fix]Sorting comparators for fullscreen layout and PiP
  CHANGELOG.md
  Sources/StreamVideo/Utils/Sorting.swift
  StreamVideoTests/Utils/Sorting_Tests.swift
Labels: bug

#612 [Feature]Report join call telemetry
  Sources/StreamVideo/WebRTC/v2/SFU/SFUAdapter.swift
  Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Joining.swift
  StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_JoiningStageTests.swift
Labels: enhancement

#615 [CI] Fix release script
  fastlane/Fastfile
Labels: CI/CD

#626 [Fix]Replace `#file` to `#fileID`
  Sources/StreamVideo/Errors/Errors.swift
  Sources/StreamVideo/Utils/AudioSession/StreamAudioSessionAdapter.swift
  Sources/StreamVideo/Utils/Logger/Array+Logger.swift
  Sources/StreamVideo/Utils/Logger/Logger.swift
  Sources/StreamVideo/Utils/Logger/Publisher+Logger.swift
  Sources/StreamVideo/Utils/StateMachine/Publisher+NextValue.swift
  Sources/StreamVideo/Utils/Unwrap/Unwrap.swift
  Sources/StreamVideo/WebRTC/v2/SFU/SFUAdapter.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCJoinRequestFactory.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift
  Sources/StreamVideo/WebSockets/Events/JsonEventDecoder.swift
Labels: enhancement
