Repository GetStream/stream-video-swift, pull requests merged in 2025-09, with the labels that each got.

#933 [Enhancement]Expose CallParticipant source
  CHANGELOG.md
  Sources/StreamVideo/Models/CallParticipant.swift
  Sources/StreamVideo/Models/Extensions/Stream_Video_Sfu_Models_Participant+CallParticipant.swift
  Sources/StreamVideo/Models/ParticipantSource.swift
  Sources/StreamVideo/Utils/Sorting/Participants.swift
  Sources/StreamVideo/Utils/Sorting/Presets.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCJoinRequestFactory.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoTests/Mock/CallParticipant_Mock.swift
  StreamVideoTests/Utils/Sorting_Tests.swift
  StreamVideoTests/WebRTC/v2/WebRTCJoinRequestFactory_Tests.swift
Labels: enhancement

#936 [Enhancement]Expand permissions prompts logic
  DemoApp/Sources/Components/MemoryLogDestination/LogQueue.swift
  Sources/StreamVideo/CallState.swift
  Sources/StreamVideo/Utils/AudioSession/AudioRecorder/Namespace/Middleware/StreamCallAudioRecorder+AVAudioRecorderMiddleware.swift
  Sources/StreamVideo/Utils/AudioSession/AudioRecorder/Namespace/Middleware/StreamCallAudioRecorder+ActiveCallMiddleware.swift
  Sources/StreamVideo/Utils/AudioSession/AudioRecorder/Namespace/Middleware/StreamCallAudioRecorder+ApplicationStateMiddleware.swift
  Sources/StreamVideo/Utils/AudioSession/AudioRecorder/Namespace/Middleware/StreamCallAudioRecorder+ShouldRecordMiddleware.swift
  Sources/StreamVideo/Utils/AudioSession/AudioRecorder/Namespace/StreamCallAudioRecorder+Namespace.swift
  Sources/StreamVideo/Utils/AudioSession/AudioRecorder/StreamCallAudioRecorder.swift
  Sources/StreamVideo/Utils/AudioSession/CallAudioSession.swift
  Sources/StreamVideo/Utils/AudioSession/RTCAudioStore/Actions/RTCAudioStoreAction.swift
  Sources/StreamVideo/Utils/AudioSession/RTCAudioStore/Effects/RTCAudioStore+InterruptionEffect.swift
  Sources/StreamVideo/Utils/AudioSession/RTCAudioStore/Extensions/RTCAudioStore+RestartAudioSession.swift
  Sources/StreamVideo/Utils/AudioSession/RTCAudioStore/RTCAudioStore.swift
  Sources/StreamVideo/Utils/PermissionsStore/PermissionsStore.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCPermissionsAdapter.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift
  Sources/StreamVideoSwiftUI/CallView/CallControls/Stateless/StatelessMicrophoneIconView.swift
  Sources/StreamVideoSwiftUI/CallView/CallControls/Stateless/StatelessVideoIconView.swift
  Sources/StreamVideoSwiftUI/CallView/PermissionsPromptView.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoSwiftUITests/CallView/CallControls/Stateless/StatelessMicrophoneIconView_Tests.swift
  StreamVideoSwiftUITests/CallView/CallControls/Stateless/StatelessVideoIconView_Tests.swift
  StreamVideoSwiftUITests/CallView/CallControls/Stateless/__Snapshots__/StatelessMicrophoneIconView_Tests/test_appearance_micOff_hasPermission_wasConfiguredCorrectly.default-dark.png
  StreamVideoSwiftUITests/CallView/CallControls/Stateless/__Snapshots__/StatelessMicrophoneIconView_Tests/test_appearance_micOff_hasPermission_wasConfiguredCorrectly.default-light.png
  StreamVideoSwiftUITests/CallView/CallControls/Stateless/__Snapshots__/StatelessMicrophoneIconView_Tests/test_appearance_micOn_hasPermission_wasConfiguredCorrectly.default-dark.png
  StreamVideoSwiftUITests/CallView/CallControls/Stateless/__Snapshots__/StatelessMicrophoneIconView_Tests/test_appearance_micOn_hasPermission_wasConfiguredCorrectly.default-light.png
  StreamVideoSwiftUITests/CallView/CallControls/Stateless/__Snapshots__/StatelessMicrophoneIconView_Tests/test_appearance_micOn_noPermission_canRequest_wasConfiguredCorrectly.default-dark.png
  StreamVideoSwiftUITests/CallView/CallControls/Stateless/__Snapshots__/StatelessMicrophoneIconView_Tests/test_appearance_micOn_noPermission_canRequest_wasConfiguredCorrectly.default-light.png
  StreamVideoSwiftUITests/CallView/CallControls/Stateless/__Snapshots__/StatelessMicrophoneIconView_Tests/test_appearance_micOn_noPermission_cannotRequestPermission_wasConfiguredCorrectly.default-dark.png
  StreamVideoSwiftUITests/CallView/CallControls/Stateless/__Snapshots__/StatelessMicrophoneIconView_Tests/test_appearance_micOn_noPermission_cannotRequestPermission_wasConfiguredCorrectly.default-light.png
  StreamVideoSwiftUITests/CallView/CallControls/Stateless/__Snapshots__/StatelessVideoIconView_Tests/test_appearance_videoOn_noPermission_canRequest_wasConfiguredCorrectly.default-dark.png
  StreamVideoSwiftUITests/CallView/CallControls/Stateless/__Snapshots__/StatelessVideoIconView_Tests/test_appearance_videoOn_noPermission_canRequest_wasConfiguredCorrectly.default-light.png
  StreamVideoSwiftUITests/CallView/CallControls/Stateless/__Snapshots__/StatelessVideoIconView_Tests/test_appearance_videoOn_noPermission_cannotRequestPermission_wasConfiguredCorrectly.default-dark.png
  StreamVideoSwiftUITests/CallView/CallControls/Stateless/__Snapshots__/StatelessVideoIconView_Tests/test_appearance_videoOn_noPermission_cannotRequestPermission_wasConfiguredCorrectly.default-light.png
  StreamVideoTests/Mock/MockWebRTCPermissionsAdapterDelegate.swift
  StreamVideoTests/Utils/AudioSession/AudioRecorder/Namespace/Middleware/StreamCallAudioRecorder_AVAudioRecorderMiddlewareTests.swift
  StreamVideoTests/Utils/AudioSession/AudioRecorder/Namespace/Middleware/StreamCallAudioRecorder_ActiveCallMiddlewareTests.swift
  StreamVideoTests/Utils/AudioSession/AudioRecorder/Namespace/Middleware/StreamCallAudioRecorder_ApplicationStateMiddlewareTests.swift
  StreamVideoTests/Utils/AudioSession/AudioRecorder/Namespace/Middleware/StreamCallAudioRecorder_ShouldRecordMiddlewareTests.swift
  StreamVideoTests/Utils/AudioSession/AudioRecorder/Namespace/StreamCallAudioRecorder_NamespaceTests.swift
  StreamVideoTests/Utils/PermissionStore/PermissionStore_Tests.swift
  StreamVideoTests/WebRTC/v2/WebRTCPermissionsAdapter_Tests.swift
  StreamVideoTests/WebRTC/v2/WebRTCStateAdapter_Tests.swift
Labels: enhancement, ✅ QAed

#940 [CI] Resolve slather issue
  fastlane/Fastfile
Labels: CI/CD

#942 [Fix]Improve AudioFilter pipeline
  AGENTS.md
  CHANGELOG.md
  Sources/StreamVideo/Utils/AudioSession/AudioProcessing/AudioProcessingStore.swift
  Sources/StreamVideo/Utils/AudioSession/AudioProcessing/Components/AudioCustomProcessingModule.swift
  Sources/StreamVideo/Utils/AudioSession/AudioProcessing/Namespace/AudioProcessingStore+Action.swift
  Sources/StreamVideo/Utils/AudioSession/AudioProcessing/Namespace/AudioProcessingStore+Namespace.swift
  Sources/StreamVideo/Utils/AudioSession/AudioProcessing/Namespace/AudioProcessingStore+State.swift
  Sources/StreamVideo/Utils/AudioSession/AudioProcessing/Namespace/Middleware/AudioProcessingStore+AudioFilterMiddleware.swift
  Sources/StreamVideo/Utils/AudioSession/AudioProcessing/Namespace/Middleware/AudioProcessingStore+CapturedChannelsMiddleware.swift
  Sources/StreamVideo/Utils/AudioSession/AudioProcessing/Namespace/Reducers/AudioProcessingStore+DefaultReducer.swift
  Sources/StreamVideo/Utils/Swift6Migration/Sendable+Extensions.swift
  Sources/StreamVideo/WebRTC/AudioFilter/StreamAudioFilterCapturePostProcessingModule.swift
  Sources/StreamVideo/WebRTC/AudioFilter/StreamAudioProcessingModule.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoTests/Mock/Audio/MockAudioFilter.swift
  StreamVideoTests/Utils/AudioSession/AudioProcessing/AudioProcessingStore_Tests.swift
  StreamVideoTests/Utils/AudioSession/AudioProcessing/Components/AudioCustomProcessingModule_Tests.swift
  StreamVideoTests/Utils/AudioSession/AudioProcessing/Namespace/Middleware/AudioFilterMiddleware_Tests.swift
  StreamVideoTests/Utils/AudioSession/AudioProcessing/Namespace/Middleware/CapturedChannelsMiddleware_Tests.swift
  StreamVideoTests/Utils/AudioSession/AudioProcessing/Namespace/Reducers/AudioProcessingStore_DefaultReducer_Tests.swift
Labels: bug, enhancement

#946 [CI] Get rid of mint package manager
  .github/actions/bootstrap/action.yml
  .github/actions/xcode-cache/action.yml
  .github/workflows/cron-checks.yml
  .github/workflows/smoke-checks.yml
  .github/workflows/sonar.yml
  Githubfile
  Mintfile
  Scripts/bootstrap.sh
  Scripts/generate.sh
  StreamVideo.xcodeproj/project.pbxproj
  fastlane/Fastfile
  lefthook.yml
Labels: CI/CD

#950 [Enhancement]Add unified session id to join request
  Sources/StreamVideo/WebRTC/v2/WebRTCJoinRequestFactory.swift
  StreamVideoTests/WebRTC/v2/WebRTCJoinRequestFactory_Tests.swift
Labels: enhancement

#951 [Fix]Stop permission prompts on call cleanup
  CHANGELOG.md
  Sources/StreamVideo/WebRTC/v2/WebRTCPermissionsAdapter.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift
Labels: enhancement

#952 Fix cron tests
  Sources/StreamVideo/Utils/IdleTimerAdapter/IdleTimerAdapter.swift
  StreamVideoTests/Utils/AudioSession/AudioRecorder/Namespace/Middleware/StreamCallAudioRecorder_ShouldRecordMiddlewareTests.swift
  StreamVideoTests/Utils/IdleTimerAdapter/IdleTimerAdapter_Tests.swift
  StreamVideoTests/WebRTC/v2/WebRTCAuthenticator_Tests.swift
Labels: CI/CD
