Repository GetStream/stream-video-swift, pull requests merged in 2025-01, with the labels that each got.

#628 [CallKit]Custom ringtone support
  CHANGELOG.md
  Sources/StreamVideo/CallKit/CallKitAdapter.swift
  Sources/StreamVideo/CallKit/CallKitService.swift
  StreamVideoTests/CallKit/CallKitServiceTests.swift
Labels: enhancement

#633 [Feature]Mute track on background when isMultitaskingCameraAccessSupported not supported
  CHANGELOG.md
  Sources/StreamVideo/Utils/StreamAppStateAdapter/StreamAppStateAdapter.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalVideoMediaAdapter.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/MediaAdapters/Utilities/ApplicationLifecycleVideoMuteAdapter.swift
  Sources/StreamVideo/WebRTC/v2/VideoCapturing/StreamVideoCapturer.swift
  Sources/StreamVideo/WebRTC/v2/VideoCapturing/StreamVideoCapturing.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoTests/Mock/MockStreamVideoCapturer.swift
  StreamVideoTests/WebRTC/SFU/Mocks/MockSignalServer.swift
  StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/Utilities/ApplicationLifecycleVideoMuteAdapter_Tests.swift
Labels: enhancement

#636 [Fix]CleanUp active videoCapturing and screenSharing sessions
  CHANGELOG.md
  Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift
  StreamVideoTests/WebRTC/v2/WebRTCStateAdapter_Tests.swift
Labels: bug

#635 [Fix]Cron checks failing on iOS 15
  StreamVideoTests/Mock/MockRTCRtpCodecCapability.swift
  StreamVideoTests/Mock/MockRTCRtpEncodingParameters.swift
Labels: bug

#638 [Fix]Legacy URL parsing pointing to Pronto
  DemoApp/Sources/Views/CallView/CallingView/SimpleCallingView.swift
Labels: bug, demo

#640 [Fix]Accepting call on another device will sync state with CallViewModel
  CHANGELOG.md
  Sources/StreamVideoSwiftUI/CallViewModel.swift
  StreamVideoSwiftUITests/CallViewModel_Tests.swift
Labels: bug

#641 [Enhancement]Handle video property on VoIP push notification
  DocumentationTests/DocumentationTests/DocumentationTests/06-advanced/03-callkit-integration.swift
  Sources/StreamVideo/Call.swift
  Sources/StreamVideo/CallKit/CallKitPushNotificationAdapter.swift
  Sources/StreamVideo/CallKit/CallKitService.swift
  Sources/StreamVideoSwiftUI/CallViewModel.swift
  Sources/StreamVideoSwiftUI/Models/CallEventsHandler.swift
  Sources/StreamVideoSwiftUI/Models/IncomingCall.swift
  StreamVideoSwiftUITests/CallingViews/IncomingCallView_Tests.swift
  StreamVideoTests/CallKit/CallKitPushNotificationAdapterTests.swift
  StreamVideoTests/CallKit/CallKitServiceTests.swift
  StreamVideoTests/Utilities/Mocks/MockCallKitService.swift
Labels: enhancement

#643 [Feature]Closed Captions support and docs
  DemoApp/Sources/Components/AppEnvironment.swift
  DemoApp/Sources/Components/DemoAppViewFactory.swift
  DemoApp/Sources/Controls/DemoMoreControls/DemoMoreControlListButtonView.swift
  DemoApp/Sources/ViewModifiers/MoreControls/DemoMoreControlsViewModifier.swift
  DemoApp/Sources/ViewModifiers/MoreControls/DemoTranscriptionAndClosedCaptionsButtonView.swift
  DemoApp/Sources/ViewModifiers/MoreControls/DemoTranscriptionButtonView.swift
  DemoApp/Sources/Views/ClosedCaptionsView/DemoClosedCaptionsView.swift
  DemoApp/Sources/Views/Login/DebugMenu.swift
  DocumentationTests/DocumentationTests/DocumentationTests.xcodeproj/project.pbxproj
  DocumentationTests/DocumentationTests/DocumentationTests/05-ui-cookbook/24-closed-captions.swift
  Sources/StreamVideo/Call.swift
  Sources/StreamVideo/CallState.swift
  Sources/StreamVideo/Utils/AyncStreamPublisher/AsyncStreamPublisher.swift
  Sources/StreamVideo/Utils/ClosedCaptionsAdapter/ClosedCaptionsAdapter.swift
  Sources/StreamVideo/Utils/OrderedCapacityQueue/OrderedCapacityQueue.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoTests/Call/Call_Tests.swift
  StreamVideoTests/Utils/AsyncStreamPublisherTests.swift
  StreamVideoTests/Utils/ClosedCaptionsAdapterTests.swift
  StreamVideoTests/Utils/OrderedCapacityQueueTests.swift
Labels: enhancement

#644 [Feature]Expose UserAvatar view slot
  CHANGELOG.md
  DemoApp/Sources/Components/DemoAppViewFactory.swift
  DemoApp/Sources/ViewModifiers/CallModifier/DemoCallModifier.swift
  DemoApp/Sources/Views/CallView/CallingView/DetailedCallingView.swift
  DemoApp/Sources/Views/Login/LoginView.swift
  Sources/StreamVideoSwiftUI/CallContainer.swift
  Sources/StreamVideoSwiftUI/CallView/CallParticipantImageView.swift
  Sources/StreamVideoSwiftUI/CallView/CallView.swift
  Sources/StreamVideoSwiftUI/CallView/LayoutComponents/HorizontalParticipantsListView.swift
  Sources/StreamVideoSwiftUI/CallView/LayoutComponents/SpotlightSpeakerView.swift
  Sources/StreamVideoSwiftUI/CallView/MinimizedCallView.swift
  Sources/StreamVideoSwiftUI/CallView/Participants/CallParticipantsInfoView.swift
  Sources/StreamVideoSwiftUI/CallView/Participants/InviteParticipantsView.swift
  Sources/StreamVideoSwiftUI/CallView/Participants/SelectedParticipantView.swift
  Sources/StreamVideoSwiftUI/CallView/ParticipantsFullScreenLayout.swift
  Sources/StreamVideoSwiftUI/CallView/ParticipantsGridLayout.swift
  Sources/StreamVideoSwiftUI/CallView/ParticipantsSpotlightLayout.swift
  Sources/StreamVideoSwiftUI/CallView/ReconnectionView.swift
  Sources/StreamVideoSwiftUI/CallView/VideoParticipantsView.swift
  Sources/StreamVideoSwiftUI/CallView/VideoRenderer/LocalVideoView.swift
  Sources/StreamVideoSwiftUI/CallView/ViewModifiers/ParticipantsListViewModifier.swift
  Sources/StreamVideoSwiftUI/CallingViews/CallConnectingView.swift
  Sources/StreamVideoSwiftUI/CallingViews/CallingGroupView.swift
  Sources/StreamVideoSwiftUI/CallingViews/CallingParticipantView.swift
  Sources/StreamVideoSwiftUI/CallingViews/IncomingCallView.swift
  Sources/StreamVideoSwiftUI/CallingViews/JoiningCallView.swift
  Sources/StreamVideoSwiftUI/CallingViews/OutgoingCallView.swift
  Sources/StreamVideoSwiftUI/CallingViews/PreJoiningView.swift
  Sources/StreamVideoSwiftUI/CallingViews/iOS13/IncomingCallView_iOS13.swift
  Sources/StreamVideoSwiftUI/CallingViews/iOS13/PreJoiningView_iOS13.swift
  Sources/StreamVideoSwiftUI/CallingViews/iOS13/VideoView_iOS13.swift
  Sources/StreamVideoSwiftUI/Livestreaming/LivestreamPlayer.swift
  Sources/StreamVideoSwiftUI/Utils/UserAvatar.swift
  Sources/StreamVideoSwiftUI/ViewFactory.swift
  StreamVideoSwiftUITests/CallingViews/CallingGroupView_Tests.swift
  StreamVideoSwiftUITests/CallingViews/CallingParticipantView_Tests.swift
Labels: enhancement

#645 [Enhancement]Improve Error logging
  DemoApp/Sources/Components/AppState.swift
  DemoApp/Sources/Components/MemoryLogDestination/OSLogDestination.swift
  DemoApp/Sources/Extensions/DemoApp+Sentry.swift
  Sources/StreamVideo/Errors/Errors.swift
  Sources/StreamVideo/OpenApi/generated/Models/APIError.swift
  Sources/StreamVideo/StreamVideo.swift
  Sources/StreamVideo/Utils/Logger/Logger.swift
  Sources/StreamVideo/Utils/ReflectiveStringConvertible/ReflectiveStringConvertible.swift
Labels: enhancement

#648 [Fix]Flakey tests
  .github/workflows/smoke-checks.yml
  StreamVideoTests/Utils/ClosedCaptionsAdapterTests.swift
Labels: bug

#649 [CI] Lock sonar scanner and mint versions and get rid of brew
  .github/actions/bootstrap/action.yml
  .github/workflows/cron-checks.yml
  .github/workflows/smoke-checks-llc.yml
  .github/workflows/smoke-checks.yml
  .gitignore
  Brewfile
  Brewfile.lock.json
  Githubfile
  Scripts/bootstrap.sh
  fastlane/Sonarfile
Labels: CI/CD

#653 [CI] Pass sonar installation variable for llc tests
  .github/workflows/smoke-checks-llc.yml
Labels: CI/CD
