Repository GetStream/stream-video-swift, pull requests merged in 2025-02, with the labels that each got.

#655 [CI] Unblock smoke checks
  .github/workflows/smoke-checks.yml
Labels: CI/CD

#654 [CI] Run sonar on push to develop
  .github/actions/python-cache/action.yml
  .github/workflows/smoke-checks-llc.yml
  .github/workflows/smoke-checks.yml
  .github/workflows/sonar.yml
  fastlane/Fastfile
  fastlane/Sonarfile
  requirements.txt
Labels: CI/CD

#657 [CI] Do not collect test coverage on build
  fastlane/Fastfile
Labels: CI/CD

#658 [Fix]Misleading error logs when leaving a call
  Sources/StreamVideo/WebSockets/Client/URLSessionWebSocketEngine.swift
Labels: bug, enhancement

#659 [CI] Remove unused sonar arguments
  fastlane/Sonarfile
Labels: CI/CD

#660 [Alignment]Allow member lookup from call when members in request are empty
  CHANGELOG.md
  Sources/StreamVideo/Call.swift
  Sources/StreamVideoSwiftUI/CallViewModel.swift
  Sources/StreamVideoSwiftUI/ViewFactory.swift
  StreamVideoSwiftUITests/CallingViews/OutgoingCallView_Tests.swift
  StreamVideoSwiftUITests/CallingViews/__Snapshots__/OutgoingCallView_Tests/test_outgoingCallView_snapshot.default-dark.png
  StreamVideoSwiftUITests/CallingViews/__Snapshots__/OutgoingCallView_Tests/test_outgoingCallView_snapshot.default-light.png
  SwiftUIDemoAppUITests/Tests/RingProcessTests.swift
Labels: bug

#661 [Alignment]Control the video/audio button visibility with the capabilities
  CHANGELOG.md
  Sources/StreamVideoSwiftUI/CallView/CallControls/Stateful/CallControlsView.swift
  StreamVideoSwiftUITests/CallView/CallControls/Stateful/CallControlsView_Tests.swift
  StreamVideoSwiftUITests/CallView/CallControls/Stateful/__Snapshots__/CallControlsView_Tests/test_callControlsView_activeCall_snapshot.default-dark.png
  StreamVideoSwiftUITests/CallView/CallControls/Stateful/__Snapshots__/CallControlsView_Tests/test_callControlsView_activeCall_snapshot.default-light.png
  StreamVideoSwiftUITests/CallView/CallControls/Stateful/__Snapshots__/CallControlsView_Tests/test_callControlsView_ringingCall_snapshot.default-dark.png
  StreamVideoSwiftUITests/CallView/CallControls/Stateful/__Snapshots__/CallControlsView_Tests/test_callControlsView_ringingCall_snapshot.default-light.png
  StreamVideoSwiftUITests/CallView/CallControls/Stateful/__Snapshots__/CallControlsView_Tests/test_callControlsView_withoutCapabilities_snapshot.default-dark.png
  StreamVideoSwiftUITests/CallView/CallControls/Stateful/__Snapshots__/CallControlsView_Tests/test_callControlsView_withoutCapabilities_snapshot.default-light.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ReconnectionView_Tests/test_reconnectionView_snapshot.default-dark.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ReconnectionView_Tests/test_reconnectionView_snapshot.default-light.png
  StreamVideoSwiftUITests/CallingViews/CallConnectingView_Tests.swift
  StreamVideoSwiftUITests/CallingViews/JoiningCallView_Tests.swift
  StreamVideoSwiftUITests/CallingViews/__Snapshots__/JoiningCallView_Tests/test_joiningCallView_snapshot.default-dark.png
  StreamVideoSwiftUITests/CallingViews/__Snapshots__/JoiningCallView_Tests/test_joiningCallView_snapshot.default-light.png
  StreamVideoUIKitTests/__Snapshots__/CallViewController_Tests/test_callViewController_outgoingSnapshot.default-dark.png
  StreamVideoUIKitTests/__Snapshots__/CallViewController_Tests/test_callViewController_outgoingSnapshot.default-light.png
Labels: bug, enhancement

#665 [CI] Snapshots recording improvement
  .github/workflows/record-snapshots.yml
  .github/workflows/smoke-checks.yml
  fastlane/Fastfile
Labels: CI/CD

#669 [CI] Optimize snapshots recording job
  .github/workflows/record-snapshots.yml
  .github/workflows/smoke-checks.yml
  fastlane/Fastfile
Labels: CI/CD

#651 [Enhancement]Small improvements in logs
  DemoApp/Sources/Components/AppState.swift
  DemoApp/Sources/Components/Authentication/AuthenticationProvider.swift
  DemoApp/Sources/Models/TokenResponse.swift
  Sources/StreamVideo/Utils/Logger/Logger.swift
  Sources/StreamVideo/WebSockets/Client/URLSessionWebSocketEngine.swift
Labels: enhancement

#666 [Fix]Control camera switch button with capabilities
  CHANGELOG.md
  Sources/StreamVideoSwiftUI/CallView/CallTopView.swift
  StreamVideoSwiftUITests/CallView/__Snapshots__/ReconnectionView_Tests/test_reconnectionView_snapshot.default-dark.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/ReconnectionView_Tests/test_reconnectionView_snapshot.default-light.png
  StreamVideoSwiftUITests/CallingViews/__Snapshots__/JoiningCallView_Tests/test_joiningCallView_snapshot.default-dark.png
  StreamVideoSwiftUITests/CallingViews/__Snapshots__/JoiningCallView_Tests/test_joiningCallView_snapshot.default-light.png
  StreamVideoUIKitTests/__Snapshots__/CallViewController_Tests/test_callViewController_outgoingSnapshot.default-dark.png
  StreamVideoUIKitTests/__Snapshots__/CallViewController_Tests/test_callViewController_outgoingSnapshot.default-light.png
Labels: enhancement

#672 Fix typo
  .github/workflows/smoke-checks.yml
Labels: CI/CD

#639 [Enhancement]Improve AudioSession management
  CHANGELOG.md
  DemoApp/Sources/Components/AppEnvironment.swift
  DemoApp/Sources/Views/CallView/CallingView/SimpleCallingView.swift
  DemoApp/Sources/Views/Login/DebugMenu.swift
  Sources/StreamVideo/Call.swift
  Sources/StreamVideo/Controllers/CallController.swift
  Sources/StreamVideo/Models/CallSettings.swift
  Sources/StreamVideo/Utils/AudioSession/AudioRecorder/StreamCallAudioRecorder.swift
  Sources/StreamVideo/Utils/AudioSession/AudioSessionConfiguration.swift
  Sources/StreamVideo/Utils/AudioSession/AudioSessionProtocol.swift
  Sources/StreamVideo/Utils/AudioSession/Extensions/AVAudioSession+RequestRecordPermission.swift
  Sources/StreamVideo/Utils/AudioSession/Extensions/AVAudioSession.CategoryOptions+Convenience.swift
  Sources/StreamVideo/Utils/AudioSession/Extensions/AVAudioSessionCategory+Convenience.swift
  Sources/StreamVideo/Utils/AudioSession/Extensions/AVAudioSessionCategoryOptions+Convenience.swift
  Sources/StreamVideo/Utils/AudioSession/Extensions/AVAudioSessionMode+Convenience.swift
  Sources/StreamVideo/Utils/AudioSession/Extensions/AVAudioSessionPortDescription+Convenience.swift
  Sources/StreamVideo/Utils/AudioSession/Extensions/AVAudioSessionPortOverride+Convenience.swift
  Sources/StreamVideo/Utils/AudioSession/Extensions/AVAudioSessionRouteChangeReason+Convenience.swift
  Sources/StreamVideo/Utils/AudioSession/Extensions/AVAudioSessionRouteDescription+Convenience.swift
  Sources/StreamVideo/Utils/AudioSession/Extensions/RTCAudioSessionConfiguration+Default.swift
  Sources/StreamVideo/Utils/AudioSession/Policies/AudioSessionPolicy.swift
  Sources/StreamVideo/Utils/AudioSession/Policies/DefaultAudioSessionPolicy.swift
  Sources/StreamVideo/Utils/AudioSession/Policies/OwnCapabilitiesAudioSessionPolicy.swift
  Sources/StreamVideo/Utils/AudioSession/RTCAudioSessionDelegatePublisher.swift
  Sources/StreamVideo/Utils/AudioSession/StreamAudioSession.swift
  Sources/StreamVideo/Utils/AudioSession/StreamAudioSessionAdapter.swift
  Sources/StreamVideo/Utils/AudioSession/StreamAudioSessionAdapterDelegate.swift
  Sources/StreamVideo/Utils/AudioSession/StreamRTCAudioSession.swift
  Sources/StreamVideo/Utils/CurrentDevice/CurrentDevice.swift
  Sources/StreamVideo/WebRTC/v2/Extensions/Foundation/Publisher+TaskSink.swift
  Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Joined.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCCoordinator.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoTests/Mock/MockAudioSession.swift
  StreamVideoTests/Mock/MockAudioSessionPolicy.swift
  StreamVideoTests/Mock/MockRTCPeerConnectionCoordinatorStack.swift
  StreamVideoTests/TestUtils/XCTAsyncUnwrap.swift
  StreamVideoTests/Utils/AudioSession/Extensions/AVAudioSessionCategoryOptions_Tests.swift
  StreamVideoTests/Utils/AudioSession/RTCAudioSessionDelegatePublisher_Tests.swift
  StreamVideoTests/Utils/AudioSession/StreamAudioSessionAdapter_Tests.swift
  StreamVideoTests/Utils/AudioSession/StreamAudioSession_Tests.swift
  StreamVideoTests/Utils/AudioSession/StreamRTCAudioSession_Tests.swift
  StreamVideoTests/Utils/StreamCallAudioRecorderTests.swift
  StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/AudioMediaAdapter_Tests.swift
  StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalAudioMediaAdapter_Tests.swift
  StreamVideoTests/WebRTC/v2/PeerConnection/RTCPeerConnectionCoordinator_Tests.swift
  StreamVideoTests/WebRTC/v2/WebRTCStateAdapter_Tests.swift
Labels: bug, enhancement

#682 [CI] Pass cron arg to unit tests
  .github/workflows/cron-checks.yml
Labels: CI/CD

#680 [Swift6 Migration]StreamVideoSwiftUITests
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoSwiftUITests/CallView/CallControls/Stateful/CallControlsView_Tests.swift
  StreamVideoSwiftUITests/CallView/CallControls/Stateless/StatelessAudioOutputIconView_Tests.swift
  StreamVideoSwiftUITests/CallView/CallControls/Stateless/StatelessHangUpIconView_Tests.swift
  StreamVideoSwiftUITests/CallView/CallControls/Stateless/StatelessMicrophoneIconView_Tests.swift
  StreamVideoSwiftUITests/CallView/CallControls/Stateless/StatelessParticipantsListButton_Tests.swift
  StreamVideoSwiftUITests/CallView/CallControls/Stateless/StatelessSpeakerIconView_Tests.swift
  StreamVideoSwiftUITests/CallView/CallControls/Stateless/StatelessToggleCameraIconView_Tests.swift
  StreamVideoSwiftUITests/CallView/CallControls/Stateless/StatelessVideoIconView_Tests.swift
  StreamVideoSwiftUITests/CallView/CallDurationView_Tests.swift
  StreamVideoSwiftUITests/CallView/ControlBadgeView_Tests.swift
  StreamVideoSwiftUITests/CallView/LayoutComponents/HorizontalParticipantsListView_Tests.swift
  StreamVideoSwiftUITests/CallView/LayoutComponents/SpotlightSpeakerView_Tests.swift
  StreamVideoSwiftUITests/CallView/ParticipantListButton_Tests.swift
  StreamVideoSwiftUITests/CallView/ParticipantsFullScreenLayout_Tests.swift
  StreamVideoSwiftUITests/CallView/ParticipantsGridLayout_Tests.swift
  StreamVideoSwiftUITests/CallView/ParticipantsSpotlightLayout_Tests.swift
  StreamVideoSwiftUITests/CallView/ReconnectionView_Tests.swift
  StreamVideoSwiftUITests/CallView/RecordingView_Tests.swift
  StreamVideoSwiftUITests/CallView/ScreenSharingView_Tests.swift
  StreamVideoSwiftUITests/CallView/VideoRenderer_Tests.swift
  StreamVideoSwiftUITests/CallView/VisibilityThresholdModifier_Tests.swift
  StreamVideoSwiftUITests/CallViewModel_Tests.swift
  StreamVideoSwiftUITests/CallingViews/CallConnectingView_Tests.swift
  StreamVideoSwiftUITests/CallingViews/CallingGroupView_Tests.swift
  StreamVideoSwiftUITests/CallingViews/CallingParticipantView_Tests.swift
  StreamVideoSwiftUITests/CallingViews/IncomingCallView_Tests.swift
  StreamVideoSwiftUITests/CallingViews/JoiningCallView_Tests.swift
  StreamVideoSwiftUITests/CallingViews/LobbyView_Tests.swift
  StreamVideoSwiftUITests/CallingViews/MicrophoneCheckView_Tests.swift
  StreamVideoSwiftUITests/CallingViews/MicrophoneChecker_Tests.swift
  StreamVideoSwiftUITests/CallingViews/OutgoingCallView_Tests.swift
  StreamVideoSwiftUITests/Livestreaming/LivestreamPlayer_Tests.swift
  StreamVideoSwiftUITests/StreamVideoUITestCase.swift
  StreamVideoSwiftUITests/Utils/AudioValuePercentageNormaliser_Tests.swift
  StreamVideoSwiftUITests/Utils/CallEventsHandler_Tests.swift
  StreamVideoSwiftUITests/Utils/CornerClipper_Tests.swift
  StreamVideoSwiftUITests/Utils/PictureInPicture/Mocks/MockStreamAVPictureInPictureViewControlling.swift
  StreamVideoSwiftUITests/Utils/PictureInPicture/StreamBufferTransformerTests.swift
  StreamVideoSwiftUITests/Utils/PictureInPicture/StreamPictureInPictureVideoRendererTests.swift
  StreamVideoSwiftUITests/Utils/PictureInPicture/WindowSizePolicy/StreamPictureInPictureAdaptiveWindowSizePolicy_Tests.swift
  StreamVideoSwiftUITests/Utils/PictureInPicture/WindowSizePolicy/StreamPictureInPictureFixedWindowSizePolicy_Tests.swift
  StreamVideoSwiftUITests/Utils/ReusePool_Tests.swift
  StreamVideoSwiftUITests/Utils/StreamMediaDurationFormatter_Tests.swift
  StreamVideoSwiftUITests/Utils/ToastView_Tests.swift
Labels: enhancement

#688 [CI] Route nightly checks fail reports to a dedicated Slack channel
  .github/workflows/cron-checks.yml
  .github/workflows/smoke-checks.yml
  .github/workflows/testflight.yml
  .github/workflows/update-copyright.yml
Labels: CI/CD

#681 [Swift6 Migration]StreamVideoUIKit
  Sources/StreamVideoUIKit/Utils/Animation.swift
  Sources/StreamVideoUIKit/Utils/UIView+Extensions.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoUIKitTests/CallViewController_Tests.swift
Labels: enhancement

#687 [Swift6 Migration]Fix CallKit crash
  DemoApp/Sources/Components/MemoryLogDestination/OSLogDestination.swift
  Sources/StreamVideo/CallKit/CallKitPushNotificationAdapter.swift
  Sources/StreamVideo/CallKit/CallKitService.swift
Labels: bug

#685 [Swift 6 Migration]Demo
  DemoApp/Sources/Components/DemoAppViewFactory.swift
  DemoApp/Sources/Extensions/CallStateResponseFields+Identifiable.swift
  DemoApp/Sources/Extensions/CallViewModel+Snapshot.swift
  DemoApp/Sources/Swift6Migration/CustomStringConvertible+Conformances.swift
  DemoApp/Sources/ViewModifiers/MoreControls/DemoTranscriptionAndClosedCaptionsButtonView.swift
  DemoApp/Sources/Views/CallView/CallingView/SimpleCallingView.swift
  StreamVideo.xcodeproj/project.pbxproj
  SwiftUIDemoAppUITests/Tests/RingProcessTests.swift
Labels: enhancement

#692 [Fix]Failing tests in Xcode 15 iOS 15.5
  StreamVideoTests/Utils/AudioSession/StreamRTCAudioSession_Tests.swift
Labels: bug, CI/CD

#686 [Fix]Align participants sorting with React
  DemoApp/Sources/Views/CallView/CallingView/DemoCallingViewModifier.swift
  DemoApp/Sources/Views/CallView/CallingView/SimpleCallingView.swift
  Sources/StreamVideo/CallState.swift
  Sources/StreamVideo/Utils/Sorting.swift
  Sources/StreamVideo/Utils/Sorting/Comparator.swift
  Sources/StreamVideo/Utils/Sorting/Participants.swift
  Sources/StreamVideo/Utils/Sorting/Presets.swift
  Sources/StreamVideo/Utils/Sorting/Sequence.swift
  Sources/StreamVideoSwiftUI/CallViewModel.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoTests/Utils/Sorting_Tests.swift
  fastlane/Fastfile
Labels: bug
