Repository GetStream/stream-video-swift, pull requests merged in 2025-05, with the labels that each got.

#770 [Enhancement]Implement proximity policies
  CHANGELOG.md
  DemoApp/Sources/Components/AppEnvironment.swift
  DemoApp/Sources/Views/CallView/CallingView/SimpleCallingView.swift
  DemoApp/Sources/Views/Login/DebugMenu.swift
  DocumentationTests/DocumentationTests/DocumentationTests.xcodeproj/project.pbxproj
  DocumentationTests/DocumentationTests/DocumentationTests/06-advanced/05-proximity-policies.swift
  Sources/StreamVideo/Call.swift
  Sources/StreamVideo/CallSettings/ProximityManager.swift
  Sources/StreamVideo/Utils/CurrentDevice/CurrentDevice.swift
  Sources/StreamVideo/Utils/Proximity/Monitor/ProximityMonitor.swift
  Sources/StreamVideo/Utils/Proximity/Policies/ProximityPolicy.swift
  Sources/StreamVideo/Utils/Proximity/Policies/SpeakerProximityPolicy.swift
  Sources/StreamVideo/Utils/Proximity/Policies/VideoProximityPolicy.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift
  Sources/StreamVideoSwiftUI/CallViewModel.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoTests/CallSettings/ProximityManager_Tests.swift
  StreamVideoTests/Mock/CurrentDevice+Dummy.swift
  StreamVideoTests/Mock/MockCallController.swift
  StreamVideoTests/Mock/MockProximityMonitor.swift
  StreamVideoTests/Mock/MockProximityPolicy.swift
  StreamVideoTests/Utils/Proximity/Monitor/ProximityMonitor_Tests.swift
  StreamVideoTests/Utils/Proximity/Policies/SpeakerProximityPolicy_Tests.swift
  StreamVideoTests/Utils/Proximity/Policies/VideoProximityPolicy_Tests.swift
  StreamVideoTests/WebRTC/v2/WebRTCStateAdapter_Tests.swift
Labels: enhancement

#796 [Fix]Picture-in-Picture trigger and lifecycle
  CHANGELOG.md
  DemoApp/Sources/Views/CallView/DemoSnapshotViewModel.swift
  Sources/StreamVideoSwiftUI/CallView/CallControls/Stateless/StatelessAudioOutputIconView.swift
  Sources/StreamVideoSwiftUI/CallView/CallControls/Stateless/StatelessMicrophoneIconView.swift
  Sources/StreamVideoSwiftUI/CallView/CallControls/Stateless/StatelessSpeakerIconView.swift
  Sources/StreamVideoSwiftUI/CallView/CallControls/Stateless/StatelessToggleCameraIconView.swift
  Sources/StreamVideoSwiftUI/CallView/CallControls/Stateless/StatelessVideoIconView.swift
  Sources/StreamVideoSwiftUI/CallViewModel.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/PictureInPictureController.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamPictureInPictureAdapter.swift
Labels: bug

#798 [Fix]Update OutgoingCallScreen from the ringingCall
  CHANGELOG.md
  Sources/StreamVideoSwiftUI/CallView/CallControls/Stateful/CallControlsView.swift
  Sources/StreamVideoSwiftUI/CallingViews/CallConnectingView.swift
  StreamVideoSwiftUITests/CallView/CallControls/Stateful/CallControlsView_Tests.swift
  StreamVideoSwiftUITests/CallingViews/CallConnectingView_Tests.swift
  StreamVideoSwiftUITests/CallingViews/OutgoingCallView_Tests.swift
Labels: bug, enhancement

#800 [Fix]Avoid updating callControls while in-call
  Sources/StreamVideoSwiftUI/CallView/CallControls/Stateful/CallControlsView.swift
Labels: bug

#802 [CI] Get rid of jazzy
  Gemfile
  Gemfile.lock
Labels: CI/CD

#803 [Fix]Enforce picture-in-picture stop on foreground
  CHANGELOG.md
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/PictureInPictureController.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/PictureInPictureEnforcedStopAdapter.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamPictureInPictureControllerProtocol.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoSwiftUITests/Utils/PictureInPicture/MockAVPictureInPictureController.swift
  StreamVideoSwiftUITests/Utils/PictureInPicture/PictureInPictureEnforcedStopAdapterTests.swift
Labels: bug, enhancement

#807 [Fix]CallKit AudioSession speaker sync
  CHANGELOG.md
  Sources/StreamVideo/Call.swift
  Sources/StreamVideo/CallKit/CallKitService.swift
  Sources/StreamVideo/Controllers/CallController.swift
  Sources/StreamVideo/Utils/AudioSession/Policies/DefaultAudioSessionPolicy.swift
  Sources/StreamVideo/Utils/AudioSession/Protocols/AVAudioSessionProtocol.swift
  Sources/StreamVideo/Utils/AudioSession/StreamAudioSession.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCCoordinator.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoTests/CallKit/CallKitServiceTests.swift
  StreamVideoTests/Mock/MockAVAudioSession.swift
  StreamVideoTests/Mock/MockCall.swift
  StreamVideoTests/Utils/AudioSession/Policies/DefaultAudioSessionPolicyTests.swift
  StreamVideoTests/Utils/AudioSession/StreamAudioSession_Tests.swift
Labels: bug, enhancement

#808 [Fix]CallSettings during reconnection
  CHANGELOG.md
  Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift
  StreamVideoTests/WebRTC/v2/WebRTCStateAdapter_Tests.swift
Labels: bug

#814 [Fix]Break StreamVideo memory leak
  CHANGELOG.md
  Sources/StreamVideo/WebRTC/AudioFilter/Filters/NoiseCancellationFilter.swift
Labels: bug

#817 [Fix]Add team to the CallViewModel and CallViewController
  CHANGELOG.md
  Sources/StreamVideoSwiftUI/CallViewModel.swift
  Sources/StreamVideoUIKit/CallViewController.swift
Labels: enhancement

#813 [Fix]MicrophoneChecker occasional crash
  CHANGELOG.md
  Sources/StreamVideo/WebRTC/v2/Extensions/Foundation/Publisher+TaskSink.swift
  Sources/StreamVideoSwiftUI/CallingViews/MicrophoneChecker.swift
  StreamVideoSwiftUITests/CallingViews/MicrophoneChecker_Tests.swift
Labels: bug

#819 [Fix]Initial CallSetttings and external audio output
  CHANGELOG.md
  Sources/StreamVideo/WebRTC/v2/WebRTCAuthenticator.swift
Labels: enhancement

#820 [Enhancement]CallKit will report ring timeout as reason when appropriate
  CHANGELOG.md
  Sources/StreamVideo/CallKit/CallKitService.swift
  Sources/StreamVideo/Utils/RejectionReasonProvider/RejectionReasonProvider.swift
  StreamVideoSwiftUITests/CallingViews/MicrophoneChecker_Tests.swift
  StreamVideoTests/CallKit/CallKitServiceTests.swift
  StreamVideoTests/Mock/MockCall.swift
  StreamVideoTests/Utils/RejectionReasonProvider/RejectionReasonProvider_Tests.swift
Labels: enhancement

#824 [Performance]Implement timers storage
  Sources/StreamVideo/CallKit/CallKitService.swift
  Sources/StreamVideo/CallState.swift
  Sources/StreamVideo/StreamVideo.swift
  Sources/StreamVideo/Utils/AudioSession/AudioRecorder/StreamCallAudioRecorder.swift
  Sources/StreamVideo/Utils/OrderedCapacityQueue/OrderedCapacityQueue.swift
  Sources/StreamVideo/Utils/ScreenPropertiesAdapter/ScreenPropertiesAdapter.swift
  Sources/StreamVideo/Utils/Timers/Timer.swift
  Sources/StreamVideo/Utils/Timers/TimerStorage.swift
  Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Disconnected.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCStatsReporter.swift
  Sources/StreamVideoSwiftUI/Livestreaming/LivestreamPlayer.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/PictureInPictureEnforcedStopAdapter.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/PictureInPictureTrackStateAdapter.swift
  StreamVideo.xcodeproj/project.pbxproj
Labels: enhancement

#826 [Performance]Break async stream memory leaks
  DemoApp/Sources/Components/Reactions/ReactionsAdapter.swift
  Sources/StreamVideo/Call.swift
  Sources/StreamVideo/CallKit/CallKitService.swift
  Sources/StreamVideo/Controllers/CallsController.swift
  Sources/StreamVideo/StreamVideo.swift
  Sources/StreamVideo/Utils/ClosedCaptionsAdapter/ClosedCaptionsAdapter.swift
  Sources/StreamVideo/WebSockets/Events/WSEventsMiddleware.swift
  Sources/StreamVideoSwiftUI/CallViewModel.swift
  StreamVideoSwiftUITests/CallingViews/LobbyViewModel_Tests.swift
  StreamVideoTests/Call/Call_Tests.swift
  StreamVideoTests/Controllers/CallController_Tests.swift
  StreamVideoTests/StreamVideo_Tests.swift
Labels: enhancement
