Repository GetStream/stream-video-swift, pull requests merged in 2025-06, with the labels that each got.

#832 [CI] Switch macos version to keep the support of Xcode 15.4
  .github/workflows/cron-checks.yml
  .github/workflows/smoke-checks.yml
Labels: CI/CD

#835 [CI] Bump snapshot version after every release
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: CI/CD

#841 [Fix]Respect dashboard callSettings for outgoing calls when no local settings provided
  CHANGELOG.md
  Sources/StreamVideoSwiftUI/CallViewModel.swift
  StreamVideoSwiftUITests/CallViewModel_Tests.swift
  StreamVideoTests/Mock/MockCall.swift
  StreamVideoTests/Mock/MockStreamVideo.swift
Labels: bug

#842 [CI] Automate the release step of merging the main branch to develop
  .github/workflows/merge-main-to-develop.yml
  .github/workflows/release-publish.yml
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: CI/CD

#853 [Enhancement]Remove IdleTimer handling from UI
  CHANGELOG.md
  Sources/StreamVideo/StreamVideo.swift
  Sources/StreamVideo/Utils/IdleTimerAdapter/IdleTimerAdapter.swift
  Sources/StreamVideoSwiftUI/CallView/CallView.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoTests/Utils/IdleTimerAdapter/IdleTimerAdapter_Tests.swift
Labels: enhancement

#856 [CI] Update checkout fetch on smoke checks
  .github/workflows/smoke-checks.yml
Labels: CI/CD

#857 [CI] Check out the original branch after public interface validation
  fastlane/Fastfile
Labels: CI/CD

#864 [Fix]Reconnection loop when trying to join an ended call without required permissions
  CHANGELOG.md
  Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Disconnected.swift
  StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_DisconnectedStageTests.swift
Labels: bug

#870 Fix synchronisation issues
  CHANGELOG.md
  DemoApp/Sources/Components/Chat/DemoChatViewModel.swift
  DemoApp/Sources/Views/CallView/CallingView/SimpleCallingView.swift
  Sources/StreamVideo/Controllers/CallController.swift
  Sources/StreamVideo/StreamVideo.swift
  Sources/StreamVideo/Utils/AudioSession/AudioRecorder/StreamCallAudioRecorder.swift
  Sources/StreamVideo/Utils/AudioSession/StreamAudioSession.swift
  Sources/StreamVideo/Utils/AudioSession/StreamRTCAudioSession.swift
  Sources/StreamVideo/Utils/CallCache/CallCache.swift
  Sources/StreamVideo/Utils/Proximity/Policies/SpeakerProximityPolicy.swift
  Sources/StreamVideo/Utils/Proximity/Policies/VideoProximityPolicy.swift
  Sources/StreamVideo/Utils/SerialActorQueue/OperationQueue+TaskOperations.swift
  Sources/StreamVideo/WebRTC/AudioFilter/Filters/NoiseCancellationFilter.swift
  Sources/StreamVideo/WebRTC/VideoCapturing/StreamVideoCaptureHandler.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalAudioMediaAdapter.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalScreenShareMediaAdapter.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalVideoMediaAdapter.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/RTCPeerConnectionCoordinator.swift
  Sources/StreamVideo/WebRTC/v2/SFU/SFUEventAdapter.swift
  Sources/StreamVideo/WebRTC/v2/UpdateSubscriptions/WebRTCUpdateSubscriptionsAdapter.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift
  Sources/StreamVideo/WebSockets/Client/URLSessionWebSocketEngine.swift
  Sources/StreamVideo/WebSockets/Events/WSEventsMiddleware.swift
  Sources/StreamVideoSwiftUI/CallViewModel.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/PictureInPictureStore.swift
  StreamVideoTests/Mock/MockStreamVideo.swift
  StreamVideoTests/WebRTC/v2/PeerConnection/RTCPeerConnectionCoordinator_Tests.swift
  StreamVideoTests/WebRTC/v2/WebRTCCoorindator_Tests.swift
Labels: bug

#873 [Fix]Remove TimerStorage
  .swiftlint.yml
  Sources/StreamVideo/CallKit/CallKitService.swift
  Sources/StreamVideo/CallState.swift
  Sources/StreamVideo/StreamVideo.swift
  Sources/StreamVideo/Utils/AudioSession/AudioRecorder/StreamCallAudioRecorder.swift
  Sources/StreamVideo/Utils/OrderedCapacityQueue/OrderedCapacityQueue.swift
  Sources/StreamVideo/Utils/Timers/TimerStorage.swift
  Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Disconnected.swift
  Sources/StreamVideo/WebRTC/v2/Stats/Collector/WebRTCStatsCollector.swift
  Sources/StreamVideo/WebRTC/v2/Stats/Reporter/WebRTCStatsReporter.swift
  Sources/StreamVideo/WebRTC/v2/Stats/WebRTCStatsAdapter.swift
  Sources/StreamVideoSwiftUI/CallViewModel.swift
  Sources/StreamVideoSwiftUI/Livestreaming/LivestreamPlayer.swift
  Sources/StreamVideoSwiftUI/Utils/ParticipantEventResetAdapter/ParticipantEventResetAdapter.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/PictureInPictureEnforcedStopAdapter.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/PictureInPictureTrackStateAdapter.swift
  StreamVideo.xcodeproj/project.pbxproj
Labels: enhancement

#877 [Performance]Timers improvements
  CHANGELOG.md
  Sources/StreamVideo/CallKit/CallKitService.swift
  Sources/StreamVideo/CallState.swift
  Sources/StreamVideo/StreamVideo.swift
  Sources/StreamVideo/Utils/AudioSession/AudioRecorder/StreamCallAudioRecorder.swift
  Sources/StreamVideo/Utils/OrderedCapacityQueue/OrderedCapacityQueue.swift
  Sources/StreamVideo/Utils/ScreenPropertiesAdapter/ScreenPropertiesAdapter.swift
  Sources/StreamVideo/Utils/Timers/DefaultTimer.swift
  Sources/StreamVideo/Utils/Timers/Extensions/DispatchWorkItem+TimerControl.swift
  Sources/StreamVideo/Utils/Timers/Protocol/Timer.swift
  Sources/StreamVideo/Utils/Timers/Protocol/TimerControl.swift
  Sources/StreamVideo/Utils/Timers/Repeating/RepeatingTimer.swift
  Sources/StreamVideo/Utils/Timers/Repeating/RepeatingTimerControl.swift
  Sources/StreamVideo/Utils/Timers/Timer.swift
  Sources/StreamVideo/Utils/Timers/TimerPublisher/TimerPublisher.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/Adapters/ICEConnectionStateAdapter.swift
  Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Disconnected.swift
  Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Joined.swift
  Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Stage.swift
  Sources/StreamVideo/WebRTC/v2/Stats/Collector/WebRTCStatsCollector.swift
  Sources/StreamVideo/WebRTC/v2/Stats/Reporter/WebRTCStatsReporter.swift
  Sources/StreamVideo/WebRTC/v2/Stats/WebRTCStatsAdapter.swift
  Sources/StreamVideoSwiftUI/Utils/ParticipantEventResetAdapter/ParticipantEventResetAdapter.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/PictureInPictureEnforcedStopAdapter.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/PictureInPictureTrackStateAdapter.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoTests/Controllers/CallController_Tests.swift
  StreamVideoTests/TestUtils/VirtualTime/VirtualTime.swift
  StreamVideoTests/TestUtils/VirtualTime/VirtualTimer.swift
  StreamVideoTests/Utils/Timers/TimerPublisher_Tests.swift
Labels: enhancement
