Repository GetStream/stream-video-swift, pull requests merged in 2025-04, with the labels that each got.

#739 [Fix]E2E main thread access issue
  SwiftUIDemoAppUITests/Robots/UserRobot+Asserts.swift
  SwiftUIDemoAppUITests/Robots/UserRobot.swift
  SwiftUIDemoAppUITests/Tests/CallViewsTests.swift
Labels: bug, CI/CD

#740 [CI] Remove concurrency module shadow on xcframeworks
  fastlane/Fastfile
Labels: CI/CD

#745 [Fix]CallSettings not respected when `create=false`
  CHANGELOG.md
  Sources/StreamVideo/WebRTC/v2/WebRTCAuthenticator.swift
  StreamVideoTests/WebRTC/v2/WebRTCAuthenticator_Tests.swift
Labels: bug

#748 Update webrtc version to 125.6422.066
  CHANGELOG.md
  Package.swift
  StreamVideo.xcodeproj/project.pbxproj
Labels: enhancement

#750 [CI] Delete fastlane scan logs
  .github/workflows/smoke-checks.yml
Labels: CI/CD

#752 [Fix]CallKit end call wasn't completing successfully
  Sources/StreamVideo/CallKit/CallKitService.swift
Labels: bug

#751 [Enhancement]Allow resetting local call settings
  CHANGELOG.md
  Sources/StreamVideoSwiftUI/CallViewModel.swift
  StreamVideoSwiftUITests/CallViewModel_Tests.swift
Labels: enhancement

#755 [Fix]Linter error
  StreamVideoSwiftUITests/CallViewModel_Tests.swift
Labels: bug, CI/CD

#757 [Fix]Resource loading when used via SPM
  CHANGELOG.md
  DocumentationTests/DocumentationTests/DocumentationTests/06-advanced/03-callkit-integration.swift
  Package.swift
  Sources/StreamVideoSwiftUI/Resource.swift
  Sources/StreamVideoSwiftUI/Sounds.swift
  Sources/StreamVideoSwiftUI/Utils/CallSoundsPlayer.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoSwiftUITests/Utils/Resource_Tests.swift
Labels: bug

#758 [Fix]Respect dashboard audio settings
  CHANGELOG.md
  Sources/StreamVideo/CallSettings/SpeakerManager.swift
  Sources/StreamVideo/CallState.swift
  Sources/StreamVideo/Models/CallSettings.swift
  Sources/StreamVideo/Models/Extensions/CallSettingsResponse+SettingsPriority.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCAuthenticator.swift
  Sources/StreamVideoSwiftUI/CallViewModel.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoSwiftUITests/CallView/CallControls/Stateless/StatelessAudioOutputIconView_Tests.swift
  StreamVideoTests/Models/CallSettingsResponse+SettingsPriorityTests.swift
  StreamVideoTests/WebRTC/v2/WebRTCAuthenticator_Tests.swift
Labels: bug

#762 [Fix]AudioSession mode misconfiguration for audio-only calls
  CHANGELOG.md
  Sources/StreamVideo/CallKit/CallKitPushNotificationAdapter.swift
  Sources/StreamVideo/CallKit/CallKitService.swift
  Sources/StreamVideo/Models/CallSettings.swift
  Sources/StreamVideo/Utils/AudioSession/Policies/DefaultAudioSessionPolicy.swift
  Sources/StreamVideo/Utils/AudioSession/Policies/OwnCapabilitiesAudioSessionPolicy.swift
  Sources/StreamVideo/Utils/CurrentDevice/CurrentDevice.swift
  Sources/StreamVideo/Utils/Logger/Logger.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoSwiftUITests/CallView/CallControls/Stateful/__Snapshots__/CallControlsView_Tests/test_callControlsView_activeCall_snapshot.default-dark.png
  StreamVideoSwiftUITests/CallView/CallControls/Stateful/__Snapshots__/CallControlsView_Tests/test_callControlsView_activeCall_snapshot.default-light.png
  StreamVideoSwiftUITests/CallView/CallControls/Stateful/__Snapshots__/CallControlsView_Tests/test_callControlsView_ringingCall_snapshot.default-dark.png
  StreamVideoSwiftUITests/CallView/CallControls/Stateful/__Snapshots__/CallControlsView_Tests/test_callControlsView_ringingCall_snapshot.default-light.png
  StreamVideoSwiftUITests/CallView/CallControls/Stateless/__Snapshots__/StatelessVideoIconView_Tests/test_appearance_videoOn_wasConfiguredCorrectly.default-dark.png
  StreamVideoSwiftUITests/CallView/CallControls/Stateless/__Snapshots__/StatelessVideoIconView_Tests/test_appearance_videoOn_wasConfiguredCorrectly.default-light.png
  StreamVideoSwiftUITests/CallViewModel_Tests.swift
  StreamVideoSwiftUITests/CallingViews/__Snapshots__/CallConnectingView_Tests/test_callConnectingView_snapshot.default-dark.png
  StreamVideoSwiftUITests/CallingViews/__Snapshots__/CallConnectingView_Tests/test_callConnectingView_snapshot.default-light.png
  StreamVideoSwiftUITests/CallingViews/__Snapshots__/LobbyView_Tests/test_lobbyView_snapshot.default-dark-with_0_participants.png
  StreamVideoSwiftUITests/CallingViews/__Snapshots__/LobbyView_Tests/test_lobbyView_snapshot.default-dark-with_1_participants.png
  StreamVideoSwiftUITests/CallingViews/__Snapshots__/LobbyView_Tests/test_lobbyView_snapshot.default-dark-with_2_participants.png
  StreamVideoSwiftUITests/CallingViews/__Snapshots__/LobbyView_Tests/test_lobbyView_snapshot.default-light-with_0_participants.png
  StreamVideoSwiftUITests/CallingViews/__Snapshots__/LobbyView_Tests/test_lobbyView_snapshot.default-light-with_1_participants.png
  StreamVideoSwiftUITests/CallingViews/__Snapshots__/LobbyView_Tests/test_lobbyView_snapshot.default-light-with_2_participants.png
  StreamVideoSwiftUITests/CallingViews/__Snapshots__/OutgoingCallView_Tests/test_outgoingCallView_snapshot.default-dark.png
  StreamVideoSwiftUITests/CallingViews/__Snapshots__/OutgoingCallView_Tests/test_outgoingCallView_snapshot.default-light.png
  StreamVideoTests/Utils/AudioSession/Policies/DefaultAudioSessionPolicyTests.swift
  StreamVideoTests/Utils/AudioSession/Policies/OwnCapabilitiesAudioSessionPolicyTests.swift
Labels: bug

#760 [WIP] Update WebRTC version to enable dSYMs
  CHANGELOG.md
  Package.swift
  StreamVideo-XCFramework.podspec
  StreamVideo.podspec
  StreamVideo.xcodeproj/project.pbxproj
Labels: CI/CD

#765 [CI] Install an older ipsw version
  .github/actions/setup-ios-runtime/action.yml
  .github/workflows/cron-checks.yml
  Githubfile
  Scripts/bootstrap.sh
Labels: CI/CD

#772 [Fix]Mute state misalignment
  CHANGELOG.md
  Sources/StreamVideoSwiftUI/CallViewModel.swift
Labels: bug

#773 [Fix]Picture-in-Picture local participant not mirrored
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/PictureInPictureVideoParticipantView.swift
Labels: bug

#747 [Fix]Reorganize Call state-machine and its transitions
  CHANGELOG.md
  Sources/StreamVideo/Call.swift
  Sources/StreamVideo/CallConfiguration.swift
  Sources/StreamVideo/CallStateMachine/CallState+Machine.swift
  Sources/StreamVideo/CallStateMachine/Stages/Call+AcceptedStage.swift
  Sources/StreamVideo/CallStateMachine/Stages/Call+AcceptingStage.swift
  Sources/StreamVideo/CallStateMachine/Stages/Call+Error.swift
  Sources/StreamVideo/CallStateMachine/Stages/Call+Idle.swift
  Sources/StreamVideo/CallStateMachine/Stages/Call+JoinedStage.swift
  Sources/StreamVideo/CallStateMachine/Stages/Call+JoiningStage.swift
  Sources/StreamVideo/CallStateMachine/Stages/Call+RejectedStage.swift
  Sources/StreamVideo/CallStateMachine/Stages/Call+RejectingStage.swift
  Sources/StreamVideo/CallStateMachine/Stages/Call+Stage.swift
  Sources/StreamVideo/Controllers/CallController.swift
  Sources/StreamVideo/Models/CoordinatorModels.swift
  Sources/StreamVideo/Utils/SerialActor/SerialActor.swift
  Sources/StreamVideo/Utils/SerialActor/SerialActorQueue.swift
  Sources/StreamVideo/Utils/StateMachine/CallStateMachine/Stages/StreamCallStateMachine+AcceptedStage.swift
  Sources/StreamVideo/Utils/StateMachine/CallStateMachine/Stages/StreamCallStateMachine+AcceptingStage.swift
  Sources/StreamVideo/Utils/StateMachine/CallStateMachine/Stages/StreamCallStateMachine+IdleStage.swift
  Sources/StreamVideo/Utils/StateMachine/CallStateMachine/Stages/StreamCallStateMachine+JoiningStage.swift
  Sources/StreamVideo/Utils/StateMachine/CallStateMachine/Stages/StreamCallStateMachine+RejectedStage.swift
  Sources/StreamVideo/Utils/StateMachine/CallStateMachine/Stages/StreamCallStateMachine+RejectingStage.swift
  Sources/StreamVideo/Utils/StateMachine/CallStateMachine/Stages/StreamCallStateMachine+Stage.swift
  Sources/StreamVideo/Utils/StateMachine/CallStateMachine/StreamCallStateMachine.swift
  Sources/StreamVideo/Utils/StateMachine/StreamStateMachine.swift
  Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Error.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoTests/Call/Call_Tests.swift
  StreamVideoTests/CallStateMachine/CallConfigurationTests.swift
  StreamVideoTests/CallStateMachine/CallStateMachine/CallStateMachine_Tests.swift
  StreamVideoTests/CallStateMachine/CallStateMachine/Stages/CallStateMachine_AcceptedStateTests.swift
  StreamVideoTests/CallStateMachine/CallStateMachine/Stages/CallStateMachine_AcceptingStageTests.swift
  StreamVideoTests/CallStateMachine/CallStateMachine/Stages/CallStateMachine_ErrorStageTests.swift
  StreamVideoTests/CallStateMachine/CallStateMachine/Stages/CallStateMachine_IdleStageTests.swift
  StreamVideoTests/CallStateMachine/CallStateMachine/Stages/CallStateMachine_JoinedStageTests.swift
  StreamVideoTests/CallStateMachine/CallStateMachine/Stages/CallStateMachine_JoiningStageTests.swift
  StreamVideoTests/CallStateMachine/CallStateMachine/Stages/CallStateMachine_RejectedStageTests.swift
  StreamVideoTests/CallStateMachine/CallStateMachine/Stages/CallStateMachine_RejectingStageTests.swift
  StreamVideoTests/CallStateMachine/Publisher_NextTests.swift
  StreamVideoTests/CallStateMachine/StreamStateMachine_Tests.swift
  StreamVideoTests/Mock/MockCallController.swift
  StreamVideoTests/Mock/MockDefaultAPI.swift
  StreamVideoTests/Utils/SerialActor/SerialActorQueue_Tests.swift
  StreamVideoTests/Utils/SerialActor/SerialActor_Tests.swift
  StreamVideoTests/Utils/StateMachine/CallStateMachine/Stages/StreamCallStateMachineStageAcceptingStage_Tests.swift
  StreamVideoTests/Utils/StateMachine/CallStateMachine/Stages/StreamCallStateMachineStageErrorStage_Tests.swift
  StreamVideoTests/Utils/StateMachine/CallStateMachine/Stages/StreamCallStateMachineStageJoiningStage_Tests.swift
  StreamVideoTests/Utils/StateMachine/CallStateMachine/Stages/StreamCallStateMachineStageRejectingStage_Tests.swift
  StreamVideoTests/Utils/StateMachine/CallStateMachine/StreamCallStateMachine_Tests.swift
Labels: bug

#775 [CI] Bump Xcode version
  .github/workflows/cron-checks.yml
  .github/workflows/smoke-checks.yml
  Gemfile
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: CI/CD

#774 [Fix]Ensure PiP deactivation when leaving the call
  Sources/StreamVideoSwiftUI/CallViewModel.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/PictureInPictureContentProvider.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/PictureInPictureController.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/PictureInPictureStore.swift
  StreamVideoSwiftUITests/Utils/PictureInPicture/PictureInPictureContentProviderTests.swift
  StreamVideoSwiftUITests/Utils/PictureInPicture/PictureInPictureContentViewTests.swift
  StreamVideoSwiftUITests/Utils/PictureInPicture/PictureInPictureStoreTests.swift
  StreamVideoSwiftUITests/Utils/PictureInPicture/PictureInPictureVideoCallViewControllerTests.swift
  StreamVideoSwiftUITests/Utils/PictureInPicture/StreamPictureInPictureTrackStateAdapterTests.swift
  StreamVideoTests/IntegrationTests/CallCRUDTests.swift
Labels: bug

#771 [Fix]AudioSession disabling speaker when video is off
  CHANGELOG.md
  Sources/StreamVideo/Models/CallSettings.swift
  Sources/StreamVideo/Utils/AudioSession/Extensions/AVAudioSession.CategoryOptions+Convenience.swift
  Sources/StreamVideo/Utils/AudioSession/Policies/DefaultAudioSessionPolicy.swift
  Sources/StreamVideo/Utils/AudioSession/Policies/OwnCapabilitiesAudioSessionPolicy.swift
  Sources/StreamVideo/Utils/StreamAppStateAdapter/StreamAppStateAdapter.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/MediaAdapters/Utilities/ApplicationLifecycleVideoMuteAdapter.swift
  Sources/StreamVideoSwiftUI/CallViewModel.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/PictureInPictureController.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoSwiftUITests/Utils/StreamAppStateAdapter/StreamAppStateAdapter_Tests.swift
  StreamVideoTests/Mock/MockAppStateAdapter.swift
  StreamVideoTests/Utils/AudioSession/Extensions/AVAudioSessionCategoryOptions_Tests.swift
  StreamVideoTests/Utils/AudioSession/Policies/DefaultAudioSessionPolicyTests.swift
  StreamVideoTests/Utils/AudioSession/Policies/OwnCapabilitiesAudioSessionPolicyTests.swift
Labels: bug

#780 Fix swiftlint issues
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoSwiftUITests/Utils/PictureInPicture/StreamPictureInPictureTrackStateAdapterTests.swift
Labels: CI/CD

#784 [Fix]Remove unnecessary operation during tests and fix flakiness
  Sources/StreamVideo/Call.swift
  Sources/StreamVideo/StreamVideo.swift
  Sources/StreamVideo/Utils/StateMachine/Publisher+NextValue.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoTests/Call/Call_Tests.swift
  StreamVideoTests/IntegrationTests/CallCRUDTests.swift
  StreamVideoTests/IntegrationTests/IntegrationTest.swift
  StreamVideoTests/Mock/MockStreamVideo.swift
  StreamVideoTests/Mock/StreamVideo_Mock.swift
Labels: bug, CI/CD

#785 [Enhancement]Allow deeplinks from new domain
  DemoApp/Sources/Components/AppEnvironment.swift
  DemoApp/Sources/Components/Authentication/AuthenticationProvider.swift
  DemoApp/Sources/Components/Deeplinks/DeeplinkAdapter.swift
  DemoApp/Sources/ViewModifiers/CallModifier/DemoCallModifier.swift
  DemoApp/Sources/Views/CallTopView/DemoCallTopView.swift
  DemoApp/Sources/Views/CallView/CallingView/DemoCallingViewModifier.swift
  DemoApp/Sources/Views/CallView/CallingView/SimpleCallingView.swift
  DemoApp/Sources/Views/CallView/DemoVideoViewOverlay.swift
  StreamVideo.xcodeproj/project.pbxproj
Labels: enhancement

#787 [CI] Update TestFlight app version on manual uploading
  fastlane/Fastfile
Labels: CI/CD

#792 [Fix]Ringing flow issues
  CHANGELOG.md
  Sources/StreamVideoSwiftUI/CallViewModel.swift
Labels: bug

#794 [Fix]Picture-in-Picture store thread access
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/PictureInPictureStore.swift
Labels: bug
