Repository GetStream/stream-video-swift, pull requests merged in 2025-03, with the labels that each got.

#693 [Enhancement]Update order for CallKit documentation tests
  DocumentationTests/DocumentationTests/DocumentationTests/06-advanced/03-callkit-integration.swift
  DocumentationTests/DocumentationTests/DocumentationTests/GloballyUsedVariables.swift
Labels: documentation, enhancement

#694 [CI] Bump Xcode, macOS and iOS versions
  .github/workflows/cron-checks.yml
  .github/workflows/release-merge.yml
  .github/workflows/release-publish.yml
  .github/workflows/release-start.yml
  .github/workflows/sdk-size-metrics.yml
  .github/workflows/smoke-checks.yml
  .github/workflows/testflight.yml
  .github/workflows/update-copyright.yml
  fastlane/Fastfile
Labels: CI/CD

#698 [CI] Bump SwiftProtobuf version in podspec
  StreamVideo-XCFramework.podspec
  StreamVideo.podspec
Labels: CI/CD

#700 [Fix]SerialQueue processing for MicrophoneChecker operations
  CHANGELOG.md
  Sources/StreamVideoSwiftUI/CallingViews/MicrophoneChecker.swift
Labels: bug

#699 [Enhancement]Camera access request is driven by Plist usage
  DemoApp/Sources/Views/CallView/CallingView/DetailedCallingView.swift
  Sources/StreamVideo/Models/CallSettings.swift
  Sources/StreamVideo/Utils/BundleExtensions.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalVideoMediaAdapter.swift
  Sources/StreamVideoSwiftUI/Utils/Camera.swift
  StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalVideoMediaAdapter_Tests.swift
Labels: enhancement

#695 [Enhancement]Unclutter released demo app
  DemoApp/Sources/Controls/DemoControls.swift
  DemoApp/Sources/Controls/DemoMoreControls/DemoMoreControlListButtonView.swift
  DemoApp/Sources/ViewModifiers/MoreControls/DemoMoreControlsViewModifier.swift
  DemoApp/Sources/Views/WaitingLocalUserView/DemoWaitingLocalUserView.swift
  DemoApp/Sources/Views/WaitingLocalUserView/QRCodeView.swift
  Sources/StreamVideo/Utils/CurrentDevice/CurrentDevice.swift
  Sources/StreamVideoSwiftUI/CallView/CallDurationView.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoSwiftUITests/CallView/__Snapshots__/CallDurationView_Tests/test_callDurationView_durationIsGreaterThanZero_viewWasConfiguredCorrectly.default-dark.png
  StreamVideoSwiftUITests/CallView/__Snapshots__/CallDurationView_Tests/test_callDurationView_durationIsGreaterThanZero_viewWasConfiguredCorrectly.default-light.png
Labels: enhancement

#705 [Fix]NoiseCancellation activating step
  CHANGELOG.md
  DemoApp/Sources/ViewModifiers/MoreControls/DemoNoiseCancellationButtonView.swift
  Sources/StreamVideo/WebRTC/AudioFilter/Filters/NoiseCancellationFilter.swift
Labels: bug

#706 [Fix]Unnecessary SetPublisher requests
  .gitignore
  CHANGELOG.md
  DemoApp/Sources/Views/CallView/CallingView/DetailedCallingView.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalAudioMediaAdapter.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalVideoMediaAdapter.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift
  Sources/StreamVideoSwiftUI/Livestreaming/LivestreamPlayer.swift
  StreamVideoTests/Utils/StateMachine/StreamStateMachine_Tests.swift
  StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalAudioMediaAdapter_Tests.swift
  StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalVideoMediaAdapter_Tests.swift
Labels: bug

#708 Fix/back camera appears flipped
  CHANGELOG.md
  Sources/StreamVideoSwiftUI/CallView/VideoParticipantsView.swift
Labels: bug

#710 [Fix]NoiseCancellation activation (part 2)
  DemoApp/Sources/Components/MemoryLogDestination/OSLogDestination.swift
  Sources/StreamVideo/Call.swift
  Sources/StreamVideo/StreamVideo.swift
  Sources/StreamVideo/WebRTC/AudioFilter/Filters/NoiseCancellationFilter.swift
Labels: bug

#712 [CI] Downgrade Xcode version for E2E tests
  .github/workflows/cron-checks.yml
  .github/workflows/smoke-checks.yml
Labels: CI/CD

#713 [Revert][CI] Downgrade Xcode version for E2E tests
  .github/workflows/cron-checks.yml
  .github/workflows/smoke-checks.yml
Labels: CI/CD

#707 [Improvement]Handle blocked users
  CHANGELOG.md
  Sources/StreamVideo/Controllers/CallController.swift
  Sources/StreamVideo/Errors/Errors.swift
  Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Blocked.swift
  Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Stage.swift
  Sources/StreamVideoSwiftUI/CallViewModel.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoTests/Controllers/CallController_Tests.swift
  StreamVideoTests/Utils/StateMachine/StreamStateMachine_Tests.swift
  StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_BlockedStageTests.swift
Labels: enhancement

#716 [Fix]InApp screensharing
  DemoApp/Sources/Controls/DemoMoreControls/DemoBroadcastMoreControlsListButtonView.swift
  DemoApp/Sources/ViewModifiers/MoreControls/DemoMoreControlsViewModifier.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalScreenShareMediaAdapter.swift
  Sources/StreamVideo/WebRTC/v2/VideoCapturing/ActionHandlers/ScreenShare/ScreenShareCaptureHandler.swift
  Sources/StreamVideoSwiftUI/CallViewModel.swift
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamPictureInPictureController.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoSwiftUITests/CallViewModel_Tests.swift
  StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalScreenShareMediaAdapter_Tests.swift
  SwiftUIDemoAppUITests/Pages/CallDetailsPage.swift
Labels: bug

#719 [Fix]Make StateMachine invalid transitions warnings rather than errors
  DemoApp/Sources/Components/MemoryLogDestination/MemoryLogViewer.swift
  DemoApp/Sources/Views/CallTopView/DemoCallTopView.swift
  Sources/StreamVideo/Call.swift
  Sources/StreamVideo/Controllers/CallController.swift
  Sources/StreamVideo/Utils/StateMachine/CallStateMachine/StreamCallStateMachine.swift
  Sources/StreamVideo/Utils/StateMachine/StreamStateMachine.swift
  Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Connecting.swift
  Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Disconnected.swift
  Sources/StreamVideo/WebRTC/v2/StateMachine/WebRTCCoordinator+StateMachine.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCCoordinator.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoTests/Controllers/CallController_Tests.swift
  StreamVideoTests/Utils/StateMachine/CallStateMachine/StreamCallStateMachine_Tests.swift
  StreamVideoTests/Utils/StateMachine/StreamStateMachine_Tests.swift
  StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_DisconnectedStageTests.swift
  StreamVideoTests/WebRTC/v2/StateMachine/WebRTCCoordinator_StateMachineTests.swift
Labels: bug, enhancement

#718 [Fix]MicrophoneChecker receiveOn crash
  CHANGELOG.md
  Sources/StreamVideoSwiftUI/CallingViews/MicrophoneChecker.swift
  StreamVideoSwiftUITests/CallingViews/MicrophoneChecker_Tests.swift
Labels: bug

#721 [CI] Lock Ruby 3.1.0
  .github/actions/ruby-cache/action.yml
Labels: CI/CD

#723 [Fix]Deactivate PiP when the app is in foreground
  CHANGELOG.md
  Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamPictureInPictureController.swift
Labels: bug

#722 [Demo]Integrate Gleap for better feedback reporting
  DemoApp/Sources/Components/AppState.swift
  DemoApp/Sources/Components/Gleap/GleapAdapter.swift
  DemoApp/Sources/Components/MemoryLogDestination/LogQueue.swift
  DemoApp/Sources/ViewModifiers/MoreControls/DemoMoreControlsViewModifier.swift
  DemoApp/Sources/Views/CallTopView/DemoCallTopView.swift
  StreamVideo.xcodeproj/project.pbxproj
Labels: enhancement

#725 [CI] Remove all the SwiftUICore module shadows in xcframeworks
  fastlane/Fastfile
Labels: CI/CD

#727 Update StreamWebRTC
  CHANGELOG.md
  Package.swift
  StreamVideo-XCFramework.podspec
  StreamVideo.podspec
  StreamVideo.xcodeproj/project.pbxproj
  SwiftUIDemoAppUITests/Tests/CallViewsTests.swift
Labels: CI/CD

#729 [CI] Provide app version on TestFlight upload
  fastlane/Fastfile
Labels: CI/CD

#730 Update SwiftProtobuf required version
  Package.swift
Labels: enhancement

#734 [Fix]Avoid current user showing up as duplicated during reconnection and migration
  CHANGELOG.md
  Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Joining.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift
  StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_JoiningStageTests.swift
  StreamVideoTests/WebRTC/v2/WebRTCStateAdapter_Tests.swift
Labels: bug

#737 [Fix]Bind transcription and noise cancelling to session
  Sources/StreamVideo/Call.swift
Labels: enhancement

#736 [Fix]Livestream participants count
  CHANGELOG.md
  Sources/StreamVideo/WebSockets/Client/WebSocketClient.swift
  Sources/StreamVideoSwiftUI/Livestreaming/LivestreamPlayer.swift
  StreamVideoTests/WebSocketClient/WebSocketClient_Tests.swift
Labels: bug

#733 [Fix]CallKit accepted events should be handled only for the current user
  CHANGELOG.md
  Sources/StreamVideo/CallKit/CallKitService.swift
  StreamVideoTests/CallKit/CallKitServiceTests.swift
Labels: bug
