Repository GetStream/stream-video-swift, pull requests merged in 2025-07, with the labels that each got.

#881 [Enhancement]Include the capturer preferredMediaSubtype in the requirements for the capturing format
  Sources/StreamVideo/Utils/AudioSession/Policies/OwnCapabilitiesAudioSessionPolicy.swift
  Sources/StreamVideo/WebRTC/v2/Extensions/AVFoundation/AVCaptureDevice+OutputFormat.swift
  Sources/StreamVideo/WebRTC/v2/Extensions/AVFoundation/AVCaptureDevice.Format+MediaSubType.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/Protocols/CaptureDeviceProtocol.swift
  Sources/StreamVideo/WebRTC/v2/VideoCapturing/ActionHandlers/Camera/CameraCaptureHandler.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoTests/Mock/MockCaptureDevice.swift
Labels: enhancement

#885 Fix issue with CallKit audio not working
  .swiftlint.yml
  Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift
Labels: ✅ QAed

#889 [Fix]Call event overflow
  Sources/StreamVideoSwiftUI/CallViewModel.swift
  StreamVideoSwiftUITests/CallViewModel_Tests.swift
Labels: bug

#888 [Enhancement]Incoming video pause
  CHANGELOG.md
  DemoApp/Sources/Components/AppEnvironment.swift
  DemoApp/Sources/Views/CallView/CallingView/SimpleCallingView.swift
  DemoApp/Sources/Views/Login/DebugMenu.swift
  DemoApp/Sources/Views/Reactions/ReactionOverlayView.swift
  DemoApp/Sources/Views/Reactions/ReactionsViewModifier.swift
  DocumentationTests/DocumentationTests/DocumentationTests.xcodeproj/project.pbxproj
  DocumentationTests/DocumentationTests/DocumentationTests/05-ui-cookbook/25-incoming-video-state.swift
  DocumentationTests/DocumentationTests/DocumentationTests/GloballyUsedVariables.swift
  Sources/StreamVideo/Call.swift
  Sources/StreamVideo/Controllers/CallController.swift
  Sources/StreamVideo/Models/CallParticipant.swift
  Sources/StreamVideo/Models/ClientCapability.swift
  Sources/StreamVideo/Models/Extensions/Stream_Video_Sfu_Models_Participant+CallParticipant.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/Models/TrackType.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/Protocols/RTCPeerConnectionCoordinatorProviding.swift
  Sources/StreamVideo/WebRTC/v2/PeerConnection/RTCPeerConnectionCoordinator.swift
  Sources/StreamVideo/WebRTC/v2/SFU/SFUEventAdapter.swift
  Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Joined.swift
  Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Joining.swift
  Sources/StreamVideo/WebRTC/v2/UpdateSubscriptions/WebRTCUpdateSubscriptionsAdapter.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCCoordinator.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCJoinRequestFactory.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift
  Sources/StreamVideoSwiftUI/CallView/VideoParticipantsView.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoTests/Call/Call_Tests.swift
  StreamVideoTests/Controllers/CallController_Tests.swift
  StreamVideoTests/Mock/CallParticipant_Mock.swift
  StreamVideoTests/Mock/MockCallController.swift
  StreamVideoTests/Mock/MockRTCPeerConnectionCoordinator.swift
  StreamVideoTests/Mock/MockRTCPeerConnectionCoordinatorFactory.swift
  StreamVideoTests/Mock/MockRTCPeerConnectionCoordinatorStack.swift
  StreamVideoTests/Models/CallParticipants_Tests.swift
  StreamVideoTests/WebRTC/SFU/SFUEventAdapter_Tests.swift
  StreamVideoTests/WebRTC/v2/PeerConnection/RTCPeerConnectionCoordinator_Tests.swift
  StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_JoiningStageTests.swift
  StreamVideoTests/WebRTC/v2/UpdateSubscriptions/WebRTCUpdateSubscriptionsAdapter_Tests.swift
  StreamVideoTests/WebRTC/v2/WebRTCCoorindator_Tests.swift
  StreamVideoTests/WebRTC/v2/WebRTCJoinRequestFactory_Tests.swift
  StreamVideoTests/WebRTC/v2/WebRTCStateAdapter_Tests.swift
  TestTools/TestData/ViewFactory.swift
Labels: enhancement

#891 [Enhancement]Improve tracing
  Sources/StreamVideo/Call.swift
  Sources/StreamVideo/CallKit/CallKitService.swift
  Sources/StreamVideo/Controllers/CallController.swift
  Sources/StreamVideo/Utils/AudioSession/StreamAudioSession.swift
  Sources/StreamVideo/Utils/AudioSession/StreamRTCAudioSession.swift
  Sources/StreamVideo/Utils/StreamAppStateAdapter/StreamAppStateAdapter.swift
  Sources/StreamVideo/WebRTC/PeerConnectionFactory.swift
  Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Joined.swift
  Sources/StreamVideo/WebRTC/v2/Stats/Models/WebRTCTrace.swift
  Sources/StreamVideo/WebRTC/v2/Stats/Traces/WebRTCTracesAdapter.swift
  Sources/StreamVideo/WebRTC/v2/Stats/Traces/WebRTCTracing.swift
  Sources/StreamVideo/WebRTC/v2/Stats/WebRTCStatsAdapter.swift
  Sources/StreamVideo/WebRTC/v2/Stats/WebRTCStatsAdapting.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCCoordinator.swift
  Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift
  StreamVideoTests/Mock/MockAudioSession.swift
  StreamVideoTests/Mock/MockRTCPeerConnectionCoordinatorStack.swift
  StreamVideoTests/Mock/MockWebRTCStatsAdapter.swift
  StreamVideoTests/Mock/MockWebRTCTracesAdapter.swift
  StreamVideoTests/Utils/AudioSession/StreamAudioSession_Tests.swift
  StreamVideoTests/Utils/Proximity/Policies/SpeakerProximityPolicy_Tests.swift
  StreamVideoTests/Utils/StreamCallAudioRecorderTests.swift
  StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/AudioMediaAdapter_Tests.swift
  StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalAudioMediaAdapter_Tests.swift
  StreamVideoTests/WebRTC/v2/PeerConnection/RTCPeerConnectionCoordinator_Tests.swift
  StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_JoinedStageTests.swift
  StreamVideoTests/WebRTC/v2/Stats/Models/WebRTCTrace_Tests.swift
  StreamVideoTests/WebRTC/v2/Stats/Traces/WebRTCTracesAdapter_Tests.swift
  StreamVideoTests/WebRTC/v2/Stats/WebRTCStatsAdapter_Tests.swift
Labels: enhancement

#892 [Enhancement]WebRTC logs via SDK logger
  DemoApp/Sources/Components/AppEnvironment.swift
  DemoApp/Sources/Extensions/DemoApp+Sentry.swift
  DemoApp/Sources/Views/Login/DebugMenu.swift
  Sources/StreamVideo/Utils/Logger/Logger.swift
  Sources/StreamVideo/Utils/Logger/WebRTCLogger.swift
  StreamVideo.xcodeproj/project.pbxproj
Labels: enhancement

#893 [Enhancement]Improve Stats for Join and UpdateSubscriptions
  Sources/StreamVideo/Utils/SelectiveEncodable/Protobuf+SelectiveEncodable.swift
  Sources/StreamVideo/Utils/SelectiveEncodable/SelectiveEncodable.swift
Labels: enhancement

#901 [Fix]CallViewModel ending outgoing group call when one of the participants rejects
  CHANGELOG.md
  Sources/StreamVideoSwiftUI/CallViewModel.swift
  StreamVideo.xcodeproj/project.pbxproj
  StreamVideoSwiftUITests/CallViewModel_Tests.swift
  StreamVideoTests/Mock/MockCall.swift
  StreamVideoTests/Mock/MockDefaultAPI.swift
Labels: bug
